export const MOCK_PATIENTS = [
  {
    id: 'pat1',
    name: 'Jan de Vries',
    email: 'jan@example.com',
    avatarInitials: 'JV',
    programId: 'p1',
    programName: 'Knie Revalidatie — Fase 1',
    programStatus: 'ACTIVE',
    weeksCurrent: 2,
    weeksTotal: 4,
    lastSessionDate: '2025-03-28',
    lastPainLevel: 3,
    compliance: 87,
    sessionsCompleted: 7,
    sessionsTotal: 8,
    nextSessionDay: 'Maandag',
    tags: ['VKB', 'Post-operatief'],
  },
  {
    id: 'pat2',
    name: 'Maria Jansen',
    email: 'maria@example.com',
    avatarInitials: 'MJ',
    programId: 'p2',
    programName: 'Schouder Stabilisatie',
    programStatus: 'DRAFT',
    weeksCurrent: 0,
    weeksTotal: 6,
    lastSessionDate: null,
    lastPainLevel: null,
    compliance: 0,
    sessionsCompleted: 0,
    sessionsTotal: 12,
    nextSessionDay: null,
    tags: ['SLAP laesie'],
  },
  {
    id: 'pat3',
    name: 'Thomas van Berg',
    email: 'thomas@example.com',
    avatarInitials: 'TB',
    programId: null,
    programName: null,
    programStatus: null,
    weeksCurrent: 0,
    weeksTotal: 0,
    lastSessionDate: null,
    lastPainLevel: null,
    compliance: 0,
    sessionsCompleted: 0,
    sessionsTotal: 0,
    nextSessionDay: null,
    tags: ['Intake gepland'],
  },
  {
    id: 'pat4',
    name: 'Sophie Dekker',
    email: 'sophie@example.com',
    avatarInitials: 'SD',
    programId: 'p3',
    programName: 'Heup Mobiliteit',
    programStatus: 'COMPLETED',
    weeksCurrent: 3,
    weeksTotal: 3,
    lastSessionDate: '2025-03-20',
    lastPainLevel: 2,
    compliance: 100,
    sessionsCompleted: 12,
    sessionsTotal: 12,
    nextSessionDay: null,
    tags: ['Afgerond'],
  },
]
