/**
 * Standard exercise database — common exercises for physiotherapy and strength training.
 * No videos attached; therapists/athletes can add their own later.
 * Includes movement pattern, load type, and muscle loads for auto-strain estimation.
 */

type SeedExercise = {
  name: string
  description: string
  category: 'STRENGTH' | 'MOBILITY' | 'PLYOMETRICS' | 'CARDIO' | 'STABILITY'
  bodyRegion: string[]
  difficulty: 'BEGINNER' | 'INTERMEDIATE' | 'ADVANCED'
  loadType: 'BODYWEIGHT' | 'WEIGHTED' | 'MACHINE' | 'BAND'
  isUnilateral: boolean
  movementPattern: string | null
  tags: string[]
  instructions: string[]
  muscleLoads: Record<string, number>
}

export const STANDARD_EXERCISES: SeedExercise[] = [
  // ═══════════════════════════════════════════════════════════════════════════
  // LOWER BODY — SQUAT PATTERNS
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'Back Squat',
    description: 'Bilaterale squatvariant met barbell op de bovenrug.',
    category: 'STRENGTH',
    bodyRegion: ['KNEE', 'HIP'],
    difficulty: 'INTERMEDIATE',
    loadType: 'WEIGHTED',
    isUnilateral: false,
    movementPattern: 'SQUAT',
    tags: ['squat', 'benen', 'compound'],
    instructions: ['Plaats de barbell op je bovenrug', 'Voeten op schouderbreedte', 'Zak tot minstens parallel', 'Druk door de hakken omhoog'],
    muscleLoads: { Quadriceps: 5, Glutes: 4, Hamstrings: 3, Core: 3, Calves: 2 },
  },
  {
    name: 'Front Squat',
    description: 'Squat met de barbell op de voorste schouders. Meer nadruk op quadriceps.',
    category: 'STRENGTH',
    bodyRegion: ['KNEE', 'HIP'],
    difficulty: 'ADVANCED',
    loadType: 'WEIGHTED',
    isUnilateral: false,
    movementPattern: 'SQUAT',
    tags: ['squat', 'benen', 'quadriceps'],
    instructions: ['Barbell op voorste deltoids', 'Ellebogen hoog houden', 'Zak diep met rechte romp', 'Druk omhoog vanuit de hakken'],
    muscleLoads: { Quadriceps: 5, Glutes: 3, Core: 4, Calves: 2 },
  },
  {
    name: 'Goblet Squat',
    description: 'Squat met een dumbbell of kettlebell voor de borst.',
    category: 'STRENGTH',
    bodyRegion: ['KNEE', 'HIP'],
    difficulty: 'BEGINNER',
    loadType: 'WEIGHTED',
    isUnilateral: false,
    movementPattern: 'SQUAT',
    tags: ['squat', 'benen', 'beginner'],
    instructions: ['Houd het gewicht tegen je borst', 'Voeten iets breder dan schouderbreedte', 'Zak naar beneden met de ellebogen binnen de knieën'],
    muscleLoads: { Quadriceps: 4, Glutes: 3, Core: 2 },
  },
  {
    name: 'Bulgarian Split Squat',
    description: 'Unilaterale squat met achterste voet op een verhoging.',
    category: 'STRENGTH',
    bodyRegion: ['KNEE', 'HIP'],
    difficulty: 'INTERMEDIATE',
    loadType: 'BODYWEIGHT',
    isUnilateral: true,
    movementPattern: 'LUNGE',
    tags: ['squat', 'unilateraal', 'benen'],
    instructions: ['Achterste voet op bank of verhoging', 'Zak recht naar beneden', 'Knie blijft boven de tenen'],
    muscleLoads: { Quadriceps: 5, Glutes: 4, Hamstrings: 2, Core: 2 },
  },
  {
    name: 'Pistol Squat',
    description: 'Single-leg squat zonder steun.',
    category: 'STRENGTH',
    bodyRegion: ['KNEE', 'HIP', 'ANKLE'],
    difficulty: 'ADVANCED',
    loadType: 'BODYWEIGHT',
    isUnilateral: true,
    movementPattern: 'SQUAT',
    tags: ['squat', 'unilateraal', 'balans'],
    instructions: ['Sta op één been', 'Strek het andere been naar voren', 'Zak zo diep mogelijk', 'Sta op zonder hulp'],
    muscleLoads: { Quadriceps: 5, Glutes: 4, Hamstrings: 3, Core: 3, Calves: 2, 'Hip flexors': 2 },
  },
  {
    name: 'Bodyweight Squat',
    description: 'Basis squat zonder extra gewicht.',
    category: 'STRENGTH',
    bodyRegion: ['KNEE', 'HIP'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'SQUAT',
    tags: ['squat', 'beginner', 'lichaamsgewicht'],
    instructions: ['Voeten op schouderbreedte', 'Zak tot parallel', 'Houd borst omhoog', 'Druk door de hakken'],
    muscleLoads: { Quadriceps: 3, Glutes: 3, Calves: 1 },
  },
  {
    name: 'Wall Sit',
    description: 'Isometrische squat tegen de muur.',
    category: 'STRENGTH',
    bodyRegion: ['KNEE'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'SQUAT',
    tags: ['isometrisch', 'knie', 'beginner'],
    instructions: ['Leun met rug tegen muur', 'Zak tot 90 graden in de knieën', 'Houd de positie vast'],
    muscleLoads: { Quadriceps: 4, Glutes: 2 },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // LOWER BODY — LUNGE PATTERNS
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'Walking Lunge',
    description: 'Voorwaartse lunges in beweging.',
    category: 'STRENGTH',
    bodyRegion: ['KNEE', 'HIP'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: true,
    movementPattern: 'LUNGE',
    tags: ['lunge', 'benen', 'dynamisch'],
    instructions: ['Neem een grote stap naar voren', 'Zak tot 90 graden in beide knieën', 'Druk af en breng het achterste been naar voren'],
    muscleLoads: { Quadriceps: 4, Glutes: 4, Hamstrings: 2, 'Hip flexors': 2, Core: 2 },
  },
  {
    name: 'Reverse Lunge',
    description: 'Lunge naar achteren — vriendelijker voor de knieën.',
    category: 'STRENGTH',
    bodyRegion: ['KNEE', 'HIP'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: true,
    movementPattern: 'LUNGE',
    tags: ['lunge', 'benen', 'knie-vriendelijk'],
    instructions: ['Stap naar achteren', 'Zak tot 90 graden', 'Druk vanuit de voorste voet terug'],
    muscleLoads: { Quadriceps: 3, Glutes: 4, Hamstrings: 2, Core: 2 },
  },
  {
    name: 'Lateral Lunge',
    description: 'Zijwaartse lunge voor adductoren en laterale stabiliteit.',
    category: 'STRENGTH',
    bodyRegion: ['KNEE', 'HIP'],
    difficulty: 'INTERMEDIATE',
    loadType: 'BODYWEIGHT',
    isUnilateral: true,
    movementPattern: 'LUNGE',
    tags: ['lunge', 'lateraal', 'adductoren'],
    instructions: ['Stap zijwaarts', 'Zak in het gebogen been', 'Houd het rechte been gestrekt', 'Druk terug naar start'],
    muscleLoads: { Quadriceps: 3, Glutes: 3, Adductoren: 4, Abductoren: 2 },
  },
  {
    name: 'Step Up',
    description: 'Op een verhoging stappen — functionele unilaterale oefening.',
    category: 'STRENGTH',
    bodyRegion: ['KNEE', 'HIP'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: true,
    movementPattern: 'LUNGE',
    tags: ['step-up', 'functioneel', 'unilateraal'],
    instructions: ['Plaats één voet op de verhoging', 'Druk je omhoog vanuit die voet', 'Laat gecontroleerd weer zakken'],
    muscleLoads: { Quadriceps: 4, Glutes: 4, Calves: 2 },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // LOWER BODY — HINGE PATTERNS
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'Romanian Deadlift (RDL)',
    description: 'Hip hinge met nadruk op hamstrings en glutes.',
    category: 'STRENGTH',
    bodyRegion: ['HIP', 'BACK'],
    difficulty: 'INTERMEDIATE',
    loadType: 'WEIGHTED',
    isUnilateral: false,
    movementPattern: 'HINGE',
    tags: ['deadlift', 'hamstrings', 'hinge'],
    instructions: ['Houd barbell/dumbbells dicht bij lichaam', 'Hinge vanuit de heupen', 'Lichte buiging in de knieën', 'Voel rek in hamstrings, sta terug op'],
    muscleLoads: { Hamstrings: 5, Glutes: 4, Onderrug: 3, Bovenrug: 2, Core: 2 },
  },
  {
    name: 'Conventional Deadlift',
    description: 'Compound tilbeweging vanaf de grond.',
    category: 'STRENGTH',
    bodyRegion: ['HIP', 'BACK', 'KNEE'],
    difficulty: 'INTERMEDIATE',
    loadType: 'WEIGHTED',
    isUnilateral: false,
    movementPattern: 'HINGE',
    tags: ['deadlift', 'compound', 'kracht'],
    instructions: ['Voeten op heupbreedte', 'Grijp de stang net buiten de knieën', 'Borst omhoog, rug neutraal', 'Druk door benen en heupen tegelijk'],
    muscleLoads: { Hamstrings: 4, Glutes: 5, Onderrug: 4, Quadriceps: 3, Bovenrug: 3, Core: 3, Onderarmen: 2 },
  },
  {
    name: 'Single Leg Deadlift',
    description: 'Unilaterale hip hinge met balanselement.',
    category: 'STABILITY',
    bodyRegion: ['HIP', 'BACK', 'ANKLE'],
    difficulty: 'INTERMEDIATE',
    loadType: 'BODYWEIGHT',
    isUnilateral: true,
    movementPattern: 'HINGE',
    tags: ['deadlift', 'balans', 'unilateraal'],
    instructions: ['Sta op één been', 'Hinge naar voren', 'Achterste been strekt naar achteren', 'Houd rug neutraal'],
    muscleLoads: { Hamstrings: 4, Glutes: 4, Core: 3, Calves: 2 },
  },
  {
    name: 'Good Morning',
    description: 'Hip hinge met barbell op de rug.',
    category: 'STRENGTH',
    bodyRegion: ['HIP', 'BACK'],
    difficulty: 'INTERMEDIATE',
    loadType: 'WEIGHTED',
    isUnilateral: false,
    movementPattern: 'HINGE',
    tags: ['hinge', 'hamstrings', 'onderrug'],
    instructions: ['Barbell op de bovenrug', 'Lichte buiging in knieën', 'Hinge voorover vanuit de heupen', 'Sta terug op met gestrekte heupen'],
    muscleLoads: { Hamstrings: 4, Glutes: 3, Onderrug: 4, Core: 3 },
  },
  {
    name: 'Nordic Hamstring Curl',
    description: 'Excentrische hamstringtraining voor blessurepreventie.',
    category: 'STRENGTH',
    bodyRegion: ['KNEE'],
    difficulty: 'ADVANCED',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'ISOLATION_LOWER',
    tags: ['hamstrings', 'excentrisch', 'preventie'],
    instructions: ['Kniel met enkels gefixeerd', 'Laat je romp gecontroleerd naar voren zakken', 'Rem de beweging af met je hamstrings', 'Vang op met handen'],
    muscleLoads: { Hamstrings: 5, Glutes: 3, Core: 2 },
  },
  {
    name: 'Kettlebell Swing',
    description: 'Explosieve hip hinge met kettlebell.',
    category: 'STRENGTH',
    bodyRegion: ['HIP', 'BACK'],
    difficulty: 'INTERMEDIATE',
    loadType: 'WEIGHTED',
    isUnilateral: false,
    movementPattern: 'HINGE',
    tags: ['kettlebell', 'explosief', 'hinge'],
    instructions: ['Hinge met kettlebell tussen benen', 'Explosief heupen strekken', 'Kettlebell swingt tot schouderhoogte', 'Controleer de terugzwaai'],
    muscleLoads: { Glutes: 5, Hamstrings: 4, Core: 3, 'Schouders anterieur': 2, Onderrug: 2 },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // LOWER BODY — HIP THRUST & GLUTES
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'Barbell Hip Thrust',
    description: 'Geïsoleerde glutestraining met barbell.',
    category: 'STRENGTH',
    bodyRegion: ['HIP'],
    difficulty: 'INTERMEDIATE',
    loadType: 'WEIGHTED',
    isUnilateral: false,
    movementPattern: 'HIP_THRUST',
    tags: ['glutes', 'hip thrust', 'kracht'],
    instructions: ['Bovenbrug op bank, schouderbladen', 'Barbell over de heupen', 'Druk heupen omhoog tot volledige extensie', 'Knijp glutes bovenaan'],
    muscleLoads: { Glutes: 5, Hamstrings: 3, Core: 2 },
  },
  {
    name: 'Glute Bridge',
    description: 'Basis gluteoefening liggend op de grond.',
    category: 'STRENGTH',
    bodyRegion: ['HIP'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'HIP_THRUST',
    tags: ['glutes', 'bridge', 'beginner'],
    instructions: ['Lig op je rug, knieën gebogen', 'Druk heupen omhoog', 'Knijp glutes bovenaan', 'Laat langzaam zakken'],
    muscleLoads: { Glutes: 4, Hamstrings: 2, Core: 2 },
  },
  {
    name: 'Single Leg Glute Bridge',
    description: 'Unilaterale glute bridge voor symmetrie.',
    category: 'STRENGTH',
    bodyRegion: ['HIP'],
    difficulty: 'INTERMEDIATE',
    loadType: 'BODYWEIGHT',
    isUnilateral: true,
    movementPattern: 'HIP_THRUST',
    tags: ['glutes', 'unilateraal', 'bridge'],
    instructions: ['Lig op je rug, één been gestrekt', 'Druk heupen omhoog met het steunbeen', 'Houd heupen level'],
    muscleLoads: { Glutes: 5, Hamstrings: 3, Core: 3 },
  },
  {
    name: 'Clamshell',
    description: 'Gluteus medius activatie met weerstandsband.',
    category: 'STABILITY',
    bodyRegion: ['HIP'],
    difficulty: 'BEGINNER',
    loadType: 'BAND',
    isUnilateral: true,
    movementPattern: 'ISOLATION_LOWER',
    tags: ['glutes', 'activatie', 'band'],
    instructions: ['Lig op je zij, knieën gebogen', 'Band om de knieën', 'Open de bovenste knie als een schelp', 'Houd voeten bij elkaar'],
    muscleLoads: { Glutes: 3, Abductoren: 4 },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // LOWER BODY — CALVES & ISOLATION
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'Calf Raise (staand)',
    description: 'Staande kuitoefening op een verhoging.',
    category: 'STRENGTH',
    bodyRegion: ['ANKLE'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'CALF_RAISE',
    tags: ['kuiten', 'beginner'],
    instructions: ['Sta op de rand van een trede', 'Druk omhoog op je tenen', 'Laat langzaam zakken onder de rand'],
    muscleLoads: { Calves: 5 },
  },
  {
    name: 'Leg Extension (machine)',
    description: 'Geïsoleerde quadricepstraining.',
    category: 'STRENGTH',
    bodyRegion: ['KNEE'],
    difficulty: 'BEGINNER',
    loadType: 'MACHINE',
    isUnilateral: false,
    movementPattern: 'ISOLATION_LOWER',
    tags: ['quadriceps', 'isolatie', 'machine'],
    instructions: ['Zit met rug tegen het kussen', 'Strek de benen volledig', 'Laat gecontroleerd zakken'],
    muscleLoads: { Quadriceps: 5 },
  },
  {
    name: 'Leg Curl (machine)',
    description: 'Geïsoleerde hamstringtraining.',
    category: 'STRENGTH',
    bodyRegion: ['KNEE'],
    difficulty: 'BEGINNER',
    loadType: 'MACHINE',
    isUnilateral: false,
    movementPattern: 'ISOLATION_LOWER',
    tags: ['hamstrings', 'isolatie', 'machine'],
    instructions: ['Lig op je buik of zit in de machine', 'Buig de knieën volledig', 'Laat gecontroleerd terug'],
    muscleLoads: { Hamstrings: 5 },
  },
  {
    name: 'Leg Press',
    description: 'Compound beenpers op de machine.',
    category: 'STRENGTH',
    bodyRegion: ['KNEE', 'HIP'],
    difficulty: 'BEGINNER',
    loadType: 'MACHINE',
    isUnilateral: false,
    movementPattern: 'SQUAT',
    tags: ['benen', 'compound', 'machine'],
    instructions: ['Plaats voeten op schouderbreedte', 'Laat het gewicht zakken tot 90 graden', 'Druk omhoog zonder knieën te locken'],
    muscleLoads: { Quadriceps: 5, Glutes: 4, Hamstrings: 2, Calves: 1 },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // UPPER BODY — PUSH HORIZONTAL
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'Bench Press',
    description: 'Horizontale druk met barbell op een bank.',
    category: 'STRENGTH',
    bodyRegion: ['SHOULDER'],
    difficulty: 'INTERMEDIATE',
    loadType: 'WEIGHTED',
    isUnilateral: false,
    movementPattern: 'PUSH_HORIZONTAL',
    tags: ['borst', 'bench press', 'compound'],
    instructions: ['Lig op de bank, voeten op de grond', 'Barbell op borsthoogte', 'Laat zakken tot de borst', 'Druk omhoog tot volledige extensie'],
    muscleLoads: { Borst: 5, Triceps: 4, 'Schouders anterieur': 3 },
  },
  {
    name: 'Push-Up',
    description: 'Basis borstspiertraining met lichaamsgewicht.',
    category: 'STRENGTH',
    bodyRegion: ['SHOULDER'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'PUSH_HORIZONTAL',
    tags: ['borst', 'push-up', 'lichaamsgewicht'],
    instructions: ['Handen op schouderbreedte', 'Lichaam in rechte lijn', 'Zak tot borst bijna de grond raakt', 'Druk omhoog'],
    muscleLoads: { Borst: 4, Triceps: 3, 'Schouders anterieur': 2, Core: 2 },
  },
  {
    name: 'Dumbbell Chest Press',
    description: 'Horizontale druk met dumbbells.',
    category: 'STRENGTH',
    bodyRegion: ['SHOULDER'],
    difficulty: 'INTERMEDIATE',
    loadType: 'WEIGHTED',
    isUnilateral: false,
    movementPattern: 'PUSH_HORIZONTAL',
    tags: ['borst', 'dumbbells', 'drukken'],
    instructions: ['Lig op bank met dumbbells', 'Druk omhoog tot armen gestrekt', 'Laat gecontroleerd zakken'],
    muscleLoads: { Borst: 5, Triceps: 3, 'Schouders anterieur': 3 },
  },
  {
    name: 'Incline Bench Press',
    description: 'Schuine bankdrukken voor bovenborst.',
    category: 'STRENGTH',
    bodyRegion: ['SHOULDER'],
    difficulty: 'INTERMEDIATE',
    loadType: 'WEIGHTED',
    isUnilateral: false,
    movementPattern: 'PUSH_HORIZONTAL',
    tags: ['borst', 'incline', 'bovenborst'],
    instructions: ['Bank op 30-45 graden', 'Druk gewicht omhoog', 'Laat zakken tot borsthoogte'],
    muscleLoads: { Borst: 4, 'Schouders anterieur': 4, Triceps: 3 },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // UPPER BODY — PUSH VERTICAL
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'Overhead Press',
    description: 'Staande schouderpers met barbell.',
    category: 'STRENGTH',
    bodyRegion: ['SHOULDER'],
    difficulty: 'INTERMEDIATE',
    loadType: 'WEIGHTED',
    isUnilateral: false,
    movementPattern: 'PUSH_VERTICAL',
    tags: ['schouders', 'press', 'compound'],
    instructions: ['Barbell op sleutelbeenhoogte', 'Druk recht omhoog', 'Lock uit boven het hoofd', 'Laat gecontroleerd zakken'],
    muscleLoads: { 'Schouders anterieur': 5, 'Schouders lateraal': 3, Triceps: 3, Core: 2 },
  },
  {
    name: 'Dumbbell Shoulder Press',
    description: 'Schouderpers met dumbbells.',
    category: 'STRENGTH',
    bodyRegion: ['SHOULDER'],
    difficulty: 'INTERMEDIATE',
    loadType: 'WEIGHTED',
    isUnilateral: false,
    movementPattern: 'PUSH_VERTICAL',
    tags: ['schouders', 'dumbbells', 'press'],
    instructions: ['Dumbbells op schouderhoogte', 'Druk omhoog tot armen gestrekt', 'Laat gecontroleerd zakken'],
    muscleLoads: { 'Schouders anterieur': 5, 'Schouders lateraal': 3, Triceps: 3 },
  },
  {
    name: 'Lateral Raise',
    description: 'Isolatieoefening voor laterale deltoid.',
    category: 'STRENGTH',
    bodyRegion: ['SHOULDER'],
    difficulty: 'BEGINNER',
    loadType: 'WEIGHTED',
    isUnilateral: false,
    movementPattern: 'ISOLATION_UPPER',
    tags: ['schouders', 'lateraal', 'isolatie'],
    instructions: ['Dumbbells langs het lichaam', 'Hef zijwaarts tot schouderhoogte', 'Laat gecontroleerd zakken'],
    muscleLoads: { 'Schouders lateraal': 5, 'Schouders anterieur': 2 },
  },
  {
    name: 'Face Pull',
    description: 'Kabel- of bandoefening voor achterste schouders.',
    category: 'STRENGTH',
    bodyRegion: ['SHOULDER'],
    difficulty: 'BEGINNER',
    loadType: 'BAND',
    isUnilateral: false,
    movementPattern: 'PULL_HORIZONTAL',
    tags: ['schouders', 'posterieur', 'band'],
    instructions: ['Trek kabel/band naar gezicht', 'Houd ellebogen hoog', 'Knijp schouderbladen samen', 'Laat gecontroleerd terug'],
    muscleLoads: { 'Schouders posterieur': 4, Rotatorcuff: 3, Bovenrug: 2 },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // UPPER BODY — PULL HORIZONTAL
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'Barbell Row',
    description: 'Horizontale roeibeweging met barbell.',
    category: 'STRENGTH',
    bodyRegion: ['BACK'],
    difficulty: 'INTERMEDIATE',
    loadType: 'WEIGHTED',
    isUnilateral: false,
    movementPattern: 'PULL_HORIZONTAL',
    tags: ['rug', 'row', 'compound'],
    instructions: ['Hinge voorover met rechte rug', 'Trek barbell naar de buik', 'Knijp schouderbladen samen', 'Laat gecontroleerd zakken'],
    muscleLoads: { Bovenrug: 5, Lats: 3, Biceps: 3, 'Schouders posterieur': 2, Onderarmen: 2 },
  },
  {
    name: 'Dumbbell Row (single arm)',
    description: 'Unilaterale roeibeweging met dumbbell.',
    category: 'STRENGTH',
    bodyRegion: ['BACK'],
    difficulty: 'BEGINNER',
    loadType: 'WEIGHTED',
    isUnilateral: true,
    movementPattern: 'PULL_HORIZONTAL',
    tags: ['rug', 'row', 'unilateraal'],
    instructions: ['Eén hand en knie op bank', 'Trek dumbbell naar de heup', 'Knijp schouderblad samen'],
    muscleLoads: { Bovenrug: 4, Lats: 4, Biceps: 3, 'Schouders posterieur': 2 },
  },
  {
    name: 'Cable Row (zittend)',
    description: 'Zittende kabelroeibeweging.',
    category: 'STRENGTH',
    bodyRegion: ['BACK'],
    difficulty: 'BEGINNER',
    loadType: 'MACHINE',
    isUnilateral: false,
    movementPattern: 'PULL_HORIZONTAL',
    tags: ['rug', 'row', 'kabel'],
    instructions: ['Zit met rechte rug', 'Trek handvat naar de buik', 'Schouderbladen samentrekken'],
    muscleLoads: { Bovenrug: 4, Lats: 3, Biceps: 3, Onderarmen: 2 },
  },
  {
    name: 'Inverted Row',
    description: 'Horizontaal roeien met lichaamsgewicht.',
    category: 'STRENGTH',
    bodyRegion: ['BACK'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'PULL_HORIZONTAL',
    tags: ['rug', 'row', 'lichaamsgewicht'],
    instructions: ['Hang onder een stang', 'Trek borst naar de stang', 'Houd lichaam in rechte lijn'],
    muscleLoads: { Bovenrug: 4, Biceps: 3, Core: 2, 'Schouders posterieur': 2 },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // UPPER BODY — PULL VERTICAL
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'Pull-Up',
    description: 'Verticaal trekken met lichaamsgewicht.',
    category: 'STRENGTH',
    bodyRegion: ['BACK', 'SHOULDER'],
    difficulty: 'INTERMEDIATE',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'PULL_VERTICAL',
    tags: ['rug', 'pull-up', 'compound'],
    instructions: ['Overhandse grip op schouderbreedte', 'Trek kin boven de stang', 'Laat gecontroleerd zakken tot volle hang'],
    muscleLoads: { Lats: 5, Biceps: 4, Bovenrug: 3, Onderarmen: 3 },
  },
  {
    name: 'Chin-Up',
    description: 'Verticaal trekken met onderhandse grip.',
    category: 'STRENGTH',
    bodyRegion: ['BACK', 'SHOULDER'],
    difficulty: 'INTERMEDIATE',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'PULL_VERTICAL',
    tags: ['rug', 'chin-up', 'biceps'],
    instructions: ['Onderhandse grip op schouderbreedte', 'Trek kin boven de stang', 'Nadruk op biceps'],
    muscleLoads: { Lats: 4, Biceps: 5, Bovenrug: 3, Onderarmen: 2 },
  },
  {
    name: 'Lat Pulldown',
    description: 'Machine-variant van de pull-up.',
    category: 'STRENGTH',
    bodyRegion: ['BACK'],
    difficulty: 'BEGINNER',
    loadType: 'MACHINE',
    isUnilateral: false,
    movementPattern: 'PULL_VERTICAL',
    tags: ['rug', 'lats', 'machine'],
    instructions: ['Brede overhandse grip', 'Trek stang naar de borst', 'Houd borst omhoog', 'Laat gecontroleerd terug'],
    muscleLoads: { Lats: 5, Biceps: 3, Bovenrug: 3, Onderarmen: 2 },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // UPPER BODY — ARM ISOLATION
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'Bicep Curl',
    description: 'Basis bicepsoefening met dumbbells.',
    category: 'STRENGTH',
    bodyRegion: ['ELBOW'],
    difficulty: 'BEGINNER',
    loadType: 'WEIGHTED',
    isUnilateral: false,
    movementPattern: 'ISOLATION_UPPER',
    tags: ['biceps', 'isolatie', 'armen'],
    instructions: ['Dumbbells langs het lichaam', 'Buig de ellebogen omhoog', 'Houd bovenarm stil', 'Laat gecontroleerd zakken'],
    muscleLoads: { Biceps: 5, Onderarmen: 2 },
  },
  {
    name: 'Tricep Dip',
    description: 'Tricepsoefening op parallelle stangen of bank.',
    category: 'STRENGTH',
    bodyRegion: ['ELBOW', 'SHOULDER'],
    difficulty: 'INTERMEDIATE',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'PUSH_HORIZONTAL',
    tags: ['triceps', 'dip', 'compound'],
    instructions: ['Steun op de stangen', 'Zak tot 90 graden in de ellebogen', 'Druk omhoog tot volledige extensie'],
    muscleLoads: { Triceps: 5, Borst: 3, 'Schouders anterieur': 3 },
  },
  {
    name: 'Tricep Pushdown (kabel)',
    description: 'Geïsoleerde tricepstraining aan de kabel.',
    category: 'STRENGTH',
    bodyRegion: ['ELBOW'],
    difficulty: 'BEGINNER',
    loadType: 'MACHINE',
    isUnilateral: false,
    movementPattern: 'ISOLATION_UPPER',
    tags: ['triceps', 'isolatie', 'kabel'],
    instructions: ['Sta voor de kabelmachine', 'Druk het touw/stang naar beneden', 'Houd ellebogen langs het lichaam'],
    muscleLoads: { Triceps: 5 },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // CORE
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'Plank',
    description: 'Isometrische core-oefening.',
    category: 'STABILITY',
    bodyRegion: ['LUMBAR'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'CORE',
    tags: ['core', 'plank', 'isometrisch'],
    instructions: ['Onderarmen en tenen op de grond', 'Lichaam in rechte lijn', 'Houd de positie vast', 'Niet laten doorzakken'],
    muscleLoads: { Core: 4, 'Schouders anterieur': 2, Onderrug: 2 },
  },
  {
    name: 'Side Plank',
    description: 'Laterale core stabiliteit.',
    category: 'STABILITY',
    bodyRegion: ['LUMBAR'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: true,
    movementPattern: 'CORE',
    tags: ['core', 'lateraal', 'stabiliteit'],
    instructions: ['Lig op je zij op onderarm', 'Hef heupen omhoog', 'Houd lichaam in rechte lijn'],
    muscleLoads: { Core: 4, Abductoren: 3, 'Schouders lateraal': 2 },
  },
  {
    name: 'Dead Bug',
    description: 'Core-stabilisatie met arm- en beenbewegingen.',
    category: 'STABILITY',
    bodyRegion: ['LUMBAR'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'CORE',
    tags: ['core', 'stabiliteit', 'revalidatie'],
    instructions: ['Lig op je rug, armen omhoog', 'Tegenovergestelde arm en been strekken', 'Houd onderrug plat op de grond'],
    muscleLoads: { Core: 4, 'Hip flexors': 2 },
  },
  {
    name: 'Bird Dog',
    description: 'Rugstabilisatie op handen en knieën.',
    category: 'STABILITY',
    bodyRegion: ['LUMBAR', 'BACK'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'CORE',
    tags: ['core', 'rug', 'stabiliteit'],
    instructions: ['Viervoetersstand', 'Strek tegenovergestelde arm en been', 'Houd romp stabiel', 'Wissel van kant'],
    muscleLoads: { Core: 3, Onderrug: 3, Glutes: 2, 'Schouders posterieur': 2 },
  },
  {
    name: 'Ab Wheel Rollout',
    description: 'Geavanceerde anti-extensie core-oefening.',
    category: 'STRENGTH',
    bodyRegion: ['LUMBAR'],
    difficulty: 'ADVANCED',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'CORE',
    tags: ['core', 'anti-extensie', 'gevorderd'],
    instructions: ['Kniel met handen op het wiel', 'Rol vooruit met gestrekte armen', 'Houd core aangespannen', 'Rol terug naar startpositie'],
    muscleLoads: { Core: 5, 'Schouders anterieur': 3, Lats: 2, 'Hip flexors': 2 },
  },
  {
    name: 'Pallof Press',
    description: 'Anti-rotatie core-oefening met kabel of band.',
    category: 'STABILITY',
    bodyRegion: ['LUMBAR'],
    difficulty: 'INTERMEDIATE',
    loadType: 'BAND',
    isUnilateral: false,
    movementPattern: 'ROTATION',
    tags: ['core', 'anti-rotatie', 'stabiliteit'],
    instructions: ['Sta zijwaarts van het ankerpunt', 'Houd band/kabel tegen borst', 'Druk armen recht vooruit', 'Weersta de rotatie'],
    muscleLoads: { Core: 5, Onderrug: 2 },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // MOBILITY
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'Hip 90/90 Stretch',
    description: 'Heupmobilisatie in 90/90 positie.',
    category: 'MOBILITY',
    bodyRegion: ['HIP'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: null,
    tags: ['heup', 'mobiliteit', 'stretch'],
    instructions: ['Zit met benen in 90/90 positie', 'Lean voorover over het voorste been', 'Wissel van kant'],
    muscleLoads: { 'Hip flexors': 3, Adductoren: 3, Glutes: 2 },
  },
  {
    name: 'World\'s Greatest Stretch',
    description: 'Dynamische full-body stretch voor opwarming.',
    category: 'MOBILITY',
    bodyRegion: ['HIP', 'BACK', 'SHOULDER'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: true,
    movementPattern: null,
    tags: ['opwarming', 'dynamisch', 'full-body'],
    instructions: ['Lunge positie', 'Draai romp naar het voorste been', 'Reik omhoog', 'Wissel van kant'],
    muscleLoads: { 'Hip flexors': 3, Adductoren: 2, Core: 2, Bovenrug: 2 },
  },
  {
    name: 'Cat-Cow Stretch',
    description: 'Wervelkolom mobiliteit in viervoetersstand.',
    category: 'MOBILITY',
    bodyRegion: ['BACK', 'LUMBAR', 'THORACIC'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: null,
    tags: ['rug', 'mobiliteit', 'opwarming'],
    instructions: ['Viervoetersstand', 'Hol de rug in (cow)', 'Bol de rug op (cat)', 'Beweeg langzaam door het bereik'],
    muscleLoads: { Core: 2, Onderrug: 2 },
  },
  {
    name: 'Thoracic Spine Rotation',
    description: 'Rotatiemobiliteit van de thoracale wervelkolom.',
    category: 'MOBILITY',
    bodyRegion: ['THORACIC'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: true,
    movementPattern: 'ROTATION',
    tags: ['thoracaal', 'rotatie', 'mobiliteit'],
    instructions: ['Zit of lig op je zij', 'Draai de bovenste arm open', 'Volg de hand met je ogen', 'Wissel van kant'],
    muscleLoads: { Bovenrug: 2, Core: 2 },
  },
  {
    name: 'Shoulder Dislocate (stok)',
    description: 'Schoudermobiliteit met een stok of band.',
    category: 'MOBILITY',
    bodyRegion: ['SHOULDER'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: null,
    tags: ['schouder', 'mobiliteit', 'stok'],
    instructions: ['Houd stok met brede grip', 'Beweeg in een boog over het hoofd naar achteren', 'Houd armen gestrekt'],
    muscleLoads: { 'Schouders anterieur': 2, 'Schouders posterieur': 2, Rotatorcuff: 3 },
  },
  {
    name: 'Ankle Dorsiflexion Mobilisation',
    description: 'Enkelmobiliteit tegen een muur.',
    category: 'MOBILITY',
    bodyRegion: ['ANKLE'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: true,
    movementPattern: null,
    tags: ['enkel', 'mobiliteit', 'dorsalflexie'],
    instructions: ['Voorste voet 10cm van de muur', 'Duw knie naar de muur voorbij de tenen', 'Houd hiel op de grond'],
    muscleLoads: { Calves: 3 },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // PLYOMETRICS
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'Box Jump',
    description: 'Explosieve sprong op een verhoging.',
    category: 'PLYOMETRICS',
    bodyRegion: ['KNEE', 'HIP', 'ANKLE'],
    difficulty: 'INTERMEDIATE',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'FULL_BODY',
    tags: ['explosief', 'springen', 'plyometrie'],
    instructions: ['Sta voor de box', 'Gebruik armen voor momentum', 'Spring omhoog en land zacht op de box'],
    muscleLoads: { Quadriceps: 4, Glutes: 4, Calves: 3, Core: 2, Hamstrings: 2 },
  },
  {
    name: 'Depth Jump',
    description: 'Val van een verhoging en spring direct omhoog.',
    category: 'PLYOMETRICS',
    bodyRegion: ['KNEE', 'HIP', 'ANKLE'],
    difficulty: 'ADVANCED',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'FULL_BODY',
    tags: ['plyometrie', 'reactief', 'gevorderd'],
    instructions: ['Stap van de box', 'Land en spring direct omhoog', 'Minimale grondcontacttijd'],
    muscleLoads: { Quadriceps: 5, Calves: 5, Glutes: 4, Hamstrings: 3 },
  },
  {
    name: 'Broad Jump',
    description: 'Horizontale sprong voor power.',
    category: 'PLYOMETRICS',
    bodyRegion: ['KNEE', 'HIP'],
    difficulty: 'INTERMEDIATE',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'FULL_BODY',
    tags: ['springen', 'horizontaal', 'power'],
    instructions: ['Sta met voeten op schouderbreedte', 'Zwaai armen naar achteren', 'Spring zo ver mogelijk naar voren', 'Land zacht'],
    muscleLoads: { Quadriceps: 4, Glutes: 5, Hamstrings: 3, Calves: 3 },
  },
  {
    name: 'Split Jump / Lunge Jump',
    description: 'Explosieve lunge met sprong en wissel.',
    category: 'PLYOMETRICS',
    bodyRegion: ['KNEE', 'HIP'],
    difficulty: 'INTERMEDIATE',
    loadType: 'BODYWEIGHT',
    isUnilateral: true,
    movementPattern: 'LUNGE',
    tags: ['plyometrie', 'lunge', 'explosief'],
    instructions: ['Start in lunge positie', 'Spring omhoog', 'Wissel benen in de lucht', 'Land zacht in lunge'],
    muscleLoads: { Quadriceps: 5, Glutes: 4, Hamstrings: 3, Calves: 3, 'Hip flexors': 2 },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // CARRIES & FUNCTIONAL
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'Farmer\'s Walk',
    description: 'Functioneel dragen van gewicht in beide handen.',
    category: 'STRENGTH',
    bodyRegion: ['FULL_BODY'],
    difficulty: 'BEGINNER',
    loadType: 'WEIGHTED',
    isUnilateral: false,
    movementPattern: 'CARRY',
    tags: ['carry', 'functioneel', 'grip'],
    instructions: ['Pak zwaar gewicht in elke hand', 'Loop met rechte houding', 'Schouders naar achteren', 'Strakke core'],
    muscleLoads: { Core: 4, Onderarmen: 5, 'Schouders lateraal': 3, Bovenrug: 3, Glutes: 2 },
  },
  {
    name: 'Suitcase Carry',
    description: 'Eenzijdig dragen voor anti-laterale flexie.',
    category: 'STRENGTH',
    bodyRegion: ['FULL_BODY'],
    difficulty: 'INTERMEDIATE',
    loadType: 'WEIGHTED',
    isUnilateral: true,
    movementPattern: 'CARRY',
    tags: ['carry', 'core', 'anti-lateraal'],
    instructions: ['Gewicht in één hand', 'Houd romp recht zonder zijwaarts leunen', 'Loop gecontroleerd'],
    muscleLoads: { Core: 5, Onderarmen: 4, Abductoren: 3, 'Schouders lateraal': 2 },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // ROTATOR CUFF & SHOULDER STABILITY
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'External Rotation (band)',
    description: 'Schouder externe rotatie met weerstandsband.',
    category: 'STABILITY',
    bodyRegion: ['SHOULDER'],
    difficulty: 'BEGINNER',
    loadType: 'BAND',
    isUnilateral: true,
    movementPattern: 'ROTATION',
    tags: ['schouder', 'rotatorcuff', 'preventie'],
    instructions: ['Elleboog 90 graden langs het lichaam', 'Draai onderarm naar buiten', 'Langzaam terug'],
    muscleLoads: { Rotatorcuff: 4, 'Schouders posterieur': 2 },
  },
  {
    name: 'Internal Rotation (band)',
    description: 'Schouder interne rotatie met weerstandsband.',
    category: 'STABILITY',
    bodyRegion: ['SHOULDER'],
    difficulty: 'BEGINNER',
    loadType: 'BAND',
    isUnilateral: true,
    movementPattern: 'ROTATION',
    tags: ['schouder', 'rotatorcuff', 'preventie'],
    instructions: ['Elleboog 90 graden langs het lichaam', 'Draai onderarm naar binnen', 'Langzaam terug'],
    muscleLoads: { Rotatorcuff: 4, 'Schouders anterieur': 2 },
  },
  {
    name: 'YTWL Raises',
    description: 'Scapulaire stabilisatie in vier posities.',
    category: 'STABILITY',
    bodyRegion: ['SHOULDER', 'BACK'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'ISOLATION_UPPER',
    tags: ['schouder', 'scapulair', 'stabiliteit'],
    instructions: ['Lig op je buik of leun voorover', 'Hef armen in Y-T-W-L posities', 'Knijp schouderbladen samen'],
    muscleLoads: { 'Schouders posterieur': 3, Bovenrug: 3, Rotatorcuff: 3 },
  },
]

export default STANDARD_EXERCISES
