/**
 * Standaard oefeningen-database voor Movement Based Therapy Amsterdam.
 * Evidence-based muscleLoads op basis van peer-reviewed EMG-studies (2000-2025).
 *
 * Conversie % MVIC → 1-5 schaal:
 *   0-20%  = 1 (lichte activatie)
 *   21-40% = 2 (matig-licht)
 *   41-60% = 3 (matig)
 *   61-80% = 4 (hoog)
 *   81%+   = 5 (zeer hoog)
 *
 * Zie emg_onderste_extremiteit.md en emg_bovenste_core.md voor bronvermelding.
 * Progressie/regressie wordt in seed.ts gekoppeld via exercise-progressions.ts.
 */

type SeedExercise = {
  name: string
  description: string
  category: 'STRENGTH' | 'MOBILITY' | 'PLYOMETRICS' | 'CARDIO' | 'STABILITY'
  bodyRegion: string[]
  difficulty: 'BEGINNER' | 'INTERMEDIATE' | 'ADVANCED'
  loadType: 'BODYWEIGHT' | 'WEIGHTED' | 'MACHINE' | 'BAND'
  isUnilateral: boolean
  movementPattern: string | null
  tags: string[]
  instructions: string[]
  muscleLoads: Record<string, number>
}

export const STANDARD_EXERCISES: SeedExercise[] = [
  // ═══════════════════════════════════════════════════════════════════════════
  // LOWER BODY — SQUAT PATTERNS
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'Wall Sit',
    description: 'Isometrische squat tegen de muur. Laag patellofemoraal risico — ideaal als beginners-regressie voor quadricepskracht bij knieklachten.',
    category: 'STRENGTH',
    bodyRegion: ['KNEE'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'SQUAT',
    tags: ['isometrisch', 'knie', 'beginner', 'revalidatie'],
    instructions: ['Leun met rug tegen muur', 'Zak tot 90 graden in de knieën', 'Houd de positie vast', 'Adem rustig door'],
    muscleLoads: { Quadriceps: 4, Glutes: 1, Core: 2 },
  },
  {
    name: 'Bodyweight Squat',
    description: 'Basis squat met lichaamsgewicht. Ideaal als technische fundering.',
    category: 'STRENGTH',
    bodyRegion: ['KNEE', 'HIP'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'SQUAT',
    tags: ['squat', 'beginner', 'lichaamsgewicht'],
    instructions: ['Voeten op schouderbreedte', 'Zak tot parallel', 'Houd borst omhoog', 'Druk door de hakken'],
    muscleLoads: { Quadriceps: 3, Glutes: 3, Calves: 1, Core: 2 },
  },
  {
    name: 'Goblet Squat',
    description: 'Squat met een dumbbell of kettlebell voor de borst. Instap-progressie richting beladen squats.',
    category: 'STRENGTH',
    bodyRegion: ['KNEE', 'HIP'],
    difficulty: 'BEGINNER',
    loadType: 'WEIGHTED',
    isUnilateral: false,
    movementPattern: 'SQUAT',
    tags: ['squat', 'benen', 'beginner'],
    instructions: ['Houd het gewicht tegen je borst', 'Voeten iets breder dan schouderbreedte', 'Zak met ellebogen tussen de knieën'],
    muscleLoads: { Quadriceps: 4, Glutes: 3, Core: 3 },
  },
  {
    name: 'Back Squat',
    description: 'Bilaterale squat met barbell op de bovenrug. High-bar: hogere VL/rectus femoris activatie. Low-bar: hogere gluteus/hamstring activatie [Murawa 2020, Yavuz 2015].',
    category: 'STRENGTH',
    bodyRegion: ['KNEE', 'HIP'],
    difficulty: 'INTERMEDIATE',
    loadType: 'WEIGHTED',
    isUnilateral: false,
    movementPattern: 'SQUAT',
    tags: ['squat', 'benen', 'compound'],
    instructions: ['Plaats de barbell op je bovenrug', 'Voeten op schouderbreedte', 'Zak tot minstens parallel', 'Druk door de hakken omhoog'],
    muscleLoads: { Quadriceps: 5, Glutes: 4, Hamstrings: 3, Core: 3, Calves: 2, Onderrug: 3 },
  },
  {
    name: 'Front Squat',
    description: 'Squat met de barbell op de voorste schouders. Hogere vastus medialis (+6-12% MVIC) en rectus femoris activatie dan back squat [Yavuz 2015].',
    category: 'STRENGTH',
    bodyRegion: ['KNEE', 'HIP'],
    difficulty: 'ADVANCED',
    loadType: 'WEIGHTED',
    isUnilateral: false,
    movementPattern: 'SQUAT',
    tags: ['squat', 'benen', 'quadriceps', 'vmo'],
    instructions: ['Barbell op voorste deltoids', 'Ellebogen hoog houden', 'Zak diep met rechte romp', 'Druk omhoog vanuit de hakken'],
    muscleLoads: { Quadriceps: 5, Glutes: 3, Core: 4, Calves: 2 },
  },
  {
    name: 'Bulgarian Split Squat',
    description: 'Unilaterale squat met achterste voet op een verhoging. Vastus medialis 85.4% MVIC — hoogste van alle bodyweight quadriceps-oefeningen [Mackey 2021].',
    category: 'STRENGTH',
    bodyRegion: ['KNEE', 'HIP'],
    difficulty: 'INTERMEDIATE',
    loadType: 'BODYWEIGHT',
    isUnilateral: true,
    movementPattern: 'LUNGE',
    tags: ['squat', 'unilateraal', 'benen', 'vmo'],
    instructions: ['Achterste voet op bank of verhoging', 'Zak recht naar beneden', 'Knie blijft boven de tenen', 'Lichte vooroverleun voor meer glute-activatie'],
    muscleLoads: { Quadriceps: 5, Glutes: 4, Hamstrings: 3, Core: 3, Calves: 2 },
  },
  {
    name: 'Pistol Squat',
    description: 'Single-leg squat zonder steun. Gluteus maximus 71% MVIC — hoogste activatie van therapeutische oefeningen [Distefano 2009].',
    category: 'STRENGTH',
    bodyRegion: ['KNEE', 'HIP', 'ANKLE'],
    difficulty: 'ADVANCED',
    loadType: 'BODYWEIGHT',
    isUnilateral: true,
    movementPattern: 'SQUAT',
    tags: ['squat', 'unilateraal', 'balans', 'gevorderd'],
    instructions: ['Sta op één been', 'Strek het andere been naar voren', 'Zak zo diep mogelijk', 'Sta op zonder hulp'],
    muscleLoads: { Quadriceps: 5, Glutes: 5, Hamstrings: 3, Core: 4, Calves: 3, 'Hip flexors': 3 },
  },
  {
    name: 'Leg Press',
    description: 'Compound beenpers op de machine. Significant LAGERE quadriceps + core activatie dan vrije squats [Escamilla 2001]. Minder functioneel maar veilig voor knie-revalidatie.',
    category: 'STRENGTH',
    bodyRegion: ['KNEE', 'HIP'],
    difficulty: 'BEGINNER',
    loadType: 'MACHINE',
    isUnilateral: false,
    movementPattern: 'SQUAT',
    tags: ['benen', 'compound', 'machine', 'revalidatie'],
    instructions: ['Plaats voeten op schouderbreedte', 'Laat het gewicht zakken tot 90 graden', 'Druk omhoog zonder knieën te locken'],
    muscleLoads: { Quadriceps: 4, Glutes: 3, Hamstrings: 2, Calves: 1 },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // LOWER BODY — LUNGE PATTERNS
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'Step Up',
    description: 'Op een verhoging stappen. Matige-hoge gluteus maximus activatie (~40-60% MVIC). Hogere trede = meer GMax + quadriceps [Reiman 2012].',
    category: 'STRENGTH',
    bodyRegion: ['KNEE', 'HIP'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: true,
    movementPattern: 'LUNGE',
    tags: ['step-up', 'functioneel', 'unilateraal'],
    instructions: ['Plaats één voet op de verhoging', 'Druk je omhoog vanuit die voet', 'Laat gecontroleerd weer zakken'],
    muscleLoads: { Quadriceps: 3, Glutes: 3, Hamstrings: 2, Calves: 2, Core: 2 },
  },
  {
    name: 'Lateral Step-Up',
    description: 'Zijwaartse step-up. Gluteus maximus 79-113% MVIC — een van de meest effectieve gluteusoefeningen [Ayotte 2007].',
    category: 'STRENGTH',
    bodyRegion: ['KNEE', 'HIP'],
    difficulty: 'INTERMEDIATE',
    loadType: 'BODYWEIGHT',
    isUnilateral: true,
    movementPattern: 'LUNGE',
    tags: ['step-up', 'lateraal', 'glutes', 'unilateraal'],
    instructions: ['Sta naast de verhoging', 'Plaats zijwaarts één voet erop', 'Druk omhoog, lift het andere been', 'Laat gecontroleerd zakken'],
    muscleLoads: { Quadriceps: 4, Glutes: 5, Abductoren: 4, Core: 3, Calves: 2 },
  },
  {
    name: 'Walking Lunge',
    description: 'Voorwaartse lunges in beweging. Hogere erector spinae en gluteus maximus activatie dan stationaire lunge [Farrokhi 2008]. Lunges activeren GMax MEER dan back squats [Muyor 2021].',
    category: 'STRENGTH',
    bodyRegion: ['KNEE', 'HIP'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: true,
    movementPattern: 'LUNGE',
    tags: ['lunge', 'benen', 'dynamisch'],
    instructions: ['Neem een grote stap naar voren', 'Zak tot 90 graden in beide knieën', 'Druk af en breng het achterste been naar voren'],
    muscleLoads: { Quadriceps: 4, Glutes: 4, Hamstrings: 3, 'Hip flexors': 2, Core: 3 },
  },
  {
    name: 'Reverse Lunge',
    description: 'Lunge naar achteren — minder kniestress, vergelijkbare gluteusactivatie [Marchetti 2024]. GMax en GMed hoger in stilstaande (voorste) been.',
    category: 'STRENGTH',
    bodyRegion: ['KNEE', 'HIP'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: true,
    movementPattern: 'LUNGE',
    tags: ['lunge', 'benen', 'knie-vriendelijk'],
    instructions: ['Stap naar achteren', 'Zak tot 90 graden', 'Druk vanuit de voorste voet terug'],
    muscleLoads: { Quadriceps: 3, Glutes: 4, Hamstrings: 3, Core: 3 },
  },
  {
    name: 'Lateral Lunge',
    description: 'Zijwaartse lunge voor adductoren en laterale stabiliteit.',
    category: 'STRENGTH',
    bodyRegion: ['KNEE', 'HIP'],
    difficulty: 'INTERMEDIATE',
    loadType: 'BODYWEIGHT',
    isUnilateral: true,
    movementPattern: 'LUNGE',
    tags: ['lunge', 'lateraal', 'adductoren'],
    instructions: ['Stap zijwaarts', 'Zak in het gebogen been', 'Houd het rechte been gestrekt', 'Druk terug naar start'],
    muscleLoads: { Quadriceps: 3, Glutes: 3, Adductoren: 4, Abductoren: 2, Core: 2 },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // LOWER BODY — HINGE PATTERNS
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'Kettlebell Swing',
    description: 'Explosieve hip hinge met kettlebell. Hoge power output, leert ballistic hip extension.',
    category: 'STRENGTH',
    bodyRegion: ['HIP', 'BACK'],
    difficulty: 'INTERMEDIATE',
    loadType: 'WEIGHTED',
    isUnilateral: false,
    movementPattern: 'HINGE',
    tags: ['kettlebell', 'explosief', 'hinge'],
    instructions: ['Hinge met kettlebell tussen benen', 'Explosief heupen strekken', 'Kettlebell swingt tot schouderhoogte', 'Controleer de terugzwaai'],
    muscleLoads: { Glutes: 5, Hamstrings: 4, Core: 4, 'Schouders anterieur': 2, Onderrug: 3 },
  },
  {
    name: 'Good Morning',
    description: 'Hip hinge met barbell op de rug. Erector spinae 216.6 mV — vergelijkbaar met RDL [De Ridder 2015]. Hoge axiale belasting: minder geschikt bij lumbale pathologie.',
    category: 'STRENGTH',
    bodyRegion: ['HIP', 'BACK'],
    difficulty: 'INTERMEDIATE',
    loadType: 'WEIGHTED',
    isUnilateral: false,
    movementPattern: 'HINGE',
    tags: ['hinge', 'hamstrings', 'onderrug'],
    instructions: ['Barbell op de bovenrug', 'Lichte buiging in knieën', 'Hinge voorover vanuit de heupen', 'Sta terug op met gestrekte heupen'],
    muscleLoads: { Hamstrings: 4, Glutes: 3, Onderrug: 5, Core: 3 },
  },
  {
    name: 'Romanian Deadlift (RDL)',
    description: 'Hip hinge met nadruk op hamstrings en glutes. Hogere/vergelijkbare biceps femoris activatie dan conventionele deadlift — vooral proximaal [Lee 2018].',
    category: 'STRENGTH',
    bodyRegion: ['HIP', 'BACK'],
    difficulty: 'INTERMEDIATE',
    loadType: 'WEIGHTED',
    isUnilateral: false,
    movementPattern: 'HINGE',
    tags: ['deadlift', 'hamstrings', 'hinge'],
    instructions: ['Houd barbell/dumbbells dicht bij lichaam', 'Hinge vanuit de heupen', 'Lichte buiging in de knieën', 'Voel rek in hamstrings, sta terug op'],
    muscleLoads: { Hamstrings: 5, Glutes: 4, Onderrug: 4, Bovenrug: 2, Core: 3 },
  },
  {
    name: 'Conventional Deadlift',
    description: 'Compound tilbeweging vanaf de grond. Hogere rectus femoris, gluteus maximus en vastus activatie dan RDL [Lee 2018]. Hogere biceps femoris dan sumo [Escamilla 2002].',
    category: 'STRENGTH',
    bodyRegion: ['HIP', 'BACK', 'KNEE'],
    difficulty: 'INTERMEDIATE',
    loadType: 'WEIGHTED',
    isUnilateral: false,
    movementPattern: 'HINGE',
    tags: ['deadlift', 'compound', 'kracht'],
    instructions: ['Voeten op heupbreedte', 'Grijp de stang net buiten de knieën', 'Borst omhoog, rug neutraal', 'Druk door benen en heupen tegelijk'],
    muscleLoads: { Hamstrings: 4, Glutes: 5, Onderrug: 4, Quadriceps: 3, Bovenrug: 3, Core: 3, Onderarmen: 3 },
  },
  {
    name: 'Single Leg Deadlift',
    description: 'Unilaterale hip hinge met balanselement. Goede anti-rotatie training.',
    category: 'STABILITY',
    bodyRegion: ['HIP', 'BACK', 'ANKLE'],
    difficulty: 'INTERMEDIATE',
    loadType: 'BODYWEIGHT',
    isUnilateral: true,
    movementPattern: 'HINGE',
    tags: ['deadlift', 'balans', 'unilateraal'],
    instructions: ['Sta op één been', 'Hinge naar voren', 'Achterste been strekt naar achteren', 'Houd rug neutraal'],
    muscleLoads: { Hamstrings: 4, Glutes: 4, Core: 4, Calves: 2, Abductoren: 3 },
  },
  {
    name: 'Prone Leg Curl',
    description: 'Liggende hamstring curl. Biceps femoris 50.3%, semitendinosus 44.3% MVIC [Krommes 2021]. Prone variant activeert BF MEER dan ST (omgekeerd aan Nordic curl) — klinisch relevant.',
    category: 'STRENGTH',
    bodyRegion: ['KNEE'],
    difficulty: 'BEGINNER',
    loadType: 'MACHINE',
    isUnilateral: false,
    movementPattern: 'ISOLATION_LOWER',
    tags: ['hamstrings', 'isolatie', 'machine', 'laterale hamstrings'],
    instructions: ['Lig op je buik in de machine', 'Buig de knieën volledig', 'Laat gecontroleerd terug', 'Focus op de samentrekking'],
    muscleLoads: { Hamstrings: 3, Calves: 1 },
  },
  {
    name: 'Leg Curl (machine)',
    description: 'Geïsoleerde hamstringtraining (zittend of liggend). Regressie van Prone Leg Curl.',
    category: 'STRENGTH',
    bodyRegion: ['KNEE'],
    difficulty: 'BEGINNER',
    loadType: 'MACHINE',
    isUnilateral: false,
    movementPattern: 'ISOLATION_LOWER',
    tags: ['hamstrings', 'isolatie', 'machine'],
    instructions: ['Zit of lig in de machine', 'Buig de knieën', 'Laat gecontroleerd terug'],
    muscleLoads: { Hamstrings: 3 },
  },
  {
    name: 'Nordic Hamstring Curl',
    description: 'Excentrische hamstringtraining. Biceps femoris 74.8%, semitendinosus 78.3% MVIC [Krommes 2021]. Bewezen effectief voor hamstring-blessurepreventie. Activeert MEDIALE hamstrings meer dan prone curl.',
    category: 'STRENGTH',
    bodyRegion: ['KNEE'],
    difficulty: 'ADVANCED',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'ISOLATION_LOWER',
    tags: ['hamstrings', 'excentrisch', 'preventie', 'mediale hamstrings'],
    instructions: ['Kniel met enkels gefixeerd', 'Laat je romp gecontroleerd naar voren zakken', 'Rem de beweging af met je hamstrings', 'Vang op met handen'],
    muscleLoads: { Hamstrings: 5, Glutes: 3, Core: 3 },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // LOWER BODY — HIP THRUST & GLUTES
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'Glute Bridge',
    description: 'Basis gluteoefening liggend op de grond. Matige GMax activatie (~25-35% MVIC). Hamstrings activeren vergelijkbaar of hoger dan glutes [Distefano 2009].',
    category: 'STRENGTH',
    bodyRegion: ['HIP'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'HIP_THRUST',
    tags: ['glutes', 'bridge', 'beginner', 'revalidatie'],
    instructions: ['Lig op je rug, knieën gebogen', 'Druk heupen omhoog', 'Knijp glutes bovenaan', 'Laat langzaam zakken'],
    muscleLoads: { Glutes: 2, Hamstrings: 3, Core: 2 },
  },
  {
    name: 'Single Leg Glute Bridge',
    description: 'Unilaterale glute bridge. Significant hogere GMax activatie (~50-60% MVIC) dan bilateraal. Extra core/abductor-eis door eenzijdige stabilisatie [Distefano 2009].',
    category: 'STRENGTH',
    bodyRegion: ['HIP'],
    difficulty: 'INTERMEDIATE',
    loadType: 'BODYWEIGHT',
    isUnilateral: true,
    movementPattern: 'HIP_THRUST',
    tags: ['glutes', 'unilateraal', 'bridge'],
    instructions: ['Lig op je rug, één been gestrekt', 'Druk heupen omhoog met het steunbeen', 'Houd heupen level'],
    muscleLoads: { Glutes: 3, Hamstrings: 3, Core: 3, Abductoren: 2 },
  },
  {
    name: 'Barbell Hip Thrust',
    description: 'Geïsoleerde glutestraining met barbell. Gluteus maximus 86.8% MVIC gemiddeld, piek 216% [Contreras 2015]. Significant hogere glute-activatie dan back squat.',
    category: 'STRENGTH',
    bodyRegion: ['HIP'],
    difficulty: 'INTERMEDIATE',
    loadType: 'WEIGHTED',
    isUnilateral: false,
    movementPattern: 'HIP_THRUST',
    tags: ['glutes', 'hip thrust', 'kracht'],
    instructions: ['Bovenrug op bank, schouderbladen', 'Barbell over de heupen (met pad)', 'Druk heupen omhoog tot volledige extensie', 'Knijp glutes bovenaan 1-2 seconden'],
    muscleLoads: { Glutes: 5, Hamstrings: 4, Core: 2 },
  },
  {
    name: 'Single Leg Hip Thrust',
    description: 'Unilaterale hip thrust — progressie van de bilaterale variant. Extra vereiste voor anti-rotatie core en heup-stabilisatie.',
    category: 'STRENGTH',
    bodyRegion: ['HIP'],
    difficulty: 'ADVANCED',
    loadType: 'BODYWEIGHT',
    isUnilateral: true,
    movementPattern: 'HIP_THRUST',
    tags: ['glutes', 'hip thrust', 'unilateraal'],
    instructions: ['Bovenrug op bank, één been gestrekt', 'Druk heupen omhoog met steunbeen', 'Houd heupen level (geen side-drop)', 'Knijp glute bovenaan'],
    muscleLoads: { Glutes: 5, Hamstrings: 4, Core: 4, Abductoren: 3 },
  },
  {
    name: 'Clamshell',
    description: 'Gluteus medius activatie met weerstandsband. ~77% GMed MVIC met band (progressie 4). Hoogste "gluteal targeting index" — minimale TFL-activatie [Selkowitz 2013].',
    category: 'STABILITY',
    bodyRegion: ['HIP'],
    difficulty: 'BEGINNER',
    loadType: 'BAND',
    isUnilateral: true,
    movementPattern: 'ISOLATION_LOWER',
    tags: ['glutes', 'activatie', 'band', 'revalidatie', 'gmed'],
    instructions: ['Lig op je zij, knieën gebogen (60° hoek = beste GMed)', 'Band om de knieën', 'Open de bovenste knie als een schelp', 'Houd voeten bij elkaar'],
    muscleLoads: { Glutes: 4, Abductoren: 4, Core: 2 },
  },
  {
    name: 'Side-Lying Hip Abduction',
    description: 'Gluteus medius 81% MVIC — beste oefening voor GMed activatie van 12 geteste [Distefano 2009, Boren 2011]. Ook significante TFL-activatie (klinische overweging).',
    category: 'STRENGTH',
    bodyRegion: ['HIP'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: true,
    movementPattern: 'ISOLATION_LOWER',
    tags: ['glutes', 'gmed', 'abductie', 'revalidatie'],
    instructions: ['Lig op je zij, onderste been licht gebogen', 'Hef bovenste been recht omhoog', 'Houd heup niet voorover kantelen', 'Laat gecontroleerd zakken'],
    muscleLoads: { Glutes: 5, Abductoren: 5, Core: 2 },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // LOWER BODY — CALVES
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'Calf Raise (staand)',
    description: 'Staande kuitoefening (gestrekte knie). Gastrocnemius ~50-52% MVIC [Hébert-Losier 2009]. Significant effectiever voor gastrocnemius hypertrofie dan zittend [Nunes 2023].',
    category: 'STRENGTH',
    bodyRegion: ['ANKLE'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'CALF_RAISE',
    tags: ['kuiten', 'gastrocnemius', 'beginner'],
    instructions: ['Sta op de rand van een trede', 'Druk omhoog op je tenen', 'Laat langzaam zakken onder de rand', 'Volledige ROM gebruiken'],
    muscleLoads: { Calves: 4 },
  },
  {
    name: 'Single Leg Calf Raise',
    description: 'Unilaterale calf raise. Hogere totale activatie dan bilateraal door dubbele belasting. Essentieel bij achillespeesrevalidatie.',
    category: 'STRENGTH',
    bodyRegion: ['ANKLE'],
    difficulty: 'INTERMEDIATE',
    loadType: 'BODYWEIGHT',
    isUnilateral: true,
    movementPattern: 'CALF_RAISE',
    tags: ['kuiten', 'unilateraal', 'achilles', 'revalidatie'],
    instructions: ['Sta op één voet op de rand van trede', 'Druk omhoog op tenen', 'Laat langzaam zakken onder de rand', 'Focus op gecontroleerde excentrische fase'],
    muscleLoads: { Calves: 5, Core: 2 },
  },
  {
    name: 'Seated Calf Raise',
    description: 'Zittende calf raise (gebogen knie). Isoleert soleus — knieflexie vermindert gastrocnemius bijdrage mechanisch [Hébert-Losier 2009]. Ideaal bij achillespeesrevalidatie.',
    category: 'STRENGTH',
    bodyRegion: ['ANKLE'],
    difficulty: 'BEGINNER',
    loadType: 'MACHINE',
    isUnilateral: false,
    movementPattern: 'CALF_RAISE',
    tags: ['kuiten', 'soleus', 'machine', 'achilles'],
    instructions: ['Zit in de machine, knieën in 90°', 'Voetbal op de platform', 'Druk omhoog met alleen de voet', 'Volledige ROM'],
    muscleLoads: { Calves: 4 },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // LOWER BODY — KNEE ISOLATION
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'Leg Extension (machine)',
    description: 'Geïsoleerde quadricepstraining (open chain). Hoogste rectus femoris activatie. VMO significant hoger bij volledige extensie (laatste 30°) — klinisch relevant voor PFPS [Escamilla 2001].',
    category: 'STRENGTH',
    bodyRegion: ['KNEE'],
    difficulty: 'BEGINNER',
    loadType: 'MACHINE',
    isUnilateral: false,
    movementPattern: 'ISOLATION_LOWER',
    tags: ['quadriceps', 'isolatie', 'machine', 'vmo'],
    instructions: ['Zit met rug tegen het kussen', 'Strek de benen volledig', 'Houd pauze bij volle extensie (VMO focus)', 'Laat gecontroleerd zakken'],
    muscleLoads: { Quadriceps: 5 },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // UPPER BODY — PUSH HORIZONTAL
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'Wall Push-Up',
    description: 'Basis push-up tegen de muur. Ideaal als beginnersregressie bij schouder-revalidatie.',
    category: 'STRENGTH',
    bodyRegion: ['SHOULDER'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'PUSH_HORIZONTAL',
    tags: ['borst', 'push-up', 'beginner', 'revalidatie'],
    instructions: ['Sta een armlengte van de muur', 'Handen op schouderhoogte', 'Leun naar de muur en druk terug', 'Houd lichaam recht'],
    muscleLoads: { Borst: 2, Triceps: 2, 'Schouders anterieur': 2, Core: 1 },
  },
  {
    name: 'Incline Push-Up',
    description: 'Push-up met handen op verhoging. Ook hoge serratus anterior activatie — essentieel voor scapulaire stabiliteit [Kowalski 2022].',
    category: 'STRENGTH',
    bodyRegion: ['SHOULDER'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'PUSH_HORIZONTAL',
    tags: ['borst', 'push-up', 'beginner', 'serratus'],
    instructions: ['Handen op bank of verhoging', 'Lichaam in rechte lijn', 'Zak tot borst bij de bank', 'Druk omhoog'],
    muscleLoads: { Borst: 3, Triceps: 3, 'Schouders anterieur': 2, Core: 2 },
  },
  {
    name: 'Push-Up',
    description: 'Klassieke push-up. Triceps 73-109% MVIC, pectoralis major 95-105%, serratus anterior 67-87% [Kowalski 2022].',
    category: 'STRENGTH',
    bodyRegion: ['SHOULDER'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'PUSH_HORIZONTAL',
    tags: ['borst', 'push-up', 'lichaamsgewicht', 'compound'],
    instructions: ['Handen op schouderbreedte', 'Lichaam in rechte lijn', 'Zak tot borst bijna de grond raakt', 'Druk omhoog'],
    muscleLoads: { Borst: 4, Triceps: 4, 'Schouders anterieur': 3, Core: 3 },
  },
  {
    name: 'Narrow-Grip Push-Up',
    description: 'Push-up met smalle handpositie. Significant hogere triceps brachii en pectoralis major activatie [Cogley 2005].',
    category: 'STRENGTH',
    bodyRegion: ['SHOULDER'],
    difficulty: 'INTERMEDIATE',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'PUSH_HORIZONTAL',
    tags: ['borst', 'triceps', 'push-up', 'smalle grip'],
    instructions: ['Handen smaller dan schouderbreedte', 'Ellebogen langs het lichaam', 'Zak gecontroleerd', 'Druk omhoog'],
    muscleLoads: { Borst: 4, Triceps: 5, 'Schouders anterieur': 3, Core: 3 },
  },
  {
    name: 'Dumbbell Chest Press',
    description: 'Horizontale druk met dumbbells. Grotere ROM dan barbell, meer stabilisatie-eis.',
    category: 'STRENGTH',
    bodyRegion: ['SHOULDER'],
    difficulty: 'INTERMEDIATE',
    loadType: 'WEIGHTED',
    isUnilateral: false,
    movementPattern: 'PUSH_HORIZONTAL',
    tags: ['borst', 'dumbbells', 'drukken'],
    instructions: ['Lig op bank met dumbbells', 'Druk omhoog tot armen gestrekt', 'Laat gecontroleerd zakken'],
    muscleLoads: { Borst: 4, Triceps: 3, 'Schouders anterieur': 3 },
  },
  {
    name: 'Bench Press',
    description: 'Barbell bench press (flat, 0°). Optimaal voor sternocostale (midden) pectoralis major activatie [Rodríguez-Ridao 2020].',
    category: 'STRENGTH',
    bodyRegion: ['SHOULDER'],
    difficulty: 'INTERMEDIATE',
    loadType: 'WEIGHTED',
    isUnilateral: false,
    movementPattern: 'PUSH_HORIZONTAL',
    tags: ['borst', 'bench press', 'compound'],
    instructions: ['Lig op de bank, voeten op de grond', 'Barbell op borsthoogte', 'Laat zakken tot de borst', 'Druk omhoog tot volledige extensie'],
    muscleLoads: { Borst: 5, Triceps: 4, 'Schouders anterieur': 3 },
  },
  {
    name: 'Incline Bench Press',
    description: 'Schuine bankdrukken (30-44°). Optimaal voor claviculaire (bovenste) pectoralis major [Rodríguez-Ridao 2020]. Vermijd >45°: verschuift belasting naar anterieure deltoid.',
    category: 'STRENGTH',
    bodyRegion: ['SHOULDER'],
    difficulty: 'INTERMEDIATE',
    loadType: 'WEIGHTED',
    isUnilateral: false,
    movementPattern: 'PUSH_HORIZONTAL',
    tags: ['borst', 'incline', 'bovenborst'],
    instructions: ['Bank op 30 graden', 'Druk gewicht omhoog', 'Laat zakken tot borsthoogte'],
    muscleLoads: { Borst: 4, 'Schouders anterieur': 4, Triceps: 3 },
  },
  {
    name: 'Parallel Bar Dips',
    description: 'Compound dips op parallelle stangen. Vergelijkbare tot hogere pectoralis major activatie als flat bench press [McKenzie 2022]. Let op bij anterieure schouderinstabiliteit.',
    category: 'STRENGTH',
    bodyRegion: ['SHOULDER', 'ELBOW'],
    difficulty: 'INTERMEDIATE',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'PUSH_HORIZONTAL',
    tags: ['borst', 'triceps', 'dips', 'compound'],
    instructions: ['Steun op parallelle stangen', 'Zak tot 90° in ellebogen (lichte vooroverleun = meer borst)', 'Druk omhoog tot volledige extensie'],
    muscleLoads: { Borst: 5, Triceps: 5, 'Schouders anterieur': 3 },
  },
  {
    name: 'Dumbbell Fly',
    description: 'Isolatie-oefening voor pectoralis. Lagere pec-activatie dan bench press, maar betere stretch in eindpositie (stretch-mediated hypertrofie) [Solstad 2020].',
    category: 'STRENGTH',
    bodyRegion: ['SHOULDER'],
    difficulty: 'INTERMEDIATE',
    loadType: 'WEIGHTED',
    isUnilateral: false,
    movementPattern: 'PUSH_HORIZONTAL',
    tags: ['borst', 'isolatie', 'stretch'],
    instructions: ['Lig op bank met dumbbells boven borst', 'Lichte buiging in ellebogen', 'Open armen zijwaarts tot borstlijn', 'Breng terug in boogbeweging'],
    muscleLoads: { Borst: 4, 'Schouders anterieur': 2 },
  },
  {
    name: 'Cable Fly',
    description: 'Cable-variant van fly. Constante spanning door volledige ROM — voorkeur boven dumbbell fly voor pec-isolatie.',
    category: 'STRENGTH',
    bodyRegion: ['SHOULDER'],
    difficulty: 'INTERMEDIATE',
    loadType: 'MACHINE',
    isUnilateral: false,
    movementPattern: 'PUSH_HORIZONTAL',
    tags: ['borst', 'isolatie', 'kabel'],
    instructions: ['Sta tussen kabels op hoge/middelste stand', 'Lichte buiging in ellebogen', 'Breng handen samen voor je borst', 'Controleerde terugweg'],
    muscleLoads: { Borst: 4, 'Schouders anterieur': 2 },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // UPPER BODY — PUSH VERTICAL
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'Dumbbell Shoulder Press',
    description: 'Schouderpers met dumbbells (zittend of staand). Staand: hogere deltoïdeus activatie door extra stabilisatie, maar lagere 1-RM [Saeterbakken 2013].',
    category: 'STRENGTH',
    bodyRegion: ['SHOULDER'],
    difficulty: 'INTERMEDIATE',
    loadType: 'WEIGHTED',
    isUnilateral: false,
    movementPattern: 'PUSH_VERTICAL',
    tags: ['schouders', 'dumbbells', 'press'],
    instructions: ['Dumbbells op schouderhoogte', 'Druk omhoog tot armen gestrekt', 'Laat gecontroleerd zakken'],
    muscleLoads: { 'Schouders anterieur': 4, 'Schouders lateraal': 3, Triceps: 3, Core: 2 },
  },
  {
    name: 'Overhead Press',
    description: 'Staande barbell overhead press. Anterieure deltoid 33% MVIC — significant hoger dan bench press (5%) en fly (3.4%) [Coratella 2020].',
    category: 'STRENGTH',
    bodyRegion: ['SHOULDER'],
    difficulty: 'INTERMEDIATE',
    loadType: 'WEIGHTED',
    isUnilateral: false,
    movementPattern: 'PUSH_VERTICAL',
    tags: ['schouders', 'press', 'compound'],
    instructions: ['Barbell op sleutelbeenhoogte', 'Druk recht omhoog', 'Lock uit boven het hoofd', 'Laat gecontroleerd zakken'],
    muscleLoads: { 'Schouders anterieur': 5, 'Schouders lateraal': 3, Triceps: 4, Core: 3 },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // UPPER BODY — SHOULDER ISOLATION
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'Lateral Raise',
    description: 'Dumbbell lateral raise. Deltoïdeus medialis ~30.3% MVIC — significant hoger dan bench press/fly [Coratella 2020]. Vergelijkbaar met cable variant [Kassiano 2025].',
    category: 'STRENGTH',
    bodyRegion: ['SHOULDER'],
    difficulty: 'BEGINNER',
    loadType: 'WEIGHTED',
    isUnilateral: false,
    movementPattern: 'ISOLATION_UPPER',
    tags: ['schouders', 'lateraal', 'isolatie'],
    instructions: ['Dumbbells langs het lichaam', 'Hef zijwaarts tot schouderhoogte', 'Laat gecontroleerd zakken'],
    muscleLoads: { 'Schouders lateraal': 4, 'Schouders anterieur': 2 },
  },
  {
    name: 'Cable Lateral Raise',
    description: 'Cable lateral raise. Geen significant verschil in hypertrofie vs. dumbbell variant na 8 weken [Kassiano 2025]. Voordeel: constante spanning door ROM.',
    category: 'STRENGTH',
    bodyRegion: ['SHOULDER'],
    difficulty: 'BEGINNER',
    loadType: 'MACHINE',
    isUnilateral: true,
    movementPattern: 'ISOLATION_UPPER',
    tags: ['schouders', 'lateraal', 'isolatie', 'kabel'],
    instructions: ['Kabel op laagste stand, aan tegenovergestelde kant', 'Grijp handvat met verste hand', 'Hef zijwaarts tot schouderhoogte', 'Laat gecontroleerd terug'],
    muscleLoads: { 'Schouders lateraal': 4, 'Schouders anterieur': 2 },
  },
  {
    name: 'Face Pull',
    description: 'Kabel- of bandoefening voor achterste schouders en midden/onder trapezius. Combineert scapulaire retractie met externe rotatie.',
    category: 'STRENGTH',
    bodyRegion: ['SHOULDER'],
    difficulty: 'BEGINNER',
    loadType: 'BAND',
    isUnilateral: false,
    movementPattern: 'PULL_HORIZONTAL',
    tags: ['schouders', 'posterieur', 'band', 'scapulair'],
    instructions: ['Trek kabel/band naar gezicht', 'Houd ellebogen hoog', 'Knijp schouderbladen samen', 'Laat gecontroleerd terug'],
    muscleLoads: { 'Schouders posterieur': 4, Rotatorcuff: 3, Bovenrug: 3 },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // UPPER BODY — ROTATOR CUFF
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'External Rotation (band)',
    description: 'Staande schouder externe rotatie met band. Functioneel bewegingspatroon maar lagere infraspinatus-activatie dan sidelying variant.',
    category: 'STABILITY',
    bodyRegion: ['SHOULDER'],
    difficulty: 'BEGINNER',
    loadType: 'BAND',
    isUnilateral: true,
    movementPattern: 'ROTATION',
    tags: ['schouder', 'rotatorcuff', 'preventie', 'functioneel'],
    instructions: ['Elleboog 90 graden langs het lichaam (handdoek in oksel)', 'Draai onderarm naar buiten', 'Langzaam terug'],
    muscleLoads: { Rotatorcuff: 3, 'Schouders posterieur': 2 },
  },
  {
    name: 'Sidelying External Rotation',
    description: 'Infraspinatus 62% MVIC, teres minor 67% — HOOGSTE activatie van 7 geteste ER-oefeningen [Reinold 2004]. Gouden standaard voor geïsoleerde infraspinatus-versterking.',
    category: 'STABILITY',
    bodyRegion: ['SHOULDER'],
    difficulty: 'BEGINNER',
    loadType: 'WEIGHTED',
    isUnilateral: true,
    movementPattern: 'ROTATION',
    tags: ['schouder', 'rotatorcuff', 'infraspinatus', 'preventie'],
    instructions: ['Lig op de zij met bovenste arm', 'Elleboog 90° tegen het lichaam (handdoek)', 'Roteer onderarm omhoog tegen weerstand', 'Langzaam terug'],
    muscleLoads: { Rotatorcuff: 4, 'Schouders posterieur': 2 },
  },
  {
    name: 'Internal Rotation (band)',
    description: 'Schouder interne rotatie met weerstandsband. Subscapularis activatie.',
    category: 'STABILITY',
    bodyRegion: ['SHOULDER'],
    difficulty: 'BEGINNER',
    loadType: 'BAND',
    isUnilateral: true,
    movementPattern: 'ROTATION',
    tags: ['schouder', 'rotatorcuff', 'preventie', 'subscapularis'],
    instructions: ['Elleboog 90 graden langs het lichaam', 'Draai onderarm naar binnen', 'Langzaam terug'],
    muscleLoads: { Rotatorcuff: 3, 'Schouders anterieur': 2 },
  },
  {
    name: 'Prone Y-Raise',
    description: 'Prone Y-raise met externe rotatie. Onder trapezius 85-97% MVIC — BESTE oefening voor onder trap activatie [Cools 2007]. Onmisbaar bij scapulaire dyskinesie.',
    category: 'STABILITY',
    bodyRegion: ['SHOULDER', 'BACK'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'ISOLATION_UPPER',
    tags: ['schouder', 'scapulair', 'onder trapezius', 'y-raise'],
    instructions: ['Lig buik op bank of grond', 'Armen in Y-positie (45° boven hoofd, duimen omhoog)', 'Hef armen op met schouderbladen', 'Knijp onder trap bovenaan'],
    muscleLoads: { 'Schouders posterieur': 3, Bovenrug: 5, Rotatorcuff: 3 },
  },
  {
    name: 'Prone T-Raise',
    description: 'Prone T-raise (horizontale abductie). Posterieure deltoid 88% MVIC, midden deltoid 87% bij 100° + volle ER [Cools 2007].',
    category: 'STABILITY',
    bodyRegion: ['SHOULDER', 'BACK'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'ISOLATION_UPPER',
    tags: ['schouder', 'scapulair', 'posterior delt', 't-raise'],
    instructions: ['Lig buik op bank', 'Armen zijwaarts (T-vorm, duimen omhoog)', 'Hef armen tot schouderhoogte', 'Knijp schouderbladen samen'],
    muscleLoads: { 'Schouders posterieur': 5, Bovenrug: 4, Rotatorcuff: 3 },
  },
  {
    name: 'Prone W-Raise',
    description: 'Prone W-raise — combineert externe rotatie met retractie. Goede algehele scapulaire activatie.',
    category: 'STABILITY',
    bodyRegion: ['SHOULDER', 'BACK'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'ISOLATION_UPPER',
    tags: ['schouder', 'scapulair', 'w-raise'],
    instructions: ['Lig buik op bank', 'Armen in W-vorm, ellebogen 90°', 'Hef ellebogen omhoog, handen roteren mee', 'Knijp schouderbladen samen'],
    muscleLoads: { 'Schouders posterieur': 3, Bovenrug: 3, Rotatorcuff: 3 },
  },
  {
    name: 'YTWL Raises',
    description: 'Combinatie van Y-T-W-L posities voor complete scapulaire stabilisatie. Samen tonen hoogste onder trapezius activatie.',
    category: 'STABILITY',
    bodyRegion: ['SHOULDER', 'BACK'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'ISOLATION_UPPER',
    tags: ['schouder', 'scapulair', 'stabiliteit', 'combo'],
    instructions: ['Lig op je buik of leun voorover', 'Hef armen in Y-T-W-L posities', 'Knijp schouderbladen samen', '5-10 reps per positie'],
    muscleLoads: { 'Schouders posterieur': 4, Bovenrug: 4, Rotatorcuff: 3 },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // UPPER BODY — PULL HORIZONTAL
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'Inverted Row',
    description: 'Horizontaal roeien met lichaamsgewicht. Goede regressie voor pull-ups en als basis-rugoefening.',
    category: 'STRENGTH',
    bodyRegion: ['BACK'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'PULL_HORIZONTAL',
    tags: ['rug', 'row', 'lichaamsgewicht', 'beginner'],
    instructions: ['Hang onder een stang', 'Trek borst naar de stang', 'Houd lichaam in rechte lijn', 'Knijp schouderbladen samen'],
    muscleLoads: { Bovenrug: 4, Lats: 3, Biceps: 3, Core: 3, 'Schouders posterieur': 2 },
  },
  {
    name: 'Chest-Supported Row',
    description: 'Row met borstondersteuning. Vergelijkbare lat-activatie als bent-over row, maar significant LAGERE erector spinae belasting [Fenwick 2009]. Ideaal bij lage rugklachten.',
    category: 'STRENGTH',
    bodyRegion: ['BACK'],
    difficulty: 'BEGINNER',
    loadType: 'WEIGHTED',
    isUnilateral: false,
    movementPattern: 'PULL_HORIZONTAL',
    tags: ['rug', 'row', 'rug-vriendelijk', 'revalidatie'],
    instructions: ['Lig buik op incline bank', 'Dumbbells hangen naar beneden', 'Trek ellebogen naar heupen', 'Knijp schouderbladen samen'],
    muscleLoads: { Bovenrug: 4, Lats: 4, Biceps: 3, 'Schouders posterieur': 3 },
  },
  {
    name: 'Cable Row (zittend)',
    description: 'Zittende kabelroeibeweging. Narrow-grip: meer lats. Wide-grip: meer midden/onder trapezius, erector spinae [Lehman 2004].',
    category: 'STRENGTH',
    bodyRegion: ['BACK'],
    difficulty: 'BEGINNER',
    loadType: 'MACHINE',
    isUnilateral: false,
    movementPattern: 'PULL_HORIZONTAL',
    tags: ['rug', 'row', 'kabel'],
    instructions: ['Zit met rechte rug', 'Trek handvat naar de buik', 'Schouderbladen samentrekken', 'Gecontroleerd terug'],
    muscleLoads: { Bovenrug: 4, Lats: 4, Biceps: 3, Onderarmen: 2 },
  },
  {
    name: 'Dumbbell Row (single arm)',
    description: 'Unilaterale roeibeweging. Vrije gewichten activeren meer stabilisatoren (erector spinae, multifidus). Hoge multifidus-activatie [Fenwick 2009].',
    category: 'STRENGTH',
    bodyRegion: ['BACK'],
    difficulty: 'BEGINNER',
    loadType: 'WEIGHTED',
    isUnilateral: true,
    movementPattern: 'PULL_HORIZONTAL',
    tags: ['rug', 'row', 'unilateraal'],
    instructions: ['Eén hand en knie op bank', 'Trek dumbbell naar de heup', 'Knijp schouderblad samen', 'Geen rotatie van romp'],
    muscleLoads: { Bovenrug: 4, Lats: 4, Biceps: 3, 'Schouders posterieur': 3, Core: 3 },
  },
  {
    name: 'Barbell Row',
    description: 'Bent-over barbell row. Hoge erector spinae belasting door voorovergebogen positie.',
    category: 'STRENGTH',
    bodyRegion: ['BACK'],
    difficulty: 'INTERMEDIATE',
    loadType: 'WEIGHTED',
    isUnilateral: false,
    movementPattern: 'PULL_HORIZONTAL',
    tags: ['rug', 'row', 'compound'],
    instructions: ['Hinge voorover met rechte rug', 'Trek barbell naar de buik', 'Knijp schouderbladen samen', 'Laat gecontroleerd zakken'],
    muscleLoads: { Bovenrug: 5, Lats: 4, Biceps: 3, 'Schouders posterieur': 2, Onderarmen: 3, Onderrug: 4 },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // UPPER BODY — PULL VERTICAL
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'Lat Pulldown',
    description: 'Machine-variant van de pull-up. Geen significant verschil in lat-rekrutering tussen grip-variaties [Lehman 2004]. Pull-up is superieur voor lat-activatie.',
    category: 'STRENGTH',
    bodyRegion: ['BACK'],
    difficulty: 'BEGINNER',
    loadType: 'MACHINE',
    isUnilateral: false,
    movementPattern: 'PULL_VERTICAL',
    tags: ['rug', 'lats', 'machine'],
    instructions: ['Brede overhandse grip', 'Trek stang naar de borst', 'Houd borst omhoog', 'Laat gecontroleerd terug'],
    muscleLoads: { Lats: 4, Biceps: 3, Bovenrug: 3, Onderarmen: 2 },
  },
  {
    name: 'Assisted Pull-Up',
    description: 'Pull-up met band- of machine-assistentie. Regressie voor opbouw naar volledige pull-up.',
    category: 'STRENGTH',
    bodyRegion: ['BACK', 'SHOULDER'],
    difficulty: 'BEGINNER',
    loadType: 'MACHINE',
    isUnilateral: false,
    movementPattern: 'PULL_VERTICAL',
    tags: ['rug', 'pull-up', 'regressie'],
    instructions: ['Overhandse grip op stang', 'Gebruik band/machine voor assistentie', 'Trek kin boven stang', 'Laat gecontroleerd zakken'],
    muscleLoads: { Lats: 4, Biceps: 3, Bovenrug: 3, Onderarmen: 2 },
  },
  {
    name: 'Chin-Up',
    description: 'Pull-up met supinated grip. Hogere biceps brachii en pectoralis major activatie dan pull-up [Youdas 2010].',
    category: 'STRENGTH',
    bodyRegion: ['BACK', 'SHOULDER'],
    difficulty: 'INTERMEDIATE',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'PULL_VERTICAL',
    tags: ['rug', 'chin-up', 'biceps'],
    instructions: ['Onderhandse grip op schouderbreedte', 'Trek kin boven de stang', 'Nadruk op biceps'],
    muscleLoads: { Lats: 4, Biceps: 5, Bovenrug: 3, Borst: 3, Onderarmen: 3 },
  },
  {
    name: 'Pull-Up',
    description: 'Pull-up met pronated grip. Latissimus dorsi 117-130% MVIC (supramaximaal). Significant hogere lat-activatie dan lat pulldown [Youdas 2010].',
    category: 'STRENGTH',
    bodyRegion: ['BACK', 'SHOULDER'],
    difficulty: 'INTERMEDIATE',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'PULL_VERTICAL',
    tags: ['rug', 'pull-up', 'compound'],
    instructions: ['Overhandse grip op schouderbreedte', 'Trek kin boven de stang', 'Laat gecontroleerd zakken tot volle hang'],
    muscleLoads: { Lats: 5, Biceps: 4, Bovenrug: 4, Core: 3, Onderarmen: 3 },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // UPPER BODY — BICEPS
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'Hammer Curl',
    description: 'Neutrale grip curl. Lagere biceps brachii activatie, maar hogere brachialis en brachioradialis [Marcolin 2018]. Waardevol voor totale armomvang.',
    category: 'STRENGTH',
    bodyRegion: ['ELBOW'],
    difficulty: 'BEGINNER',
    loadType: 'WEIGHTED',
    isUnilateral: false,
    movementPattern: 'ISOLATION_UPPER',
    tags: ['biceps', 'brachialis', 'neutraal', 'hammer'],
    instructions: ['Dumbbells neutrale grip (duimen vooruit)', 'Buig ellebogen', 'Houd bovenarm stil', 'Laat gecontroleerd zakken'],
    muscleLoads: { Biceps: 3, Onderarmen: 4 },
  },
  {
    name: 'Reverse Curl',
    description: 'Curl met pronated grip. Hoogste brachioradialis activatie [Marcolin 2018]. Minder biceps brachii.',
    category: 'STRENGTH',
    bodyRegion: ['ELBOW', 'WRIST'],
    difficulty: 'BEGINNER',
    loadType: 'WEIGHTED',
    isUnilateral: false,
    movementPattern: 'ISOLATION_UPPER',
    tags: ['biceps', 'brachioradialis', 'reverse', 'onderarmen'],
    instructions: ['Pronated grip (handpalmen naar beneden)', 'Buig ellebogen', 'Focus op onderarm-activatie', 'Laat gecontroleerd zakken'],
    muscleLoads: { Biceps: 2, Onderarmen: 5 },
  },
  {
    name: 'Bicep Curl',
    description: 'Supinated grip curl met dumbbells. Traditionele biceps brachii oefening.',
    category: 'STRENGTH',
    bodyRegion: ['ELBOW'],
    difficulty: 'BEGINNER',
    loadType: 'WEIGHTED',
    isUnilateral: false,
    movementPattern: 'ISOLATION_UPPER',
    tags: ['biceps', 'isolatie', 'armen'],
    instructions: ['Dumbbells langs het lichaam, supinated grip', 'Buig de ellebogen omhoog', 'Houd bovenarm stil', 'Laat gecontroleerd zakken'],
    muscleLoads: { Biceps: 4, Onderarmen: 2 },
  },
  {
    name: 'EZ-Bar Curl',
    description: 'EZ-bar curl. Significant hogere biceps brachii EN brachioradialis activatie dan dumbbell curl. Ergonomischer (minder polsbelasting) [Marcolin 2018].',
    category: 'STRENGTH',
    bodyRegion: ['ELBOW'],
    difficulty: 'BEGINNER',
    loadType: 'WEIGHTED',
    isUnilateral: false,
    movementPattern: 'ISOLATION_UPPER',
    tags: ['biceps', 'ez-bar', 'pols-vriendelijk'],
    instructions: ['EZ-bar met supinated grip (grepen)', 'Buig ellebogen', 'Houd bovenarmen stil', 'Laat gecontroleerd zakken'],
    muscleLoads: { Biceps: 5, Onderarmen: 3 },
  },
  {
    name: 'Incline Dumbbell Curl',
    description: 'Curl op incline bank (~45°). Biceps brachii over grotere ROM met meer stretch — stretch-mediated hypertrofie [Oliveira 2009].',
    category: 'STRENGTH',
    bodyRegion: ['ELBOW'],
    difficulty: 'INTERMEDIATE',
    loadType: 'WEIGHTED',
    isUnilateral: false,
    movementPattern: 'ISOLATION_UPPER',
    tags: ['biceps', 'incline', 'stretch'],
    instructions: ['Zit op 45° incline bank', 'Dumbbells hangen recht naar beneden', 'Buig ellebogen zonder bovenarm te bewegen', 'Focus op de stretch in eindpositie'],
    muscleLoads: { Biceps: 5, Onderarmen: 2 },
  },
  {
    name: 'Preacher Curl',
    description: 'Curl op preacher bench. Hoge biceps activatie maar over een kort deel van ROM [Oliveira 2009].',
    category: 'STRENGTH',
    bodyRegion: ['ELBOW'],
    difficulty: 'INTERMEDIATE',
    loadType: 'WEIGHTED',
    isUnilateral: false,
    movementPattern: 'ISOLATION_UPPER',
    tags: ['biceps', 'preacher', 'isolatie'],
    instructions: ['Bovenarmen op preacher pad', 'Buig ellebogen tegen weerstand', 'Laat niet helemaal zakken (span behouden)', 'Knijp bovenaan'],
    muscleLoads: { Biceps: 5, Onderarmen: 3 },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // UPPER BODY — TRICEPS
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'Tricep Pushdown (kabel)',
    description: 'Rope pushdown. ~74% spieractivatie — hoogste voor laterale en mediale kop van de triceps [Boehler 2011].',
    category: 'STRENGTH',
    bodyRegion: ['ELBOW'],
    difficulty: 'BEGINNER',
    loadType: 'MACHINE',
    isUnilateral: false,
    movementPattern: 'ISOLATION_UPPER',
    tags: ['triceps', 'isolatie', 'kabel', 'laterale kop'],
    instructions: ['Sta voor de kabelmachine', 'Druk het touw/stang naar beneden', 'Houd ellebogen langs het lichaam', 'Volledige extensie'],
    muscleLoads: { Triceps: 4 },
  },
  {
    name: 'Skull Crusher',
    description: 'Lying triceps extension. ~62% spieractivatie [Boehler 2011].',
    category: 'STRENGTH',
    bodyRegion: ['ELBOW'],
    difficulty: 'INTERMEDIATE',
    loadType: 'WEIGHTED',
    isUnilateral: false,
    movementPattern: 'ISOLATION_UPPER',
    tags: ['triceps', 'skull crusher', 'isolatie'],
    instructions: ['Lig op bank met EZ-bar of dumbbells boven borst', 'Laat zakken richting voorhoofd', 'Houd bovenarmen stil', 'Strek ellebogen'],
    muscleLoads: { Triceps: 4, Borst: 1 },
  },
  {
    name: 'Tricep Dip',
    description: 'Dip op bank/stoel. Regressie voor parallel bar dips.',
    category: 'STRENGTH',
    bodyRegion: ['ELBOW', 'SHOULDER'],
    difficulty: 'INTERMEDIATE',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'PUSH_HORIZONTAL',
    tags: ['triceps', 'dip', 'bank'],
    instructions: ['Handen op bank achter je', 'Benen gestrekt of gebogen', 'Zak door ellebogen', 'Druk omhoog'],
    muscleLoads: { Triceps: 4, Borst: 2, 'Schouders anterieur': 3 },
  },
  {
    name: 'Overhead Triceps Extension',
    description: 'Overhead extension. Beste activatie van de LANGE KOP — 40% MEER tricepsgroei vs. pushdowns [Maeo 2023]. Stretch-mediated hypertrofie.',
    category: 'STRENGTH',
    bodyRegion: ['ELBOW'],
    difficulty: 'INTERMEDIATE',
    loadType: 'WEIGHTED',
    isUnilateral: false,
    movementPattern: 'ISOLATION_UPPER',
    tags: ['triceps', 'overhead', 'lange kop', 'stretch'],
    instructions: ['Dumbbell of EZ-bar boven hoofd', 'Laat zakken achter hoofd (ellebogen gebogen)', 'Strek armen omhoog', 'Focus op stretch in eindpositie'],
    muscleLoads: { Triceps: 5, 'Schouders anterieur': 2, Core: 2 },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // CORE — ANTERIOR
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'Crunch',
    description: 'Basis crunch. Matige rectus abdominis activatie — LAGER dan ab wheel en hanging varianten [Escamilla 2006].',
    category: 'STRENGTH',
    bodyRegion: ['LUMBAR'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'CORE',
    tags: ['core', 'crunch', 'beginner'],
    instructions: ['Lig op rug, knieën gebogen', 'Handen bij slapen', 'Rol schouders op (geen sit-up)', 'Laat gecontroleerd zakken'],
    muscleLoads: { Core: 3, 'Hip flexors': 1 },
  },
  {
    name: 'Sit-Up',
    description: 'Klassieke sit-up. Hogere activatie van bovenste/onderste rectus abdominis en externe obliquus dan straight leg raise [Escamilla 2006].',
    category: 'STRENGTH',
    bodyRegion: ['LUMBAR'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'CORE',
    tags: ['core', 'sit-up', 'beginner'],
    instructions: ['Lig op rug, voeten gefixeerd', 'Kom omhoog tot rechtop', 'Laat gecontroleerd zakken', 'Geen ruk in beweging'],
    muscleLoads: { Core: 3, 'Hip flexors': 3 },
  },
  {
    name: 'Dead Bug',
    description: 'Core-stabilisatie met extremiteitsbewegingen. Significante transversus abdominis activatie (#4 hollowing ranking). Minimale erector spinae — veilig bij lage rugpijn [Yoon 2024].',
    category: 'STABILITY',
    bodyRegion: ['LUMBAR'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'CORE',
    tags: ['core', 'stabiliteit', 'revalidatie', 'tva'],
    instructions: ['Lig op je rug, armen omhoog, knieën 90°', 'Strek tegenovergestelde arm en been', 'Houd onderrug plat op de grond', 'Wissel'],
    muscleLoads: { Core: 4, 'Hip flexors': 2 },
  },
  {
    name: 'Hollow Body Hold',
    description: 'Anti-extensie isometrische core. Rectus abdominis ~55-65% MVIC. Veilig voor patiënten met lumbale discuspathologie (geen herhaalde flexie) [McGill 2016].',
    category: 'STRENGTH',
    bodyRegion: ['LUMBAR'],
    difficulty: 'INTERMEDIATE',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'CORE',
    tags: ['core', 'isometrisch', 'anti-extensie'],
    instructions: ['Lig op rug, armen/benen gestrekt', 'Druk onderrug in de grond', 'Hef schouders en benen iets op (boot-vorm)', 'Houd positie vast'],
    muscleLoads: { Core: 4, 'Hip flexors': 3 },
  },
  {
    name: 'Cable Crunch',
    description: 'Cable crunch met progressieve belasting. Verhoogde rectus abdominis, externe obliquus en rectus femoris activatie vs. bodyweight [Moraes 2009].',
    category: 'STRENGTH',
    bodyRegion: ['LUMBAR'],
    difficulty: 'INTERMEDIATE',
    loadType: 'MACHINE',
    isUnilateral: false,
    movementPattern: 'CORE',
    tags: ['core', 'kabel', 'progressieve overload'],
    instructions: ['Kniel voor kabelmachine', 'Grijp touw naast hoofd', 'Rol schouders richting heupen (niet hoek in heupen)', 'Laat gecontroleerd terug'],
    muscleLoads: { Core: 5, 'Hip flexors': 2 },
  },
  {
    name: 'Reverse Crunch',
    description: 'Reverse crunch op incline (30°). Top-oefening voor ONDERSTE rectus abdominis regio [Escamilla 2006].',
    category: 'STRENGTH',
    bodyRegion: ['LUMBAR'],
    difficulty: 'INTERMEDIATE',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'CORE',
    tags: ['core', 'onderste abs', 'reverse'],
    instructions: ['Lig op rug of op incline bank', 'Knieën gebogen', 'Rol heupen/knieën richting borst', 'Laat gecontroleerd zakken'],
    muscleLoads: { Core: 4, 'Hip flexors': 3 },
  },
  {
    name: 'Hanging Knee Raise',
    description: 'Hanging knee-up. Top-3 rectus abdominis en interne obliquus activatie [Escamilla 2006]. Hoge grip-eis — gebruik straps indien nodig.',
    category: 'STRENGTH',
    bodyRegion: ['LUMBAR'],
    difficulty: 'INTERMEDIATE',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'CORE',
    tags: ['core', 'hanging', 'rectus abdominis'],
    instructions: ['Hang aan een pull-up stang', 'Hef knieën richting borst', 'Controleer omlaag', 'Geen schommel in beweging'],
    muscleLoads: { Core: 5, 'Hip flexors': 4, Onderarmen: 3 },
  },
  {
    name: 'Hanging Leg Raise',
    description: 'Hanging leg raise met gestrekte benen. Progressie van hanging knee raise — hogere overall activatie.',
    category: 'STRENGTH',
    bodyRegion: ['LUMBAR'],
    difficulty: 'ADVANCED',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'CORE',
    tags: ['core', 'hanging', 'gevorderd'],
    instructions: ['Hang aan een pull-up stang', 'Hef gestrekte benen tot 90°', 'Laat gecontroleerd zakken', 'Geen schommel'],
    muscleLoads: { Core: 5, 'Hip flexors': 5, Onderarmen: 3 },
  },
  {
    name: 'Ab Wheel Rollout',
    description: 'Anti-extensie ab wheel. Bovenste rectus abdominis 63% MVIC, externe/interne obliquus 46% — significant hoger dan meeste abdominale oefeningen [Escamilla 2006].',
    category: 'STRENGTH',
    bodyRegion: ['LUMBAR'],
    difficulty: 'ADVANCED',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'CORE',
    tags: ['core', 'anti-extensie', 'gevorderd'],
    instructions: ['Kniel met handen op het wiel', 'Rol vooruit met gestrekte armen', 'Houd core aangespannen (geen doorhangen)', 'Rol terug naar startpositie'],
    muscleLoads: { Core: 5, 'Schouders anterieur': 3, Lats: 3 },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // CORE — POSTERIOR / LATERAL / STABILIZATION
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'Bird Dog',
    description: 'McGill "Big Three". Transversus abdominis #1 in hollowing-oefeningen (grootste toename in spierdikte) [Yoon 2024]. Traint stabilisatie tegen rotatie + extensie.',
    category: 'STABILITY',
    bodyRegion: ['LUMBAR', 'BACK'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'CORE',
    tags: ['core', 'rug', 'stabiliteit', 'mcgill', 'tva'],
    instructions: ['Viervoetersstand', 'Strek tegenovergestelde arm en been', 'Houd romp stabiel (geen rotatie)', 'Wissel van kant'],
    muscleLoads: { Core: 5, Onderrug: 3, Glutes: 3, 'Schouders posterieur': 2 },
  },
  {
    name: 'Side Plank',
    description: 'McGill "Big Three" laterale stabilisatie. Externe obliquus hoog, Quadratus lumborum hoog (weinig oefeningen trainen QL effectief), Gluteus medius 3 [McGill 2016].',
    category: 'STABILITY',
    bodyRegion: ['LUMBAR'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: true,
    movementPattern: 'CORE',
    tags: ['core', 'lateraal', 'stabiliteit', 'mcgill', 'quadratus lumborum'],
    instructions: ['Lig op je zij op onderarm', 'Hef heupen omhoog (rechte lijn)', 'Houd positie vast', 'Wissel kant'],
    muscleLoads: { Core: 4, Abductoren: 4, Glutes: 3, 'Schouders lateraal': 2 },
  },
  {
    name: 'Plank',
    description: 'Anterior plank. Matige rectus abdominis, hoge transversus abdominis (vooral met hollowing: 22.7-106% rust vs. bracing 18.7-87.1%) [McGill 2016].',
    category: 'STABILITY',
    bodyRegion: ['LUMBAR'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'CORE',
    tags: ['core', 'plank', 'isometrisch'],
    instructions: ['Onderarmen en tenen op de grond', 'Lichaam in rechte lijn', 'Houd de positie vast', 'Niet laten doorzakken'],
    muscleLoads: { Core: 4, 'Schouders anterieur': 2, Onderrug: 2, Glutes: 2 },
  },
  {
    name: 'Pallof Press',
    description: 'Anti-rotation gouden standaard. Hoge transversus abdominis en obliquus activatie. Minimale compressieve spinale belasting — ideaal bij rugpijn-revalidatie.',
    category: 'STABILITY',
    bodyRegion: ['LUMBAR'],
    difficulty: 'INTERMEDIATE',
    loadType: 'BAND',
    isUnilateral: false,
    movementPattern: 'ROTATION',
    tags: ['core', 'anti-rotatie', 'stabiliteit', 'revalidatie'],
    instructions: ['Sta zijwaarts van het ankerpunt', 'Houd band/kabel tegen borst', 'Druk armen recht vooruit', 'Weersta de rotatie'],
    muscleLoads: { Core: 5, Onderrug: 2 },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // BACK EXTENSION
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'Back Extension (Roman Chair)',
    description: '45° hyper-extension. Erector spinae 76-79% MVIC [De Ridder 2015]. Hogere gluteus maximus (94-140% verschil) dan seated machine.',
    category: 'STRENGTH',
    bodyRegion: ['BACK', 'LUMBAR'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'HINGE',
    tags: ['rug', 'erector spinae', 'hyper'],
    instructions: ['Plaats heupen op pad, voeten gefixeerd', 'Laat bovenlichaam zakken', 'Strek tot neutrale rugpositie', 'Geen overstrekking'],
    muscleLoads: { Onderrug: 4, Glutes: 4, Hamstrings: 3 },
  },
  {
    name: 'Reverse Hyper',
    description: 'Reverse hyper. Biedt spinale decompressie (tractie) in excentrische fase. Gluteus maximus primair + hamstrings [De Ridder 2015].',
    category: 'STRENGTH',
    bodyRegion: ['BACK', 'HIP'],
    difficulty: 'INTERMEDIATE',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'HINGE',
    tags: ['rug', 'glutes', 'decompressie', 'hamstrings'],
    instructions: ['Lig buik op reverse hyper', 'Hef gestrekte benen omhoog', 'Knijp glutes bovenaan', 'Laat gecontroleerd zakken'],
    muscleLoads: { Glutes: 4, Hamstrings: 4, Onderrug: 4 },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // MOBILITY
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'Hip 90/90 Stretch',
    description: 'Heupmobilisatie in 90/90 positie voor interne en externe rotatie.',
    category: 'MOBILITY',
    bodyRegion: ['HIP'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: null,
    tags: ['heup', 'mobiliteit', 'stretch'],
    instructions: ['Zit met benen in 90/90 positie', 'Leun voorover over het voorste been', 'Wissel van kant'],
    muscleLoads: { 'Hip flexors': 3, Adductoren: 3, Glutes: 2 },
  },
  {
    name: 'World\'s Greatest Stretch',
    description: 'Dynamische full-body stretch voor opwarming.',
    category: 'MOBILITY',
    bodyRegion: ['HIP', 'BACK', 'SHOULDER'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: true,
    movementPattern: null,
    tags: ['opwarming', 'dynamisch', 'full-body'],
    instructions: ['Lunge positie', 'Draai romp naar het voorste been', 'Reik omhoog', 'Wissel van kant'],
    muscleLoads: { 'Hip flexors': 3, Adductoren: 2, Core: 2, Bovenrug: 2 },
  },
  {
    name: 'Cat-Cow Stretch',
    description: 'Wervelkolom mobiliteit in viervoetersstand.',
    category: 'MOBILITY',
    bodyRegion: ['BACK', 'LUMBAR', 'THORACIC'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: null,
    tags: ['rug', 'mobiliteit', 'opwarming'],
    instructions: ['Viervoetersstand', 'Hol de rug in (cow)', 'Bol de rug op (cat)', 'Beweeg langzaam door het bereik'],
    muscleLoads: { Core: 2, Onderrug: 2 },
  },
  {
    name: 'Thoracic Spine Rotation',
    description: 'Rotatiemobiliteit van de thoracale wervelkolom.',
    category: 'MOBILITY',
    bodyRegion: ['THORACIC'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: true,
    movementPattern: 'ROTATION',
    tags: ['thoracaal', 'rotatie', 'mobiliteit'],
    instructions: ['Zit of lig op je zij', 'Draai de bovenste arm open', 'Volg de hand met je ogen', 'Wissel van kant'],
    muscleLoads: { Bovenrug: 2, Core: 2 },
  },
  {
    name: 'Shoulder Dislocate (stok)',
    description: 'Schoudermobiliteit met een stok of band.',
    category: 'MOBILITY',
    bodyRegion: ['SHOULDER'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: null,
    tags: ['schouder', 'mobiliteit', 'stok'],
    instructions: ['Houd stok met brede grip', 'Beweeg in een boog over het hoofd naar achteren', 'Houd armen gestrekt'],
    muscleLoads: { 'Schouders anterieur': 2, 'Schouders posterieur': 2, Rotatorcuff: 3 },
  },
  {
    name: 'Ankle Dorsiflexion Mobilisation',
    description: 'Enkelmobiliteit tegen een muur.',
    category: 'MOBILITY',
    bodyRegion: ['ANKLE'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: true,
    movementPattern: null,
    tags: ['enkel', 'mobiliteit', 'dorsalflexie'],
    instructions: ['Voorste voet 10cm van de muur', 'Duw knie naar de muur voorbij de tenen', 'Houd hiel op de grond'],
    muscleLoads: { Calves: 3 },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // PLYOMETRICS
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'Broad Jump',
    description: 'Horizontale sprong voor power.',
    category: 'PLYOMETRICS',
    bodyRegion: ['KNEE', 'HIP'],
    difficulty: 'INTERMEDIATE',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'FULL_BODY',
    tags: ['springen', 'horizontaal', 'power'],
    instructions: ['Sta met voeten op schouderbreedte', 'Zwaai armen naar achteren', 'Spring zo ver mogelijk naar voren', 'Land zacht'],
    muscleLoads: { Quadriceps: 4, Glutes: 4, Hamstrings: 3, Calves: 3 },
  },
  {
    name: 'Countermovement Jump',
    description: 'Verticale sprong met tegenbeweging. Hoge activatie VL, VM, GAS. Na 6 weken plyo: +13.25% VL, +9.60% VM, +13.93% GAS [Ebben 2011].',
    category: 'PLYOMETRICS',
    bodyRegion: ['KNEE', 'HIP', 'ANKLE'],
    difficulty: 'INTERMEDIATE',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'FULL_BODY',
    tags: ['springen', 'verticaal', 'cmj', 'power'],
    instructions: ['Sta met voeten op schouderbreedte', 'Snelle kwart-squat naar beneden', 'Spring zo hoog mogelijk', 'Land zacht'],
    muscleLoads: { Quadriceps: 4, Glutes: 4, Hamstrings: 3, Calves: 4 },
  },
  {
    name: 'Box Jump',
    description: 'Explosieve sprong op een verhoging. Mid-range plyometrische belasting.',
    category: 'PLYOMETRICS',
    bodyRegion: ['KNEE', 'HIP', 'ANKLE'],
    difficulty: 'INTERMEDIATE',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'FULL_BODY',
    tags: ['explosief', 'springen', 'plyometrie'],
    instructions: ['Sta voor de box', 'Gebruik armen voor momentum', 'Spring omhoog en land zacht op de box', 'Stap terug naar beneden (niet springen)'],
    muscleLoads: { Quadriceps: 4, Glutes: 4, Calves: 3, Core: 3, Hamstrings: 3 },
  },
  {
    name: 'Depth Jump',
    description: 'Val van verhoging met direct-opnieuw-springen. Hoge reactieve krachten, korte grondcontacttijd.',
    category: 'PLYOMETRICS',
    bodyRegion: ['KNEE', 'HIP', 'ANKLE'],
    difficulty: 'ADVANCED',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'FULL_BODY',
    tags: ['plyometrie', 'reactief', 'gevorderd'],
    instructions: ['Stap van de box', 'Land en spring DIRECT omhoog', 'Minimale grondcontacttijd', 'Beheers de landing'],
    muscleLoads: { Quadriceps: 5, Calves: 5, Glutes: 4, Hamstrings: 4, Core: 3 },
  },
  {
    name: 'Hurdle Jump',
    description: 'HOOGSTE gluteus maximus activatie van alle sprongoefeningen [Ebben 2011]. Beste plyo voor GMax power-ontwikkeling.',
    category: 'PLYOMETRICS',
    bodyRegion: ['KNEE', 'HIP', 'ANKLE'],
    difficulty: 'ADVANCED',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'FULL_BODY',
    tags: ['plyometrie', 'hurdle', 'glutes', 'gevorderd'],
    instructions: ['Plaats meerdere hurdles in rij', 'Spring met beide benen over hurdle', 'Minimale grondcontacttijd tussen hurdles', 'Land zacht en reactief'],
    muscleLoads: { Glutes: 5, Quadriceps: 4, Hamstrings: 4, Calves: 4, Core: 3 },
  },
  {
    name: 'Split Jump / Lunge Jump',
    description: 'Explosieve lunge met sprong en wissel.',
    category: 'PLYOMETRICS',
    bodyRegion: ['KNEE', 'HIP'],
    difficulty: 'INTERMEDIATE',
    loadType: 'BODYWEIGHT',
    isUnilateral: true,
    movementPattern: 'LUNGE',
    tags: ['plyometrie', 'lunge', 'explosief'],
    instructions: ['Start in lunge positie', 'Spring omhoog', 'Wissel benen in de lucht', 'Land zacht in lunge'],
    muscleLoads: { Quadriceps: 4, Glutes: 4, Hamstrings: 3, Calves: 3, 'Hip flexors': 3 },
  },
  {
    name: 'Crossover Jump',
    description: 'HOOGSTE gluteus medius activatie van sprongoefeningen [Ebben 2011]. Zijwaartse plyo voor laterale stabilisatie.',
    category: 'PLYOMETRICS',
    bodyRegion: ['KNEE', 'HIP'],
    difficulty: 'ADVANCED',
    loadType: 'BODYWEIGHT',
    isUnilateral: true,
    movementPattern: 'FULL_BODY',
    tags: ['plyometrie', 'lateraal', 'gmed', 'gevorderd'],
    instructions: ['Sta op één been', 'Spring zijwaarts en kruis over', 'Land op tegenovergesteld been', 'Beheers landing en spring terug'],
    muscleLoads: { Glutes: 5, Abductoren: 5, Quadriceps: 3, Calves: 3, Core: 3 },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // CARRIES
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'Farmer\'s Walk',
    description: 'Functioneel dragen van gewicht in beide handen.',
    category: 'STRENGTH',
    bodyRegion: ['FULL_BODY'],
    difficulty: 'BEGINNER',
    loadType: 'WEIGHTED',
    isUnilateral: false,
    movementPattern: 'CARRY',
    tags: ['carry', 'functioneel', 'grip'],
    instructions: ['Pak zwaar gewicht in elke hand', 'Loop met rechte houding', 'Schouders naar achteren', 'Strakke core'],
    muscleLoads: { Core: 4, Onderarmen: 5, 'Schouders lateraal': 3, Bovenrug: 3, Glutes: 2 },
  },
  {
    name: 'Suitcase Carry',
    description: 'Eenzijdig dragen voor anti-laterale flexie. Hoge QL + oblique activatie.',
    category: 'STRENGTH',
    bodyRegion: ['FULL_BODY'],
    difficulty: 'INTERMEDIATE',
    loadType: 'WEIGHTED',
    isUnilateral: true,
    movementPattern: 'CARRY',
    tags: ['carry', 'core', 'anti-lateraal'],
    instructions: ['Gewicht in één hand', 'Houd romp recht zonder zijwaarts leunen', 'Loop gecontroleerd'],
    muscleLoads: { Core: 5, Onderarmen: 4, Abductoren: 3, 'Schouders lateraal': 2 },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // ADDUCTOREN / LIES (Copenhagen-familie — Haroy 2019, Serner 2014)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'Copenhagen Adduction (long-lever)',
    description: 'Zijligging plank waarbij bovenbeen van trainingspartner/bank ondersteunt aan enkel. Gold-standard liesblessure-preventie in voetbal (Haroy 2019 BJSM). Serner 2014 mat 108% MVIC adductor longus — hoogste van alle geteste oefeningen.',
    category: 'STRENGTH',
    bodyRegion: ['HIP'],
    difficulty: 'ADVANCED',
    loadType: 'BODYWEIGHT',
    isUnilateral: true,
    movementPattern: 'ISOLATION_LOWER',
    tags: ['lies', 'adductoren', 'preventie', 'voetbal', 'FIFA11+'],
    instructions: ['Lig op je zij, onderste been gestrekt', 'Bovenste been rust op enkelhoogte op bank of partner', 'Til romp en onderste been van de grond, steun op onderarm', 'Zak gecontroleerd en push terug omhoog', '3×6-10 reps, 2×/week volgens Haroy-protocol'],
    muscleLoads: { Adductoren: 5, Core: 4, Abductoren: 3, Glutes: 2 },
  },
  {
    name: 'Copenhagen Side Plank (short-lever)',
    description: 'Regressie van Copenhagen Adduction — knie in plaats van enkel op steunpunt. Entry-level voor post-acute liesklachten (Ishoi 2016 IJSPT).',
    category: 'STABILITY',
    bodyRegion: ['HIP'],
    difficulty: 'INTERMEDIATE',
    loadType: 'BODYWEIGHT',
    isUnilateral: true,
    movementPattern: 'ISOLATION_LOWER',
    tags: ['lies', 'adductoren', 'revalidatie', 'zijplank'],
    instructions: ['Lig op zij, onderste knie gebogen onder je', 'Bovenste been op bank op kniehoogte', 'Til heup van de grond, houd 10-30s', 'Progressie naar long-lever'],
    muscleLoads: { Adductoren: 4, Core: 4, Abductoren: 3 },
  },
  {
    name: 'Adductor Squeeze (bal, 45°)',
    description: 'Isometrische knijp met bal tussen knieën in 45°-heupflexie. Klassieke startoefening adductor-related groin pain (Delahunt 2011), ook gebruikt als HAGOS-testpositie.',
    category: 'STABILITY',
    bodyRegion: ['HIP'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'ISOLATION_LOWER',
    tags: ['lies', 'adductoren', 'isometrisch', 'beginner'],
    instructions: ['Lig op rug, knieën in 45° flexie', 'Plaats bal tussen knieën', 'Knijp 5-10s, ontspan, herhaal'],
    muscleLoads: { Adductoren: 3, Core: 2 },
  },
  {
    name: 'Standing Cable Hip Adduction',
    description: 'Staande concentrische adductie via kabelmachine. Laag-drempelig alternatief voor oudere patiënten of re-entry na acute liesklachten (Serner 2014 EMG).',
    category: 'STRENGTH',
    bodyRegion: ['HIP'],
    difficulty: 'BEGINNER',
    loadType: 'MACHINE',
    isUnilateral: true,
    movementPattern: 'ISOLATION_LOWER',
    tags: ['lies', 'adductoren', 'kabel'],
    instructions: ['Bevestig enkelband aan kabel', 'Sta zijwaarts, been weg van machine', 'Trek been naar midden toe', 'Gecontroleerd terug'],
    muscleLoads: { Adductoren: 4, Core: 2 },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // TENDINOPATHIE-PROTOCOLLEN (Alfredson, HSR, Silbernagel)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'Alfredson Heel Drop (knie gestrekt)',
    description: 'Gold-standard eccentric heel drop voor mid-portion Achilles tendinopathie. 3×15 reps, 2×/dag, 12 weken (Alfredson 1998 AJSM). Knie gestrekt = gastrocnemius-focus.',
    category: 'STRENGTH',
    bodyRegion: ['ANKLE'],
    difficulty: 'INTERMEDIATE',
    loadType: 'BODYWEIGHT',
    isUnilateral: true,
    movementPattern: 'CALF_RAISE',
    tags: ['achilles', 'tendinopathie', 'eccentric', 'Alfredson', 'revalidatie'],
    instructions: ['Sta op rand trap/traptrede met voorvoet', 'Duw met beide benen omhoog', 'Laat gecontroleerd zakken op aangedane zij, knie gestrekt', '3×15 langzaam (3-4s) zakken, 2×/dag, 12 wk'],
    muscleLoads: { Calves: 5, Hamstrings: 1 },
  },
  {
    name: 'Alfredson Heel Drop (knie gebogen)',
    description: 'Soleus-specifieke eccentric variant — hoort bij Alfredson-duo voor Achilles tendinopathie. Knie ~45° gebogen isoleert soleus.',
    category: 'STRENGTH',
    bodyRegion: ['ANKLE'],
    difficulty: 'INTERMEDIATE',
    loadType: 'BODYWEIGHT',
    isUnilateral: true,
    movementPattern: 'CALF_RAISE',
    tags: ['achilles', 'tendinopathie', 'eccentric', 'soleus', 'Alfredson'],
    instructions: ['Sta op rand trap met voorvoet', 'Houd knie licht gebogen', 'Duw omhoog met beide, zak eenzijdig', '3×15, 2×/dag, 12 wk'],
    muscleLoads: { Calves: 5 },
  },
  {
    name: 'Spanish Squat',
    description: 'Isometrische squat met band achter knieën. Rio 2015 BJSM: isometrische contracties op 70% MVIC, 5×45s, verlagen patella-tendinopathiepijn acuut in-season.',
    category: 'STRENGTH',
    bodyRegion: ['KNEE'],
    difficulty: 'INTERMEDIATE',
    loadType: 'BAND',
    isUnilateral: false,
    movementPattern: 'SQUAT',
    tags: ['patella', 'tendinopathie', 'isometrisch', 'pijndemping'],
    instructions: ['Bevestig band rond stevig ankerpunt op kniehoogte', 'Stap in band zodat deze achter je knieën ligt', 'Leun achterover en zak tot ~70° knieflexie', 'Houd 45s × 5 sets, pauze 2 min'],
    muscleLoads: { Quadriceps: 5, Glutes: 2 },
  },
  {
    name: 'HSR Knee Extension',
    description: 'Heavy-slow-resistance knie-extensie, 6s excentrisch + 6s concentrisch. Kongsgaard 2009: betere langetermijnresultaten dan eccentric alone voor patella-tendinopathie.',
    category: 'STRENGTH',
    bodyRegion: ['KNEE'],
    difficulty: 'ADVANCED',
    loadType: 'MACHINE',
    isUnilateral: false,
    movementPattern: 'ISOLATION_LOWER',
    tags: ['patella', 'tendinopathie', 'HSR', 'heavy-slow'],
    instructions: ['Machine op 15RM-belasting, afbouwen naar 6RM over 12 wk', 'Tempo: 6s concentrisch, 6s excentrisch', '3 sets, 3×/week'],
    muscleLoads: { Quadriceps: 5, Core: 1 },
  },
  {
    name: 'HSR Leg Press',
    description: 'Heavy-slow-resistance leg press — geschikt voor gecombineerde patella/achilles-tendinopathie (Beyer 2015 AJSM).',
    category: 'STRENGTH',
    bodyRegion: ['KNEE', 'ANKLE'],
    difficulty: 'ADVANCED',
    loadType: 'MACHINE',
    isUnilateral: false,
    movementPattern: 'SQUAT',
    tags: ['tendinopathie', 'HSR', 'heavy-slow'],
    instructions: ['Leg press op 15RM aanvang', '6s concentrisch, 6s excentrisch', '3 sets × 3/week, 12 wk'],
    muscleLoads: { Quadriceps: 5, Glutes: 4, Hamstrings: 2, Calves: 2 },
  },
  {
    name: 'Single-Leg Decline Squat (25°)',
    description: 'Eenzijdige squat op 25° helling — Purdam 2004 protocol voor patella-tendinopathie. Maximaliseert patellar-tendon loading via afgenomen ankle-strategie.',
    category: 'STRENGTH',
    bodyRegion: ['KNEE'],
    difficulty: 'ADVANCED',
    loadType: 'BODYWEIGHT',
    isUnilateral: true,
    movementPattern: 'SQUAT',
    tags: ['patella', 'tendinopathie', 'eccentric', 'decline', 'Purdam'],
    instructions: ['Sta op 25°-helling, hakken hoger dan tenen', 'Sta op één been', 'Zak langzaam tot 60° knieflexie', 'Duw omhoog met beide benen'],
    muscleLoads: { Quadriceps: 5, Glutes: 2 },
  },
  {
    name: 'Wrist Extensor Eccentric (Tyler Twist)',
    description: 'Eccentric polsextensie met FlexBar — Tyler 2010 JSES RCT toonde 81% pijnreductie bij lateral epicondylalgie (tennis elbow) in 7 weken.',
    category: 'STRENGTH',
    bodyRegion: ['ELBOW', 'WRIST'],
    difficulty: 'BEGINNER',
    loadType: 'BAND',
    isUnilateral: true,
    movementPattern: 'ISOLATION_UPPER',
    tags: ['tennis-elbow', 'eccentric', 'Tyler-Twist', 'epicondylalgie'],
    instructions: ['Pak FlexBar met aangedane hand bovenhands', 'Grijp andere uiteinde met gezonde hand', 'Twist FlexBar tot tegenovergestelde richtingen', 'Houd vast, draai aangedane pols langzaam uit twist (eccentric, 3-4s)', '3×15 reps, 1×/dag'],
    muscleLoads: { Onderarmen: 5 },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // HIP / GLUTE ACTIVATION (Boren 2011, Distefano 2009)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'Side Plank with Hip Abduction',
    description: 'Zijplank + bovenbeen-abductie. Boren 2011 IJSPT: 103% MVIC gluteus medius — hoogste van alle onderzochte oefeningen.',
    category: 'STABILITY',
    bodyRegion: ['HIP'],
    difficulty: 'ADVANCED',
    loadType: 'BODYWEIGHT',
    isUnilateral: true,
    movementPattern: 'ISOLATION_LOWER',
    tags: ['glut-medius', 'zijplank', 'abductie', 'core'],
    instructions: ['Zijplank op onderarm, lichaam in rechte lijn', 'Til bovenste been gecontroleerd omhoog', 'Houd 2s top, zak terug', '3×8-10 per zij'],
    muscleLoads: { Abductoren: 5, Core: 5, Glutes: 4, Adductoren: 2 },
  },
  {
    name: 'Lateral Band Walk',
    description: 'Zijwaartse mini-band walk, band rond enkels = hoogste gluteus-medius activatie (Distefano 2009 JOSPT, Cambridge 2012). Standaard in PFPS/ACL-prehab.',
    category: 'STRENGTH',
    bodyRegion: ['HIP'],
    difficulty: 'BEGINNER',
    loadType: 'BAND',
    isUnilateral: false,
    movementPattern: 'ISOLATION_LOWER',
    tags: ['glut-medius', 'PFPS', 'band', 'activation', 'prehab'],
    instructions: ['Band rond enkels', 'Halve squat-positie', 'Stap zijwaarts 10 stappen, dan terug', 'Houd spanning constant op band'],
    muscleLoads: { Abductoren: 4, Glutes: 3, Quadriceps: 2 },
  },
  {
    name: 'Monster Walk (forward band)',
    description: 'Voorwaartse band walk in athletic stance — frontaal-vlak aanvulling op lateral band walk (Distefano 2009 JOSPT).',
    category: 'STRENGTH',
    bodyRegion: ['HIP'],
    difficulty: 'BEGINNER',
    loadType: 'BAND',
    isUnilateral: false,
    movementPattern: 'ISOLATION_LOWER',
    tags: ['glut-medius', 'band', 'activation'],
    instructions: ['Band rond enkels of net boven knieën', 'Halve squat-positie', 'Stap diagonaal voorwaarts (rechts-links-rechts)', '10-15 stappen, dan achterwaarts terug'],
    muscleLoads: { Glutes: 3, Abductoren: 3, 'Hip flexors': 2, Quadriceps: 2 },
  },
  {
    name: 'Quadruped Hip Extension (Donkey Kick)',
    description: 'Quadruped eenzijdige heupextensie. Boren 2011: ~75% MVIC gluteus maximus zonder axiale belasting — geschikt post-op heup/rug.',
    category: 'STRENGTH',
    bodyRegion: ['HIP'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: true,
    movementPattern: 'ISOLATION_LOWER',
    tags: ['glut-max', 'revalidatie', 'quadruped'],
    instructions: ['Start op handen en knieën', 'Knie 90° gebogen, duw hiel naar plafond', 'Heup niet laten roteren', 'Houd 1s top'],
    muscleLoads: { Glutes: 4, Onderrug: 2, Core: 2 },
  },
  {
    name: 'Fire Hydrant',
    description: 'Quadruped eenzijdige heupabductie. Boren 2011: gluteus medius activatie zonder axiale belasting.',
    category: 'STRENGTH',
    bodyRegion: ['HIP'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: true,
    movementPattern: 'ISOLATION_LOWER',
    tags: ['glut-medius', 'quadruped', 'activation'],
    instructions: ['Start op handen en knieën', 'Knie 90° gebogen, til been zijwaarts omhoog', 'Been niet laten draaien', '12-15 reps per zij'],
    muscleLoads: { Abductoren: 3, Glutes: 3, Core: 2 },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // LUMBAR / CORE (McGill Big 3 + anti-rotation)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'McGill Curl-Up',
    description: 'Curl-up met één knie gebogen, onderrug in neutrale positie — McGill Big 3. Rectus abdominis activatie met minimale lumbar shear (McGill 2009 Arch Phys Med Rehab).',
    category: 'STABILITY',
    bodyRegion: ['LUMBAR'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'CORE',
    tags: ['LBP', 'McGill', 'Big3', 'revalidatie'],
    instructions: ['Lig op rug, één been gebogen, ander gestrekt', 'Handen onder lordose voor ondersteuning', 'Til hoofd en schouders enkele cm omhoog', 'Onderrug niet platdrukken tegen grond', '5-10s hold, 5 reps per zij'],
    muscleLoads: { Core: 4, Onderrug: 1 },
  },
  {
    name: 'Stir-the-Pot',
    description: 'Onderarm-plank op Swiss ball met cirkelende armen. McGill 2010 Strength Cond J: dynamische anti-extension plank-progressie.',
    category: 'STABILITY',
    bodyRegion: ['LUMBAR', 'FULL_BODY'],
    difficulty: 'ADVANCED',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'CORE',
    tags: ['McGill', 'anti-extension', 'plank', 'swiss-ball'],
    instructions: ['Onderarmen op Swiss ball, lichaam in plankpositie', 'Maak kleine cirkels met onderarmen, beide richtingen', 'Romp stil houden', '10 cirkels per richting × 3 sets'],
    muscleLoads: { Core: 5, 'Schouders anterieur': 3, Bovenrug: 2 },
  },
  {
    name: 'Bear Crawl (hold / march)',
    description: 'Quadruped hold of lopende progressie met knieën net van grond. Anti-extension + contralaterale stabiliteit, populair in rehab-to-performance.',
    category: 'STABILITY',
    bodyRegion: ['FULL_BODY'],
    difficulty: 'INTERMEDIATE',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'CORE',
    tags: ['anti-extension', 'core', 'quadruped'],
    instructions: ['Start op handen en knieën', 'Til knieën 2-3 cm van de grond', 'Hold 20-30s of stap contralateraal voor/achteruit', 'Rug neutraal, heupen stabiel'],
    muscleLoads: { Core: 4, 'Schouders anterieur': 3, Quadriceps: 3, Bovenrug: 2 },
  },
  {
    name: 'Renegade Row',
    description: 'Plank + afwisselende eenzijdige row met dumbbells. Anti-rotation + pulling, populair in rehab-to-performance overgangsfase.',
    category: 'STRENGTH',
    bodyRegion: ['FULL_BODY'],
    difficulty: 'ADVANCED',
    loadType: 'WEIGHTED',
    isUnilateral: true,
    movementPattern: 'PULL_HORIZONTAL',
    tags: ['anti-rotation', 'core', 'row', 'plank'],
    instructions: ['Push-up positie met dumbbells in handen', 'Voeten breed voor stabiliteit', 'Row eenzijdig naar heup, romp stil', 'Wissel zijdes', '3×8 per zij'],
    muscleLoads: { Core: 5, Bovenrug: 4, Lats: 3, 'Schouders posterieur': 3, Triceps: 2 },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // CERVICAAL / THORACAAL / SCAPULAIR
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'Chin Tuck (craniocervical flexion)',
    description: 'Deep neck flexor activatie — Jull 2008 JMPT / Falla 2012 gold-standard voor chronische nekpijn (DCF-training).',
    category: 'STABILITY',
    bodyRegion: ['CERVICAL'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'ISOLATION_UPPER',
    tags: ['nek', 'DCF', 'craniocervical', 'Jull'],
    instructions: ['Sta of zit met rechte rug', 'Trek kin recht naar achter (dubbele kin)', 'Hoofd niet kantelen', 'Houd 5-10s, 10 reps, meerdere keren per dag'],
    muscleLoads: { 'Diepe halsflexoren': 3 },
  },
  {
    name: 'Chin Tuck Endurance (supine hold)',
    description: 'Liggende chin tuck met druksensor — endurance-variant volgens DNF-testnormen (Jull 2008).',
    category: 'STABILITY',
    bodyRegion: ['CERVICAL'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'ISOLATION_UPPER',
    tags: ['nek', 'DCF', 'endurance', 'supine'],
    instructions: ['Lig op rug, hoofd neutraal', 'Knik kin naar borst zonder hoofd op te tillen', 'Houd 10s × 10 reps', 'Progressie: langere holds tot 10×10s zonder compensatie'],
    muscleLoads: { 'Diepe halsflexoren': 3 },
  },
  {
    name: 'Prone Thoracic Extension',
    description: 'Buiklig met armen overhead — thoracale extensie tegen kyfotische houding. Klassieke mobility-oefening bij bureauwerker-posturale klachten.',
    category: 'MOBILITY',
    bodyRegion: ['THORACIC'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'ISOLATION_UPPER',
    tags: ['thoracaal', 'mobility', 'houding', 'extensie'],
    instructions: ['Lig op buik, armen gestrekt boven hoofd', 'Til armen en bovenlichaam gecontroleerd op', 'Knijp schouderbladen samen', 'Houd 2s, 10-12 reps'],
    muscleLoads: { Bovenrug: 3, Onderrug: 2, 'Schouders posterieur': 2 },
  },
  {
    name: 'Band Pull-Apart',
    description: 'Scapulaire retractie met weerstandsband. Cools 2014 BJSM: mid-trapezius + rhomboid activatie voor post-impingement houdingscorrectie.',
    category: 'STRENGTH',
    bodyRegion: ['SHOULDER', 'THORACIC'],
    difficulty: 'BEGINNER',
    loadType: 'BAND',
    isUnilateral: false,
    movementPattern: 'PULL_HORIZONTAL',
    tags: ['scapulair', 'impingement', 'band', 'houding'],
    instructions: ['Band in beide handen, armen voor je gestrekt', 'Trek band uit elkaar tot schouderbreedte', 'Knijp schouderbladen samen', 'Gecontroleerd terug', '3×12-15'],
    muscleLoads: { Bovenrug: 4, 'Schouders posterieur': 3, Rotatorcuff: 2 },
  },
  {
    name: 'Wall Slide (serratus)',
    description: 'Scapulothoracic coördinatie-oefening. Hardwick 2006 JOSPT: serratus anterior ~60% MVIC — RCT-ondersteund bij schouder-impingement.',
    category: 'STABILITY',
    bodyRegion: ['SHOULDER'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'PUSH_VERTICAL',
    tags: ['serratus', 'impingement', 'scapulair', 'Hardwick'],
    instructions: ['Sta met rug tegen muur, armen in 90-90 positie', 'Schuif armen langzaam omhoog langs muur', 'Ellebogen en polsen contact met muur houden', 'Terug naar startpositie', '3×10-12 reps'],
    muscleLoads: { 'Schouders anterieur': 2, Bovenrug: 3, Rotatorcuff: 2 },
  },
  {
    name: 'Prone Horizontal Abduction at 100° (Full Can)',
    description: 'Buikligging horizontale abductie met externe rotatie (duim omhoog). Reinold 2004 JOSPT: 82% MVIC supraspinatus — hoogste gerapporteerde activatie.',
    category: 'STRENGTH',
    bodyRegion: ['SHOULDER'],
    difficulty: 'INTERMEDIATE',
    loadType: 'WEIGHTED',
    isUnilateral: true,
    movementPattern: 'ISOLATION_UPPER',
    tags: ['rotatorcuff', 'supraspinatus', 'Reinold', 'full-can'],
    instructions: ['Lig op buik op bank, arm hangt naar beneden', 'Duim omhoog (full can positie)', 'Til arm tot 100° abductie (net boven schouder)', 'Gecontroleerd terug', 'Licht gewicht 1-2kg, 3×10-12'],
    muscleLoads: { 'Schouders posterieur': 4, Rotatorcuff: 4, Bovenrug: 3 },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // BALANCE / PROPRIOCEPTIE
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'Single-Leg Balance (progressief)',
    description: 'Eenzijdige balans met progressies (ogen dicht, instabiel vlak, perturbaties). Hrysomallis 2011 Sports Med meta-analyse: effectief voor chronische enkelinstabiliteit.',
    category: 'STABILITY',
    bodyRegion: ['ANKLE'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: true,
    movementPattern: 'ISOLATION_LOWER',
    tags: ['balans', 'propriocepsis', 'enkel', 'CAI'],
    instructions: ['Sta op één been, andere gebogen', 'Houd 30s, dan wissel', 'Progressie: ogen dicht → wiebelkussen → bal gooien met partner'],
    muscleLoads: { Core: 2, Abductoren: 2, Calves: 2, 'Intrinsieke voetspieren': 2 },
  },
  {
    name: 'Y-Balance Reach',
    description: 'Dynamische balans-test en -oefening. Plisky 2006 JOSPT: voorspeller van onderste-extremiteit blessurerisico, RTS-criterium (Smith 2015).',
    category: 'STABILITY',
    bodyRegion: ['KNEE', 'ANKLE'],
    difficulty: 'INTERMEDIATE',
    loadType: 'BODYWEIGHT',
    isUnilateral: true,
    movementPattern: 'ISOLATION_LOWER',
    tags: ['balans', 'Y-balance', 'RTS', 'ACL'],
    instructions: ['Sta op één been in midden van Y-patroon', 'Reach met contralaterale voet anterior', 'Dan posteromediaal en posterolateraal', 'Blijf in balans, max reach noteren', '3 trials per richting'],
    muscleLoads: { Quadriceps: 3, Glutes: 3, Core: 3, Hamstrings: 2 },
  },
  {
    name: 'Single-Leg Hop for Distance',
    description: 'Eenbenige horizontale sprong-test. Noyes 1991 / Gustavsson 2006: standaard LSI-criterium (>90%) voor ACL-RTS.',
    category: 'PLYOMETRICS',
    bodyRegion: ['KNEE'],
    difficulty: 'INTERMEDIATE',
    loadType: 'BODYWEIGHT',
    isUnilateral: true,
    movementPattern: 'FULL_BODY',
    tags: ['ACL', 'RTS', 'hop-test', 'LSI'],
    instructions: ['Sta op één been achter lijn', 'Spring zo ver mogelijk, land op zelfde been', 'Houd landing 2s stabiel', '3 trials, max noteren; vergelijk L/R (LSI >90%)'],
    muscleLoads: { Quadriceps: 4, Glutes: 4, Calves: 4, Hamstrings: 3 },
  },
  {
    name: 'Triple Crossover Hop',
    description: 'Drievoudige crossover-sprong — frontaal-vlak RTS-test, Noyes 1991 AJSM, 90% LSI-criterium voor ACL-RTS.',
    category: 'PLYOMETRICS',
    bodyRegion: ['KNEE'],
    difficulty: 'ADVANCED',
    loadType: 'BODYWEIGHT',
    isUnilateral: true,
    movementPattern: 'FULL_BODY',
    tags: ['ACL', 'RTS', 'hop-test', 'crossover'],
    instructions: ['Sta op één been', 'Spring 3× kruisend over lijn (links-rechts-links)', 'Land elke keer stabiel', '3 trials, totale afstand noteren'],
    muscleLoads: { Quadriceps: 4, Glutes: 4, Calves: 4, Abductoren: 3 },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // CARDIO (app had 0 cardio-oefeningen)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'Rowing Ergometer',
    description: 'Concept2/roeimachine — low-impact full-body cardio. Universele basis in fysio-praktijken; geschikt bij onderste-extremiteit revalidatie.',
    category: 'CARDIO',
    bodyRegion: ['FULL_BODY'],
    difficulty: 'BEGINNER',
    loadType: 'MACHINE',
    isUnilateral: false,
    movementPattern: 'FULL_BODY',
    tags: ['cardio', 'roeien', 'low-impact', 'full-body'],
    instructions: ['Voeten gespannen in voetsteunen', 'Drive: benen eerst, dan rug, dan armen', 'Recovery: armen, rug, benen', 'Tempo 20-26 spm voor steady-state'],
    muscleLoads: { Bovenrug: 3, Quadriceps: 3, Lats: 3, Core: 3, Hamstrings: 2, Glutes: 2 },
  },
  {
    name: 'Air Bike (Assault Bike)',
    description: 'Fietsen-met-armen voor gewrichtsvriendelijke HIIT. Full-body cardio zonder impact.',
    category: 'CARDIO',
    bodyRegion: ['FULL_BODY'],
    difficulty: 'BEGINNER',
    loadType: 'MACHINE',
    isUnilateral: false,
    movementPattern: 'FULL_BODY',
    tags: ['cardio', 'HIIT', 'low-impact', 'air-bike'],
    instructions: ['Zadelhoogte: lichte knie-flexie in onderste positie', 'Tegelijk armen en benen inzetten', 'Steady-state of intervals (20/10)'],
    muscleLoads: { Quadriceps: 3, 'Schouders anterieur': 2, Core: 2, Hamstrings: 2 },
  },
  {
    name: 'Stationary Bike',
    description: 'Fiets (upright of recumbent). Fransen 2015 Cochrane: post-op knie/heup standaard oefening voor ROM en uithoudingsvermogen.',
    category: 'CARDIO',
    bodyRegion: ['KNEE'],
    difficulty: 'BEGINNER',
    loadType: 'MACHINE',
    isUnilateral: false,
    movementPattern: 'FULL_BODY',
    tags: ['cardio', 'fiets', 'post-op', 'knie-OA'],
    instructions: ['Zadelhoogte: 5° knie-flexie in onderste positie', 'Start zonder weerstand voor ROM', 'Progressie: weerstand + tijd', '10-30 min steady-state'],
    muscleLoads: { Quadriceps: 3, Hamstrings: 2, Calves: 2 },
  },
  {
    name: 'Elliptical / Crosstrainer',
    description: 'Crosstrainer — low-impact running-alternatief. Geschikt bij belastings-opbouw na enkel/knie-blessure.',
    category: 'CARDIO',
    bodyRegion: ['FULL_BODY'],
    difficulty: 'BEGINNER',
    loadType: 'MACHINE',
    isUnilateral: false,
    movementPattern: 'FULL_BODY',
    tags: ['cardio', 'low-impact', 'crosstrainer'],
    instructions: ['Voeten plat op platforms', 'Gebruik ook armen voor full-body', 'Rechte houding, core aangespannen'],
    muscleLoads: { Quadriceps: 3, Glutes: 2, Hamstrings: 2, Calves: 2, 'Schouders anterieur': 1 },
  },
  {
    name: 'A-Skip',
    description: 'Running drill — hoge knieheffing met hamstring-snap. Basis running-drill voor RTS-running progressie.',
    category: 'PLYOMETRICS',
    bodyRegion: ['FULL_BODY'],
    difficulty: 'INTERMEDIATE',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'FULL_BODY',
    tags: ['running', 'drill', 'RTS', 'coordinatie'],
    instructions: ['Skip voorwaarts met agressieve kniedrive tot heuphoogte', 'Standbeen actief (pogo-achtig)', 'Armen meewerkend', '2×20m'],
    muscleLoads: { 'Hip flexors': 4, Calves: 4, Quadriceps: 3, Core: 3 },
  },
  {
    name: 'Bounding',
    description: 'Overdreven sprong-loopoefening. Markovic 2007 plyo-meta: sprint/vermogensontwikkeling. Late-stage ACL/sprint RTS.',
    category: 'PLYOMETRICS',
    bodyRegion: ['FULL_BODY'],
    difficulty: 'ADVANCED',
    loadType: 'BODYWEIGHT',
    isUnilateral: true,
    movementPattern: 'FULL_BODY',
    tags: ['sprint', 'plyo', 'RTS', 'vermogen'],
    instructions: ['Agressief afdrukken op één been', 'Maximale vluchttijd en afstand', 'Land op ander been, herhaal', 'Focus op horizontale voortgang', '2-4×20-30m'],
    muscleLoads: { Calves: 5, Quadriceps: 4, Glutes: 4, Hamstrings: 3, 'Hip flexors': 3 },
  },
  {
    name: 'Pogo Hops',
    description: 'Stijve-enkel-sprongen. Davies 2015 IJSPT: entry-level tendon stiffness in Achilles/patella RTS-loading ladder.',
    category: 'PLYOMETRICS',
    bodyRegion: ['ANKLE'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'CALF_RAISE',
    tags: ['tendon-stiffness', 'plyo', 'achilles', 'enkel'],
    instructions: ['Spring met stijve enkels op plaats', 'Minimale knieflexie — snap de grond af', 'Korte grondcontact', '3×20 reps'],
    muscleLoads: { Calves: 5, Quadriceps: 2, 'Intrinsieke voetspieren': 2 },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // ENKEL / VOET / SHIN
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'Tibialis Anterior Raise',
    description: 'Dorsiflexie-oefening (wand-gebaseerd of met band). Galbraith 2009 Phys Sportsmed MTSS-review: standaard bij shin splints.',
    category: 'STRENGTH',
    bodyRegion: ['ANKLE'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'ISOLATION_LOWER',
    tags: ['MTSS', 'shin-splints', 'tibialis-anterior', 'dorsiflexie'],
    instructions: ['Sta met hakken tegen muur, tenen op 10 cm afstand', 'Til tenen en voorvoet omhoog', 'Gecontroleerd terug', '3×15-20 reps'],
    muscleLoads: { 'Tibialis anterior': 4, Core: 1 },
  },
  {
    name: 'Heel Walk',
    description: 'Lopen op hakken — endurance-variant tibialis anterior training bij MTSS (Galbraith 2009 review).',
    category: 'MOBILITY',
    bodyRegion: ['ANKLE'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'FULL_BODY',
    tags: ['MTSS', 'shin-splints', 'tibialis-anterior'],
    instructions: ['Loop op hakken met tenen omhoog', 'Rechte houding', '2-3×20m'],
    muscleLoads: { 'Tibialis anterior': 3, Core: 2 },
  },
  {
    name: 'Short Foot (Toe Yoga)',
    description: 'Intrinsieke voetspier-activatie — platvoet, plantar fasciitis. McKeon 2015 BJSM foot-core paradigm.',
    category: 'STABILITY',
    bodyRegion: ['FOOT'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'ISOLATION_LOWER',
    tags: ['platvoet', 'plantar-fasciitis', 'intrinsieke-voet', 'foot-core'],
    instructions: ['Zit of sta met voeten plat', 'Trek voorvoet naar hiel zonder tenen te krommen — boog omhoog', 'Houd 5-10s', '10-15 reps per voet'],
    muscleLoads: { 'Intrinsieke voetspieren': 4 },
  },
]

export default STANDARD_EXERCISES
