/**
 * Standaard oefeningen-database voor Movement Based Therapy Amsterdam.
 * Evidence-based muscleLoads op basis van peer-reviewed EMG-studies (2000-2025).
 *
 * Conversie % MVIC → 1-5 schaal:
 *   0-20%  = 1 (lichte activatie)
 *   21-40% = 2 (matig-licht)
 *   41-60% = 3 (matig)
 *   61-80% = 4 (hoog)
 *   81%+   = 5 (zeer hoog)
 *
 * Zie emg_onderste_extremiteit.md en emg_bovenste_core.md voor bronvermelding.
 * Progressie/regressie wordt in seed.ts gekoppeld via exercise-progressions.ts.
 */

type SeedExercise = {
  name: string
  description: string
  category: 'STRENGTH' | 'MOBILITY' | 'PLYOMETRICS' | 'CARDIO' | 'STABILITY'
  bodyRegion: string[]
  difficulty: 'BEGINNER' | 'INTERMEDIATE' | 'ADVANCED'
  loadType: 'BODYWEIGHT' | 'WEIGHTED' | 'MACHINE' | 'BAND'
  isUnilateral: boolean
  movementPattern: string | null
  tags: string[]
  instructions: string[]
  muscleLoads: Record<string, number>
}

export const STANDARD_EXERCISES: SeedExercise[] = [
  // ═══════════════════════════════════════════════════════════════════════════
  // LOWER BODY — SQUAT PATTERNS
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'Wall Sit',
    description: 'Isometrische squat tegen de muur. Laag patellofemoraal risico — ideaal als beginners-regressie voor quadricepskracht bij knieklachten.',
    category: 'STRENGTH',
    bodyRegion: ['KNEE'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'SQUAT',
    tags: ['isometrisch', 'knie', 'beginner', 'revalidatie'],
    instructions: ['Leun met rug tegen muur', 'Zak tot 90 graden in de knieën', 'Houd de positie vast', 'Adem rustig door'],
    muscleLoads: { Quadriceps: 4, Glutes: 1, Core: 2 },
  },
  {
    name: 'Bodyweight Squat',
    description: 'Basis squat met lichaamsgewicht. Ideaal als technische fundering.',
    category: 'STRENGTH',
    bodyRegion: ['KNEE', 'HIP'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'SQUAT',
    tags: ['squat', 'beginner', 'lichaamsgewicht'],
    instructions: ['Voeten op schouderbreedte', 'Zak tot parallel', 'Houd borst omhoog', 'Druk door de hakken'],
    muscleLoads: { Quadriceps: 3, Glutes: 3, Calves: 1, Core: 2 },
  },
  {
    name: 'Goblet Squat',
    description: 'Squat met een dumbbell of kettlebell voor de borst. Instap-progressie richting beladen squats.',
    category: 'STRENGTH',
    bodyRegion: ['KNEE', 'HIP'],
    difficulty: 'BEGINNER',
    loadType: 'WEIGHTED',
    isUnilateral: false,
    movementPattern: 'SQUAT',
    tags: ['squat', 'benen', 'beginner'],
    instructions: ['Houd het gewicht tegen je borst', 'Voeten iets breder dan schouderbreedte', 'Zak met ellebogen tussen de knieën'],
    muscleLoads: { Quadriceps: 4, Glutes: 3, Core: 3 },
  },
  {
    name: 'Back Squat',
    description: 'Bilaterale squat met barbell op de bovenrug. High-bar: hogere VL/rectus femoris activatie. Low-bar: hogere gluteus/hamstring activatie [Murawa 2020, Yavuz 2015].',
    category: 'STRENGTH',
    bodyRegion: ['KNEE', 'HIP'],
    difficulty: 'INTERMEDIATE',
    loadType: 'WEIGHTED',
    isUnilateral: false,
    movementPattern: 'SQUAT',
    tags: ['squat', 'benen', 'compound'],
    instructions: ['Plaats de barbell op je bovenrug', 'Voeten op schouderbreedte', 'Zak tot minstens parallel', 'Druk door de hakken omhoog'],
    muscleLoads: { Quadriceps: 5, Glutes: 4, Hamstrings: 3, Core: 3, Calves: 2, Onderrug: 3 },
  },
  {
    name: 'Front Squat',
    description: 'Squat met de barbell op de voorste schouders. Hogere vastus medialis (+6-12% MVIC) en rectus femoris activatie dan back squat [Yavuz 2015].',
    category: 'STRENGTH',
    bodyRegion: ['KNEE', 'HIP'],
    difficulty: 'ADVANCED',
    loadType: 'WEIGHTED',
    isUnilateral: false,
    movementPattern: 'SQUAT',
    tags: ['squat', 'benen', 'quadriceps', 'vmo'],
    instructions: ['Barbell op voorste deltoids', 'Ellebogen hoog houden', 'Zak diep met rechte romp', 'Druk omhoog vanuit de hakken'],
    muscleLoads: { Quadriceps: 5, Glutes: 3, Core: 4, Calves: 2 },
  },
  {
    name: 'Bulgarian Split Squat',
    description: 'Unilaterale squat met achterste voet op een verhoging. Vastus medialis 85.4% MVIC — hoogste van alle bodyweight quadriceps-oefeningen [Mackey 2021].',
    category: 'STRENGTH',
    bodyRegion: ['KNEE', 'HIP'],
    difficulty: 'INTERMEDIATE',
    loadType: 'BODYWEIGHT',
    isUnilateral: true,
    movementPattern: 'LUNGE',
    tags: ['squat', 'unilateraal', 'benen', 'vmo'],
    instructions: ['Achterste voet op bank of verhoging', 'Zak recht naar beneden', 'Knie blijft boven de tenen', 'Lichte vooroverleun voor meer glute-activatie'],
    muscleLoads: { Quadriceps: 5, Glutes: 4, Hamstrings: 3, Core: 3, Calves: 2 },
  },
  {
    name: 'Pistol Squat',
    description: 'Single-leg squat zonder steun. Gluteus maximus 71% MVIC — hoogste activatie van therapeutische oefeningen [Distefano 2009].',
    category: 'STRENGTH',
    bodyRegion: ['KNEE', 'HIP', 'ANKLE'],
    difficulty: 'ADVANCED',
    loadType: 'BODYWEIGHT',
    isUnilateral: true,
    movementPattern: 'SQUAT',
    tags: ['squat', 'unilateraal', 'balans', 'gevorderd'],
    instructions: ['Sta op één been', 'Strek het andere been naar voren', 'Zak zo diep mogelijk', 'Sta op zonder hulp'],
    muscleLoads: { Quadriceps: 5, Glutes: 5, Hamstrings: 3, Core: 4, Calves: 3, 'Hip flexors': 3 },
  },
  {
    name: 'Leg Press',
    description: 'Compound beenpers op de machine. Significant LAGERE quadriceps + core activatie dan vrije squats [Escamilla 2001]. Minder functioneel maar veilig voor knie-revalidatie.',
    category: 'STRENGTH',
    bodyRegion: ['KNEE', 'HIP'],
    difficulty: 'BEGINNER',
    loadType: 'MACHINE',
    isUnilateral: false,
    movementPattern: 'SQUAT',
    tags: ['benen', 'compound', 'machine', 'revalidatie'],
    instructions: ['Plaats voeten op schouderbreedte', 'Laat het gewicht zakken tot 90 graden', 'Druk omhoog zonder knieën te locken'],
    muscleLoads: { Quadriceps: 4, Glutes: 3, Hamstrings: 2, Calves: 1 },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // LOWER BODY — LUNGE PATTERNS
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'Step Up',
    description: 'Op een verhoging stappen. Matige-hoge gluteus maximus activatie (~40-60% MVIC). Hogere trede = meer GMax + quadriceps [Reiman 2012].',
    category: 'STRENGTH',
    bodyRegion: ['KNEE', 'HIP'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: true,
    movementPattern: 'LUNGE',
    tags: ['step-up', 'functioneel', 'unilateraal'],
    instructions: ['Plaats één voet op de verhoging', 'Druk je omhoog vanuit die voet', 'Laat gecontroleerd weer zakken'],
    muscleLoads: { Quadriceps: 3, Glutes: 3, Hamstrings: 2, Calves: 2, Core: 2 },
  },
  {
    name: 'Lateral Step-Up',
    description: 'Zijwaartse step-up. Gluteus maximus 79-113% MVIC — een van de meest effectieve gluteusoefeningen [Ayotte 2007].',
    category: 'STRENGTH',
    bodyRegion: ['KNEE', 'HIP'],
    difficulty: 'INTERMEDIATE',
    loadType: 'BODYWEIGHT',
    isUnilateral: true,
    movementPattern: 'LUNGE',
    tags: ['step-up', 'lateraal', 'glutes', 'unilateraal'],
    instructions: ['Sta naast de verhoging', 'Plaats zijwaarts één voet erop', 'Druk omhoog, lift het andere been', 'Laat gecontroleerd zakken'],
    muscleLoads: { Quadriceps: 4, Glutes: 5, Abductoren: 4, Core: 3, Calves: 2 },
  },
  {
    name: 'Walking Lunge',
    description: 'Voorwaartse lunges in beweging. Hogere erector spinae en gluteus maximus activatie dan stationaire lunge [Farrokhi 2008]. Lunges activeren GMax MEER dan back squats [Muyor 2021].',
    category: 'STRENGTH',
    bodyRegion: ['KNEE', 'HIP'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: true,
    movementPattern: 'LUNGE',
    tags: ['lunge', 'benen', 'dynamisch'],
    instructions: ['Neem een grote stap naar voren', 'Zak tot 90 graden in beide knieën', 'Druk af en breng het achterste been naar voren'],
    muscleLoads: { Quadriceps: 4, Glutes: 4, Hamstrings: 3, 'Hip flexors': 2, Core: 3 },
  },
  {
    name: 'Reverse Lunge',
    description: 'Lunge naar achteren — minder kniestress, vergelijkbare gluteusactivatie [Marchetti 2024]. GMax en GMed hoger in stilstaande (voorste) been.',
    category: 'STRENGTH',
    bodyRegion: ['KNEE', 'HIP'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: true,
    movementPattern: 'LUNGE',
    tags: ['lunge', 'benen', 'knie-vriendelijk'],
    instructions: ['Stap naar achteren', 'Zak tot 90 graden', 'Druk vanuit de voorste voet terug'],
    muscleLoads: { Quadriceps: 3, Glutes: 4, Hamstrings: 3, Core: 3 },
  },
  {
    name: 'Lateral Lunge',
    description: 'Zijwaartse lunge voor adductoren en laterale stabiliteit.',
    category: 'STRENGTH',
    bodyRegion: ['KNEE', 'HIP'],
    difficulty: 'INTERMEDIATE',
    loadType: 'BODYWEIGHT',
    isUnilateral: true,
    movementPattern: 'LUNGE',
    tags: ['lunge', 'lateraal', 'adductoren'],
    instructions: ['Stap zijwaarts', 'Zak in het gebogen been', 'Houd het rechte been gestrekt', 'Druk terug naar start'],
    muscleLoads: { Quadriceps: 3, Glutes: 3, Adductoren: 4, Abductoren: 2, Core: 2 },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // LOWER BODY — HINGE PATTERNS
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'Kettlebell Swing',
    description: 'Explosieve hip hinge met kettlebell. Hoge power output, leert ballistic hip extension.',
    category: 'STRENGTH',
    bodyRegion: ['HIP', 'BACK'],
    difficulty: 'INTERMEDIATE',
    loadType: 'WEIGHTED',
    isUnilateral: false,
    movementPattern: 'HINGE',
    tags: ['kettlebell', 'explosief', 'hinge'],
    instructions: ['Hinge met kettlebell tussen benen', 'Explosief heupen strekken', 'Kettlebell swingt tot schouderhoogte', 'Controleer de terugzwaai'],
    muscleLoads: { Glutes: 5, Hamstrings: 4, Core: 4, 'Schouders anterieur': 2, Onderrug: 3 },
  },
  {
    name: 'Good Morning',
    description: 'Hip hinge met barbell op de rug. Erector spinae 216.6 mV — vergelijkbaar met RDL [De Ridder 2015]. Hoge axiale belasting: minder geschikt bij lumbale pathologie.',
    category: 'STRENGTH',
    bodyRegion: ['HIP', 'BACK'],
    difficulty: 'INTERMEDIATE',
    loadType: 'WEIGHTED',
    isUnilateral: false,
    movementPattern: 'HINGE',
    tags: ['hinge', 'hamstrings', 'onderrug'],
    instructions: ['Barbell op de bovenrug', 'Lichte buiging in knieën', 'Hinge voorover vanuit de heupen', 'Sta terug op met gestrekte heupen'],
    muscleLoads: { Hamstrings: 4, Glutes: 3, Onderrug: 5, Core: 3 },
  },
  {
    name: 'Romanian Deadlift (RDL)',
    description: 'Hip hinge met nadruk op hamstrings en glutes. Hogere/vergelijkbare biceps femoris activatie dan conventionele deadlift — vooral proximaal [Lee 2018].',
    category: 'STRENGTH',
    bodyRegion: ['HIP', 'BACK'],
    difficulty: 'INTERMEDIATE',
    loadType: 'WEIGHTED',
    isUnilateral: false,
    movementPattern: 'HINGE',
    tags: ['deadlift', 'hamstrings', 'hinge'],
    instructions: ['Houd barbell/dumbbells dicht bij lichaam', 'Hinge vanuit de heupen', 'Lichte buiging in de knieën', 'Voel rek in hamstrings, sta terug op'],
    muscleLoads: { Hamstrings: 5, Glutes: 4, Onderrug: 4, Bovenrug: 2, Core: 3 },
  },
  {
    name: 'Conventional Deadlift',
    description: 'Compound tilbeweging vanaf de grond. Hogere rectus femoris, gluteus maximus en vastus activatie dan RDL [Lee 2018]. Hogere biceps femoris dan sumo [Escamilla 2002].',
    category: 'STRENGTH',
    bodyRegion: ['HIP', 'BACK', 'KNEE'],
    difficulty: 'INTERMEDIATE',
    loadType: 'WEIGHTED',
    isUnilateral: false,
    movementPattern: 'HINGE',
    tags: ['deadlift', 'compound', 'kracht'],
    instructions: ['Voeten op heupbreedte', 'Grijp de stang net buiten de knieën', 'Borst omhoog, rug neutraal', 'Druk door benen en heupen tegelijk'],
    muscleLoads: { Hamstrings: 4, Glutes: 5, Onderrug: 4, Quadriceps: 3, Bovenrug: 3, Core: 3, Onderarmen: 3 },
  },
  {
    name: 'Single Leg Deadlift',
    description: 'Unilaterale hip hinge met balanselement. Goede anti-rotatie training.',
    category: 'STABILITY',
    bodyRegion: ['HIP', 'BACK', 'ANKLE'],
    difficulty: 'INTERMEDIATE',
    loadType: 'BODYWEIGHT',
    isUnilateral: true,
    movementPattern: 'HINGE',
    tags: ['deadlift', 'balans', 'unilateraal'],
    instructions: ['Sta op één been', 'Hinge naar voren', 'Achterste been strekt naar achteren', 'Houd rug neutraal'],
    muscleLoads: { Hamstrings: 4, Glutes: 4, Core: 4, Calves: 2, Abductoren: 3 },
  },
  {
    name: 'Prone Leg Curl',
    description: 'Liggende hamstring curl. Biceps femoris 50.3%, semitendinosus 44.3% MVIC [Krommes 2021]. Prone variant activeert BF MEER dan ST (omgekeerd aan Nordic curl) — klinisch relevant.',
    category: 'STRENGTH',
    bodyRegion: ['KNEE'],
    difficulty: 'BEGINNER',
    loadType: 'MACHINE',
    isUnilateral: false,
    movementPattern: 'ISOLATION_LOWER',
    tags: ['hamstrings', 'isolatie', 'machine', 'laterale hamstrings'],
    instructions: ['Lig op je buik in de machine', 'Buig de knieën volledig', 'Laat gecontroleerd terug', 'Focus op de samentrekking'],
    muscleLoads: { Hamstrings: 3, Calves: 1 },
  },
  {
    name: 'Leg Curl (machine)',
    description: 'Geïsoleerde hamstringtraining (zittend of liggend). Regressie van Prone Leg Curl.',
    category: 'STRENGTH',
    bodyRegion: ['KNEE'],
    difficulty: 'BEGINNER',
    loadType: 'MACHINE',
    isUnilateral: false,
    movementPattern: 'ISOLATION_LOWER',
    tags: ['hamstrings', 'isolatie', 'machine'],
    instructions: ['Zit of lig in de machine', 'Buig de knieën', 'Laat gecontroleerd terug'],
    muscleLoads: { Hamstrings: 3 },
  },
  {
    name: 'Nordic Hamstring Curl',
    description: 'Excentrische hamstringtraining. Biceps femoris 74.8%, semitendinosus 78.3% MVIC [Krommes 2021]. Bewezen effectief voor hamstring-blessurepreventie. Activeert MEDIALE hamstrings meer dan prone curl.',
    category: 'STRENGTH',
    bodyRegion: ['KNEE'],
    difficulty: 'ADVANCED',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'ISOLATION_LOWER',
    tags: ['hamstrings', 'excentrisch', 'preventie', 'mediale hamstrings'],
    instructions: ['Kniel met enkels gefixeerd', 'Laat je romp gecontroleerd naar voren zakken', 'Rem de beweging af met je hamstrings', 'Vang op met handen'],
    muscleLoads: { Hamstrings: 5, Glutes: 3, Core: 3 },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // LOWER BODY — HIP THRUST & GLUTES
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'Glute Bridge',
    description: 'Basis gluteoefening liggend op de grond. Matige GMax activatie (~25-35% MVIC). Hamstrings activeren vergelijkbaar of hoger dan glutes [Distefano 2009].',
    category: 'STRENGTH',
    bodyRegion: ['HIP'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'HIP_THRUST',
    tags: ['glutes', 'bridge', 'beginner', 'revalidatie'],
    instructions: ['Lig op je rug, knieën gebogen', 'Druk heupen omhoog', 'Knijp glutes bovenaan', 'Laat langzaam zakken'],
    muscleLoads: { Glutes: 2, Hamstrings: 3, Core: 2 },
  },
  {
    name: 'Single Leg Glute Bridge',
    description: 'Unilaterale glute bridge. Significant hogere GMax activatie (~50-60% MVIC) dan bilateraal. Extra core/abductor-eis door eenzijdige stabilisatie [Distefano 2009].',
    category: 'STRENGTH',
    bodyRegion: ['HIP'],
    difficulty: 'INTERMEDIATE',
    loadType: 'BODYWEIGHT',
    isUnilateral: true,
    movementPattern: 'HIP_THRUST',
    tags: ['glutes', 'unilateraal', 'bridge'],
    instructions: ['Lig op je rug, één been gestrekt', 'Druk heupen omhoog met het steunbeen', 'Houd heupen level'],
    muscleLoads: { Glutes: 3, Hamstrings: 3, Core: 3, Abductoren: 2 },
  },
  {
    name: 'Barbell Hip Thrust',
    description: 'Geïsoleerde glutestraining met barbell. Gluteus maximus 86.8% MVIC gemiddeld, piek 216% [Contreras 2015]. Significant hogere glute-activatie dan back squat.',
    category: 'STRENGTH',
    bodyRegion: ['HIP'],
    difficulty: 'INTERMEDIATE',
    loadType: 'WEIGHTED',
    isUnilateral: false,
    movementPattern: 'HIP_THRUST',
    tags: ['glutes', 'hip thrust', 'kracht'],
    instructions: ['Bovenrug op bank, schouderbladen', 'Barbell over de heupen (met pad)', 'Druk heupen omhoog tot volledige extensie', 'Knijp glutes bovenaan 1-2 seconden'],
    muscleLoads: { Glutes: 5, Hamstrings: 4, Core: 2 },
  },
  {
    name: 'Single Leg Hip Thrust',
    description: 'Unilaterale hip thrust — progressie van de bilaterale variant. Extra vereiste voor anti-rotatie core en heup-stabilisatie.',
    category: 'STRENGTH',
    bodyRegion: ['HIP'],
    difficulty: 'ADVANCED',
    loadType: 'BODYWEIGHT',
    isUnilateral: true,
    movementPattern: 'HIP_THRUST',
    tags: ['glutes', 'hip thrust', 'unilateraal'],
    instructions: ['Bovenrug op bank, één been gestrekt', 'Druk heupen omhoog met steunbeen', 'Houd heupen level (geen side-drop)', 'Knijp glute bovenaan'],
    muscleLoads: { Glutes: 5, Hamstrings: 4, Core: 4, Abductoren: 3 },
  },
  {
    name: 'Clamshell',
    description: 'Gluteus medius activatie met weerstandsband. ~77% GMed MVIC met band (progressie 4). Hoogste "gluteal targeting index" — minimale TFL-activatie [Selkowitz 2013].',
    category: 'STABILITY',
    bodyRegion: ['HIP'],
    difficulty: 'BEGINNER',
    loadType: 'BAND',
    isUnilateral: true,
    movementPattern: 'ISOLATION_LOWER',
    tags: ['glutes', 'activatie', 'band', 'revalidatie', 'gmed'],
    instructions: ['Lig op je zij, knieën gebogen (60° hoek = beste GMed)', 'Band om de knieën', 'Open de bovenste knie als een schelp', 'Houd voeten bij elkaar'],
    muscleLoads: { Glutes: 4, Abductoren: 4, Core: 2 },
  },
  {
    name: 'Side-Lying Hip Abduction',
    description: 'Gluteus medius 81% MVIC — beste oefening voor GMed activatie van 12 geteste [Distefano 2009, Boren 2011]. Ook significante TFL-activatie (klinische overweging).',
    category: 'STRENGTH',
    bodyRegion: ['HIP'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: true,
    movementPattern: 'ISOLATION_LOWER',
    tags: ['glutes', 'gmed', 'abductie', 'revalidatie'],
    instructions: ['Lig op je zij, onderste been licht gebogen', 'Hef bovenste been recht omhoog', 'Houd heup niet voorover kantelen', 'Laat gecontroleerd zakken'],
    muscleLoads: { Glutes: 5, Abductoren: 5, Core: 2 },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // LOWER BODY — CALVES
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'Calf Raise (staand)',
    description: 'Staande kuitoefening (gestrekte knie). Gastrocnemius ~50-52% MVIC [Hébert-Losier 2009]. Significant effectiever voor gastrocnemius hypertrofie dan zittend [Nunes 2023].',
    category: 'STRENGTH',
    bodyRegion: ['ANKLE'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'CALF_RAISE',
    tags: ['kuiten', 'gastrocnemius', 'beginner'],
    instructions: ['Sta op de rand van een trede', 'Druk omhoog op je tenen', 'Laat langzaam zakken onder de rand', 'Volledige ROM gebruiken'],
    muscleLoads: { Calves: 4 },
  },
  {
    name: 'Single Leg Calf Raise',
    description: 'Unilaterale calf raise. Hogere totale activatie dan bilateraal door dubbele belasting. Essentieel bij achillespeesrevalidatie.',
    category: 'STRENGTH',
    bodyRegion: ['ANKLE'],
    difficulty: 'INTERMEDIATE',
    loadType: 'BODYWEIGHT',
    isUnilateral: true,
    movementPattern: 'CALF_RAISE',
    tags: ['kuiten', 'unilateraal', 'achilles', 'revalidatie'],
    instructions: ['Sta op één voet op de rand van trede', 'Druk omhoog op tenen', 'Laat langzaam zakken onder de rand', 'Focus op gecontroleerde excentrische fase'],
    muscleLoads: { Calves: 5, Core: 2 },
  },
  {
    name: 'Seated Calf Raise',
    description: 'Zittende calf raise (gebogen knie). Isoleert soleus — knieflexie vermindert gastrocnemius bijdrage mechanisch [Hébert-Losier 2009]. Ideaal bij achillespeesrevalidatie.',
    category: 'STRENGTH',
    bodyRegion: ['ANKLE'],
    difficulty: 'BEGINNER',
    loadType: 'MACHINE',
    isUnilateral: false,
    movementPattern: 'CALF_RAISE',
    tags: ['kuiten', 'soleus', 'machine', 'achilles'],
    instructions: ['Zit in de machine, knieën in 90°', 'Voetbal op de platform', 'Druk omhoog met alleen de voet', 'Volledige ROM'],
    muscleLoads: { Calves: 4 },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // LOWER BODY — KNEE ISOLATION
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'Leg Extension (machine)',
    description: 'Geïsoleerde quadricepstraining (open chain). Hoogste rectus femoris activatie. VMO significant hoger bij volledige extensie (laatste 30°) — klinisch relevant voor PFPS [Escamilla 2001].',
    category: 'STRENGTH',
    bodyRegion: ['KNEE'],
    difficulty: 'BEGINNER',
    loadType: 'MACHINE',
    isUnilateral: false,
    movementPattern: 'ISOLATION_LOWER',
    tags: ['quadriceps', 'isolatie', 'machine', 'vmo'],
    instructions: ['Zit met rug tegen het kussen', 'Strek de benen volledig', 'Houd pauze bij volle extensie (VMO focus)', 'Laat gecontroleerd zakken'],
    muscleLoads: { Quadriceps: 5 },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // UPPER BODY — PUSH HORIZONTAL
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'Wall Push-Up',
    description: 'Basis push-up tegen de muur. Ideaal als beginnersregressie bij schouder-revalidatie.',
    category: 'STRENGTH',
    bodyRegion: ['SHOULDER'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'PUSH_HORIZONTAL',
    tags: ['borst', 'push-up', 'beginner', 'revalidatie'],
    instructions: ['Sta een armlengte van de muur', 'Handen op schouderhoogte', 'Leun naar de muur en druk terug', 'Houd lichaam recht'],
    muscleLoads: { Borst: 2, Triceps: 2, 'Schouders anterieur': 2, Core: 1 },
  },
  {
    name: 'Incline Push-Up',
    description: 'Push-up met handen op verhoging. Ook hoge serratus anterior activatie — essentieel voor scapulaire stabiliteit [Kowalski 2022].',
    category: 'STRENGTH',
    bodyRegion: ['SHOULDER'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'PUSH_HORIZONTAL',
    tags: ['borst', 'push-up', 'beginner', 'serratus'],
    instructions: ['Handen op bank of verhoging', 'Lichaam in rechte lijn', 'Zak tot borst bij de bank', 'Druk omhoog'],
    muscleLoads: { Borst: 3, Triceps: 3, 'Schouders anterieur': 2, Core: 2 },
  },
  {
    name: 'Push-Up',
    description: 'Klassieke push-up. Triceps 73-109% MVIC, pectoralis major 95-105%, serratus anterior 67-87% [Kowalski 2022].',
    category: 'STRENGTH',
    bodyRegion: ['SHOULDER'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'PUSH_HORIZONTAL',
    tags: ['borst', 'push-up', 'lichaamsgewicht', 'compound'],
    instructions: ['Handen op schouderbreedte', 'Lichaam in rechte lijn', 'Zak tot borst bijna de grond raakt', 'Druk omhoog'],
    muscleLoads: { Borst: 4, Triceps: 4, 'Schouders anterieur': 3, Core: 3 },
  },
  {
    name: 'Narrow-Grip Push-Up',
    description: 'Push-up met smalle handpositie. Significant hogere triceps brachii en pectoralis major activatie [Cogley 2005].',
    category: 'STRENGTH',
    bodyRegion: ['SHOULDER'],
    difficulty: 'INTERMEDIATE',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'PUSH_HORIZONTAL',
    tags: ['borst', 'triceps', 'push-up', 'smalle grip'],
    instructions: ['Handen smaller dan schouderbreedte', 'Ellebogen langs het lichaam', 'Zak gecontroleerd', 'Druk omhoog'],
    muscleLoads: { Borst: 4, Triceps: 5, 'Schouders anterieur': 3, Core: 3 },
  },
  {
    name: 'Dumbbell Chest Press',
    description: 'Horizontale druk met dumbbells. Grotere ROM dan barbell, meer stabilisatie-eis.',
    category: 'STRENGTH',
    bodyRegion: ['SHOULDER'],
    difficulty: 'INTERMEDIATE',
    loadType: 'WEIGHTED',
    isUnilateral: false,
    movementPattern: 'PUSH_HORIZONTAL',
    tags: ['borst', 'dumbbells', 'drukken'],
    instructions: ['Lig op bank met dumbbells', 'Druk omhoog tot armen gestrekt', 'Laat gecontroleerd zakken'],
    muscleLoads: { Borst: 4, Triceps: 3, 'Schouders anterieur': 3 },
  },
  {
    name: 'Bench Press',
    description: 'Barbell bench press (flat, 0°). Optimaal voor sternocostale (midden) pectoralis major activatie [Rodríguez-Ridao 2020].',
    category: 'STRENGTH',
    bodyRegion: ['SHOULDER'],
    difficulty: 'INTERMEDIATE',
    loadType: 'WEIGHTED',
    isUnilateral: false,
    movementPattern: 'PUSH_HORIZONTAL',
    tags: ['borst', 'bench press', 'compound'],
    instructions: ['Lig op de bank, voeten op de grond', 'Barbell op borsthoogte', 'Laat zakken tot de borst', 'Druk omhoog tot volledige extensie'],
    muscleLoads: { Borst: 5, Triceps: 4, 'Schouders anterieur': 3 },
  },
  {
    name: 'Incline Bench Press',
    description: 'Schuine bankdrukken (30-44°). Optimaal voor claviculaire (bovenste) pectoralis major [Rodríguez-Ridao 2020]. Vermijd >45°: verschuift belasting naar anterieure deltoid.',
    category: 'STRENGTH',
    bodyRegion: ['SHOULDER'],
    difficulty: 'INTERMEDIATE',
    loadType: 'WEIGHTED',
    isUnilateral: false,
    movementPattern: 'PUSH_HORIZONTAL',
    tags: ['borst', 'incline', 'bovenborst'],
    instructions: ['Bank op 30 graden', 'Druk gewicht omhoog', 'Laat zakken tot borsthoogte'],
    muscleLoads: { Borst: 4, 'Schouders anterieur': 4, Triceps: 3 },
  },
  {
    name: 'Parallel Bar Dips',
    description: 'Compound dips op parallelle stangen. Vergelijkbare tot hogere pectoralis major activatie als flat bench press [McKenzie 2022]. Let op bij anterieure schouderinstabiliteit.',
    category: 'STRENGTH',
    bodyRegion: ['SHOULDER', 'ELBOW'],
    difficulty: 'INTERMEDIATE',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'PUSH_HORIZONTAL',
    tags: ['borst', 'triceps', 'dips', 'compound'],
    instructions: ['Steun op parallelle stangen', 'Zak tot 90° in ellebogen (lichte vooroverleun = meer borst)', 'Druk omhoog tot volledige extensie'],
    muscleLoads: { Borst: 5, Triceps: 5, 'Schouders anterieur': 3 },
  },
  {
    name: 'Dumbbell Fly',
    description: 'Isolatie-oefening voor pectoralis. Lagere pec-activatie dan bench press, maar betere stretch in eindpositie (stretch-mediated hypertrofie) [Solstad 2020].',
    category: 'STRENGTH',
    bodyRegion: ['SHOULDER'],
    difficulty: 'INTERMEDIATE',
    loadType: 'WEIGHTED',
    isUnilateral: false,
    movementPattern: 'PUSH_HORIZONTAL',
    tags: ['borst', 'isolatie', 'stretch'],
    instructions: ['Lig op bank met dumbbells boven borst', 'Lichte buiging in ellebogen', 'Open armen zijwaarts tot borstlijn', 'Breng terug in boogbeweging'],
    muscleLoads: { Borst: 4, 'Schouders anterieur': 2 },
  },
  {
    name: 'Cable Fly',
    description: 'Cable-variant van fly. Constante spanning door volledige ROM — voorkeur boven dumbbell fly voor pec-isolatie.',
    category: 'STRENGTH',
    bodyRegion: ['SHOULDER'],
    difficulty: 'INTERMEDIATE',
    loadType: 'MACHINE',
    isUnilateral: false,
    movementPattern: 'PUSH_HORIZONTAL',
    tags: ['borst', 'isolatie', 'kabel'],
    instructions: ['Sta tussen kabels op hoge/middelste stand', 'Lichte buiging in ellebogen', 'Breng handen samen voor je borst', 'Controleerde terugweg'],
    muscleLoads: { Borst: 4, 'Schouders anterieur': 2 },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // UPPER BODY — PUSH VERTICAL
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'Dumbbell Shoulder Press',
    description: 'Schouderpers met dumbbells (zittend of staand). Staand: hogere deltoïdeus activatie door extra stabilisatie, maar lagere 1-RM [Saeterbakken 2013].',
    category: 'STRENGTH',
    bodyRegion: ['SHOULDER'],
    difficulty: 'INTERMEDIATE',
    loadType: 'WEIGHTED',
    isUnilateral: false,
    movementPattern: 'PUSH_VERTICAL',
    tags: ['schouders', 'dumbbells', 'press'],
    instructions: ['Dumbbells op schouderhoogte', 'Druk omhoog tot armen gestrekt', 'Laat gecontroleerd zakken'],
    muscleLoads: { 'Schouders anterieur': 4, 'Schouders lateraal': 3, Triceps: 3, Core: 2 },
  },
  {
    name: 'Overhead Press',
    description: 'Staande barbell overhead press. Anterieure deltoid 33% MVIC — significant hoger dan bench press (5%) en fly (3.4%) [Coratella 2020].',
    category: 'STRENGTH',
    bodyRegion: ['SHOULDER'],
    difficulty: 'INTERMEDIATE',
    loadType: 'WEIGHTED',
    isUnilateral: false,
    movementPattern: 'PUSH_VERTICAL',
    tags: ['schouders', 'press', 'compound'],
    instructions: ['Barbell op sleutelbeenhoogte', 'Druk recht omhoog', 'Lock uit boven het hoofd', 'Laat gecontroleerd zakken'],
    muscleLoads: { 'Schouders anterieur': 5, 'Schouders lateraal': 3, Triceps: 4, Core: 3 },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // UPPER BODY — SHOULDER ISOLATION
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'Lateral Raise',
    description: 'Dumbbell lateral raise. Deltoïdeus medialis ~30.3% MVIC — significant hoger dan bench press/fly [Coratella 2020]. Vergelijkbaar met cable variant [Kassiano 2025].',
    category: 'STRENGTH',
    bodyRegion: ['SHOULDER'],
    difficulty: 'BEGINNER',
    loadType: 'WEIGHTED',
    isUnilateral: false,
    movementPattern: 'ISOLATION_UPPER',
    tags: ['schouders', 'lateraal', 'isolatie'],
    instructions: ['Dumbbells langs het lichaam', 'Hef zijwaarts tot schouderhoogte', 'Laat gecontroleerd zakken'],
    muscleLoads: { 'Schouders lateraal': 4, 'Schouders anterieur': 2 },
  },
  {
    name: 'Cable Lateral Raise',
    description: 'Cable lateral raise. Geen significant verschil in hypertrofie vs. dumbbell variant na 8 weken [Kassiano 2025]. Voordeel: constante spanning door ROM.',
    category: 'STRENGTH',
    bodyRegion: ['SHOULDER'],
    difficulty: 'BEGINNER',
    loadType: 'MACHINE',
    isUnilateral: true,
    movementPattern: 'ISOLATION_UPPER',
    tags: ['schouders', 'lateraal', 'isolatie', 'kabel'],
    instructions: ['Kabel op laagste stand, aan tegenovergestelde kant', 'Grijp handvat met verste hand', 'Hef zijwaarts tot schouderhoogte', 'Laat gecontroleerd terug'],
    muscleLoads: { 'Schouders lateraal': 4, 'Schouders anterieur': 2 },
  },
  {
    name: 'Face Pull',
    description: 'Kabel- of bandoefening voor achterste schouders en midden/onder trapezius. Combineert scapulaire retractie met externe rotatie.',
    category: 'STRENGTH',
    bodyRegion: ['SHOULDER'],
    difficulty: 'BEGINNER',
    loadType: 'BAND',
    isUnilateral: false,
    movementPattern: 'PULL_HORIZONTAL',
    tags: ['schouders', 'posterieur', 'band', 'scapulair'],
    instructions: ['Trek kabel/band naar gezicht', 'Houd ellebogen hoog', 'Knijp schouderbladen samen', 'Laat gecontroleerd terug'],
    muscleLoads: { 'Schouders posterieur': 4, Rotatorcuff: 3, Bovenrug: 3 },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // UPPER BODY — ROTATOR CUFF
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'External Rotation (band)',
    description: 'Staande schouder externe rotatie met band. Functioneel bewegingspatroon maar lagere infraspinatus-activatie dan sidelying variant.',
    category: 'STABILITY',
    bodyRegion: ['SHOULDER'],
    difficulty: 'BEGINNER',
    loadType: 'BAND',
    isUnilateral: true,
    movementPattern: 'ROTATION',
    tags: ['schouder', 'rotatorcuff', 'preventie', 'functioneel'],
    instructions: ['Elleboog 90 graden langs het lichaam (handdoek in oksel)', 'Draai onderarm naar buiten', 'Langzaam terug'],
    muscleLoads: { Rotatorcuff: 3, 'Schouders posterieur': 2 },
  },
  {
    name: 'Sidelying External Rotation',
    description: 'Infraspinatus 62% MVIC, teres minor 67% — HOOGSTE activatie van 7 geteste ER-oefeningen [Reinold 2004]. Gouden standaard voor geïsoleerde infraspinatus-versterking.',
    category: 'STABILITY',
    bodyRegion: ['SHOULDER'],
    difficulty: 'BEGINNER',
    loadType: 'WEIGHTED',
    isUnilateral: true,
    movementPattern: 'ROTATION',
    tags: ['schouder', 'rotatorcuff', 'infraspinatus', 'preventie'],
    instructions: ['Lig op de zij met bovenste arm', 'Elleboog 90° tegen het lichaam (handdoek)', 'Roteer onderarm omhoog tegen weerstand', 'Langzaam terug'],
    muscleLoads: { Rotatorcuff: 4, 'Schouders posterieur': 2 },
  },
  {
    name: 'Internal Rotation (band)',
    description: 'Schouder interne rotatie met weerstandsband. Subscapularis activatie.',
    category: 'STABILITY',
    bodyRegion: ['SHOULDER'],
    difficulty: 'BEGINNER',
    loadType: 'BAND',
    isUnilateral: true,
    movementPattern: 'ROTATION',
    tags: ['schouder', 'rotatorcuff', 'preventie', 'subscapularis'],
    instructions: ['Elleboog 90 graden langs het lichaam', 'Draai onderarm naar binnen', 'Langzaam terug'],
    muscleLoads: { Rotatorcuff: 3, 'Schouders anterieur': 2 },
  },
  {
    name: 'Prone Y-Raise',
    description: 'Prone Y-raise met externe rotatie. Onder trapezius 85-97% MVIC — BESTE oefening voor onder trap activatie [Cools 2007]. Onmisbaar bij scapulaire dyskinesie.',
    category: 'STABILITY',
    bodyRegion: ['SHOULDER', 'BACK'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'ISOLATION_UPPER',
    tags: ['schouder', 'scapulair', 'onder trapezius', 'y-raise'],
    instructions: ['Lig buik op bank of grond', 'Armen in Y-positie (45° boven hoofd, duimen omhoog)', 'Hef armen op met schouderbladen', 'Knijp onder trap bovenaan'],
    muscleLoads: { 'Schouders posterieur': 3, Bovenrug: 5, Rotatorcuff: 3 },
  },
  {
    name: 'Prone T-Raise',
    description: 'Prone T-raise (horizontale abductie). Posterieure deltoid 88% MVIC, midden deltoid 87% bij 100° + volle ER [Cools 2007].',
    category: 'STABILITY',
    bodyRegion: ['SHOULDER', 'BACK'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'ISOLATION_UPPER',
    tags: ['schouder', 'scapulair', 'posterior delt', 't-raise'],
    instructions: ['Lig buik op bank', 'Armen zijwaarts (T-vorm, duimen omhoog)', 'Hef armen tot schouderhoogte', 'Knijp schouderbladen samen'],
    muscleLoads: { 'Schouders posterieur': 5, Bovenrug: 4, Rotatorcuff: 3 },
  },
  {
    name: 'Prone W-Raise',
    description: 'Prone W-raise — combineert externe rotatie met retractie. Goede algehele scapulaire activatie.',
    category: 'STABILITY',
    bodyRegion: ['SHOULDER', 'BACK'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'ISOLATION_UPPER',
    tags: ['schouder', 'scapulair', 'w-raise'],
    instructions: ['Lig buik op bank', 'Armen in W-vorm, ellebogen 90°', 'Hef ellebogen omhoog, handen roteren mee', 'Knijp schouderbladen samen'],
    muscleLoads: { 'Schouders posterieur': 3, Bovenrug: 3, Rotatorcuff: 3 },
  },
  {
    name: 'YTWL Raises',
    description: 'Combinatie van Y-T-W-L posities voor complete scapulaire stabilisatie. Samen tonen hoogste onder trapezius activatie.',
    category: 'STABILITY',
    bodyRegion: ['SHOULDER', 'BACK'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'ISOLATION_UPPER',
    tags: ['schouder', 'scapulair', 'stabiliteit', 'combo'],
    instructions: ['Lig op je buik of leun voorover', 'Hef armen in Y-T-W-L posities', 'Knijp schouderbladen samen', '5-10 reps per positie'],
    muscleLoads: { 'Schouders posterieur': 4, Bovenrug: 4, Rotatorcuff: 3 },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // UPPER BODY — PULL HORIZONTAL
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'Inverted Row',
    description: 'Horizontaal roeien met lichaamsgewicht. Goede regressie voor pull-ups en als basis-rugoefening.',
    category: 'STRENGTH',
    bodyRegion: ['BACK'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'PULL_HORIZONTAL',
    tags: ['rug', 'row', 'lichaamsgewicht', 'beginner'],
    instructions: ['Hang onder een stang', 'Trek borst naar de stang', 'Houd lichaam in rechte lijn', 'Knijp schouderbladen samen'],
    muscleLoads: { Bovenrug: 4, Lats: 3, Biceps: 3, Core: 3, 'Schouders posterieur': 2 },
  },
  {
    name: 'Chest-Supported Row',
    description: 'Row met borstondersteuning. Vergelijkbare lat-activatie als bent-over row, maar significant LAGERE erector spinae belasting [Fenwick 2009]. Ideaal bij lage rugklachten.',
    category: 'STRENGTH',
    bodyRegion: ['BACK'],
    difficulty: 'BEGINNER',
    loadType: 'WEIGHTED',
    isUnilateral: false,
    movementPattern: 'PULL_HORIZONTAL',
    tags: ['rug', 'row', 'rug-vriendelijk', 'revalidatie'],
    instructions: ['Lig buik op incline bank', 'Dumbbells hangen naar beneden', 'Trek ellebogen naar heupen', 'Knijp schouderbladen samen'],
    muscleLoads: { Bovenrug: 4, Lats: 4, Biceps: 3, 'Schouders posterieur': 3 },
  },
  {
    name: 'Cable Row (zittend)',
    description: 'Zittende kabelroeibeweging. Narrow-grip: meer lats. Wide-grip: meer midden/onder trapezius, erector spinae [Lehman 2004].',
    category: 'STRENGTH',
    bodyRegion: ['BACK'],
    difficulty: 'BEGINNER',
    loadType: 'MACHINE',
    isUnilateral: false,
    movementPattern: 'PULL_HORIZONTAL',
    tags: ['rug', 'row', 'kabel'],
    instructions: ['Zit met rechte rug', 'Trek handvat naar de buik', 'Schouderbladen samentrekken', 'Gecontroleerd terug'],
    muscleLoads: { Bovenrug: 4, Lats: 4, Biceps: 3, Onderarmen: 2 },
  },
  {
    name: 'Dumbbell Row (single arm)',
    description: 'Unilaterale roeibeweging. Vrije gewichten activeren meer stabilisatoren (erector spinae, multifidus). Hoge multifidus-activatie [Fenwick 2009].',
    category: 'STRENGTH',
    bodyRegion: ['BACK'],
    difficulty: 'BEGINNER',
    loadType: 'WEIGHTED',
    isUnilateral: true,
    movementPattern: 'PULL_HORIZONTAL',
    tags: ['rug', 'row', 'unilateraal'],
    instructions: ['Eén hand en knie op bank', 'Trek dumbbell naar de heup', 'Knijp schouderblad samen', 'Geen rotatie van romp'],
    muscleLoads: { Bovenrug: 4, Lats: 4, Biceps: 3, 'Schouders posterieur': 3, Core: 3 },
  },
  {
    name: 'Barbell Row',
    description: 'Bent-over barbell row. Hoge erector spinae belasting door voorovergebogen positie.',
    category: 'STRENGTH',
    bodyRegion: ['BACK'],
    difficulty: 'INTERMEDIATE',
    loadType: 'WEIGHTED',
    isUnilateral: false,
    movementPattern: 'PULL_HORIZONTAL',
    tags: ['rug', 'row', 'compound'],
    instructions: ['Hinge voorover met rechte rug', 'Trek barbell naar de buik', 'Knijp schouderbladen samen', 'Laat gecontroleerd zakken'],
    muscleLoads: { Bovenrug: 5, Lats: 4, Biceps: 3, 'Schouders posterieur': 2, Onderarmen: 3, Onderrug: 4 },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // UPPER BODY — PULL VERTICAL
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'Lat Pulldown',
    description: 'Machine-variant van de pull-up. Geen significant verschil in lat-rekrutering tussen grip-variaties [Lehman 2004]. Pull-up is superieur voor lat-activatie.',
    category: 'STRENGTH',
    bodyRegion: ['BACK'],
    difficulty: 'BEGINNER',
    loadType: 'MACHINE',
    isUnilateral: false,
    movementPattern: 'PULL_VERTICAL',
    tags: ['rug', 'lats', 'machine'],
    instructions: ['Brede overhandse grip', 'Trek stang naar de borst', 'Houd borst omhoog', 'Laat gecontroleerd terug'],
    muscleLoads: { Lats: 4, Biceps: 3, Bovenrug: 3, Onderarmen: 2 },
  },
  {
    name: 'Assisted Pull-Up',
    description: 'Pull-up met band- of machine-assistentie. Regressie voor opbouw naar volledige pull-up.',
    category: 'STRENGTH',
    bodyRegion: ['BACK', 'SHOULDER'],
    difficulty: 'BEGINNER',
    loadType: 'MACHINE',
    isUnilateral: false,
    movementPattern: 'PULL_VERTICAL',
    tags: ['rug', 'pull-up', 'regressie'],
    instructions: ['Overhandse grip op stang', 'Gebruik band/machine voor assistentie', 'Trek kin boven stang', 'Laat gecontroleerd zakken'],
    muscleLoads: { Lats: 4, Biceps: 3, Bovenrug: 3, Onderarmen: 2 },
  },
  {
    name: 'Chin-Up',
    description: 'Pull-up met supinated grip. Hogere biceps brachii en pectoralis major activatie dan pull-up [Youdas 2010].',
    category: 'STRENGTH',
    bodyRegion: ['BACK', 'SHOULDER'],
    difficulty: 'INTERMEDIATE',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'PULL_VERTICAL',
    tags: ['rug', 'chin-up', 'biceps'],
    instructions: ['Onderhandse grip op schouderbreedte', 'Trek kin boven de stang', 'Nadruk op biceps'],
    muscleLoads: { Lats: 4, Biceps: 5, Bovenrug: 3, Borst: 3, Onderarmen: 3 },
  },
  {
    name: 'Pull-Up',
    description: 'Pull-up met pronated grip. Latissimus dorsi 117-130% MVIC (supramaximaal). Significant hogere lat-activatie dan lat pulldown [Youdas 2010].',
    category: 'STRENGTH',
    bodyRegion: ['BACK', 'SHOULDER'],
    difficulty: 'INTERMEDIATE',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'PULL_VERTICAL',
    tags: ['rug', 'pull-up', 'compound'],
    instructions: ['Overhandse grip op schouderbreedte', 'Trek kin boven de stang', 'Laat gecontroleerd zakken tot volle hang'],
    muscleLoads: { Lats: 5, Biceps: 4, Bovenrug: 4, Core: 3, Onderarmen: 3 },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // UPPER BODY — BICEPS
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'Hammer Curl',
    description: 'Neutrale grip curl. Lagere biceps brachii activatie, maar hogere brachialis en brachioradialis [Marcolin 2018]. Waardevol voor totale armomvang.',
    category: 'STRENGTH',
    bodyRegion: ['ELBOW'],
    difficulty: 'BEGINNER',
    loadType: 'WEIGHTED',
    isUnilateral: false,
    movementPattern: 'ISOLATION_UPPER',
    tags: ['biceps', 'brachialis', 'neutraal', 'hammer'],
    instructions: ['Dumbbells neutrale grip (duimen vooruit)', 'Buig ellebogen', 'Houd bovenarm stil', 'Laat gecontroleerd zakken'],
    muscleLoads: { Biceps: 3, Onderarmen: 4 },
  },
  {
    name: 'Reverse Curl',
    description: 'Curl met pronated grip. Hoogste brachioradialis activatie [Marcolin 2018]. Minder biceps brachii.',
    category: 'STRENGTH',
    bodyRegion: ['ELBOW', 'WRIST'],
    difficulty: 'BEGINNER',
    loadType: 'WEIGHTED',
    isUnilateral: false,
    movementPattern: 'ISOLATION_UPPER',
    tags: ['biceps', 'brachioradialis', 'reverse', 'onderarmen'],
    instructions: ['Pronated grip (handpalmen naar beneden)', 'Buig ellebogen', 'Focus op onderarm-activatie', 'Laat gecontroleerd zakken'],
    muscleLoads: { Biceps: 2, Onderarmen: 5 },
  },
  {
    name: 'Bicep Curl',
    description: 'Supinated grip curl met dumbbells. Traditionele biceps brachii oefening.',
    category: 'STRENGTH',
    bodyRegion: ['ELBOW'],
    difficulty: 'BEGINNER',
    loadType: 'WEIGHTED',
    isUnilateral: false,
    movementPattern: 'ISOLATION_UPPER',
    tags: ['biceps', 'isolatie', 'armen'],
    instructions: ['Dumbbells langs het lichaam, supinated grip', 'Buig de ellebogen omhoog', 'Houd bovenarm stil', 'Laat gecontroleerd zakken'],
    muscleLoads: { Biceps: 4, Onderarmen: 2 },
  },
  {
    name: 'EZ-Bar Curl',
    description: 'EZ-bar curl. Significant hogere biceps brachii EN brachioradialis activatie dan dumbbell curl. Ergonomischer (minder polsbelasting) [Marcolin 2018].',
    category: 'STRENGTH',
    bodyRegion: ['ELBOW'],
    difficulty: 'BEGINNER',
    loadType: 'WEIGHTED',
    isUnilateral: false,
    movementPattern: 'ISOLATION_UPPER',
    tags: ['biceps', 'ez-bar', 'pols-vriendelijk'],
    instructions: ['EZ-bar met supinated grip (grepen)', 'Buig ellebogen', 'Houd bovenarmen stil', 'Laat gecontroleerd zakken'],
    muscleLoads: { Biceps: 5, Onderarmen: 3 },
  },
  {
    name: 'Incline Dumbbell Curl',
    description: 'Curl op incline bank (~45°). Biceps brachii over grotere ROM met meer stretch — stretch-mediated hypertrofie [Oliveira 2009].',
    category: 'STRENGTH',
    bodyRegion: ['ELBOW'],
    difficulty: 'INTERMEDIATE',
    loadType: 'WEIGHTED',
    isUnilateral: false,
    movementPattern: 'ISOLATION_UPPER',
    tags: ['biceps', 'incline', 'stretch'],
    instructions: ['Zit op 45° incline bank', 'Dumbbells hangen recht naar beneden', 'Buig ellebogen zonder bovenarm te bewegen', 'Focus op de stretch in eindpositie'],
    muscleLoads: { Biceps: 5, Onderarmen: 2 },
  },
  {
    name: 'Preacher Curl',
    description: 'Curl op preacher bench. Hoge biceps activatie maar over een kort deel van ROM [Oliveira 2009].',
    category: 'STRENGTH',
    bodyRegion: ['ELBOW'],
    difficulty: 'INTERMEDIATE',
    loadType: 'WEIGHTED',
    isUnilateral: false,
    movementPattern: 'ISOLATION_UPPER',
    tags: ['biceps', 'preacher', 'isolatie'],
    instructions: ['Bovenarmen op preacher pad', 'Buig ellebogen tegen weerstand', 'Laat niet helemaal zakken (span behouden)', 'Knijp bovenaan'],
    muscleLoads: { Biceps: 5, Onderarmen: 3 },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // UPPER BODY — TRICEPS
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'Tricep Pushdown (kabel)',
    description: 'Rope pushdown. ~74% spieractivatie — hoogste voor laterale en mediale kop van de triceps [Boehler 2011].',
    category: 'STRENGTH',
    bodyRegion: ['ELBOW'],
    difficulty: 'BEGINNER',
    loadType: 'MACHINE',
    isUnilateral: false,
    movementPattern: 'ISOLATION_UPPER',
    tags: ['triceps', 'isolatie', 'kabel', 'laterale kop'],
    instructions: ['Sta voor de kabelmachine', 'Druk het touw/stang naar beneden', 'Houd ellebogen langs het lichaam', 'Volledige extensie'],
    muscleLoads: { Triceps: 4 },
  },
  {
    name: 'Skull Crusher',
    description: 'Lying triceps extension. ~62% spieractivatie [Boehler 2011].',
    category: 'STRENGTH',
    bodyRegion: ['ELBOW'],
    difficulty: 'INTERMEDIATE',
    loadType: 'WEIGHTED',
    isUnilateral: false,
    movementPattern: 'ISOLATION_UPPER',
    tags: ['triceps', 'skull crusher', 'isolatie'],
    instructions: ['Lig op bank met EZ-bar of dumbbells boven borst', 'Laat zakken richting voorhoofd', 'Houd bovenarmen stil', 'Strek ellebogen'],
    muscleLoads: { Triceps: 4, Borst: 1 },
  },
  {
    name: 'Tricep Dip',
    description: 'Dip op bank/stoel. Regressie voor parallel bar dips.',
    category: 'STRENGTH',
    bodyRegion: ['ELBOW', 'SHOULDER'],
    difficulty: 'INTERMEDIATE',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'PUSH_HORIZONTAL',
    tags: ['triceps', 'dip', 'bank'],
    instructions: ['Handen op bank achter je', 'Benen gestrekt of gebogen', 'Zak door ellebogen', 'Druk omhoog'],
    muscleLoads: { Triceps: 4, Borst: 2, 'Schouders anterieur': 3 },
  },
  {
    name: 'Overhead Triceps Extension',
    description: 'Overhead extension. Beste activatie van de LANGE KOP — 40% MEER tricepsgroei vs. pushdowns [Maeo 2023]. Stretch-mediated hypertrofie.',
    category: 'STRENGTH',
    bodyRegion: ['ELBOW'],
    difficulty: 'INTERMEDIATE',
    loadType: 'WEIGHTED',
    isUnilateral: false,
    movementPattern: 'ISOLATION_UPPER',
    tags: ['triceps', 'overhead', 'lange kop', 'stretch'],
    instructions: ['Dumbbell of EZ-bar boven hoofd', 'Laat zakken achter hoofd (ellebogen gebogen)', 'Strek armen omhoog', 'Focus op stretch in eindpositie'],
    muscleLoads: { Triceps: 5, 'Schouders anterieur': 2, Core: 2 },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // CORE — ANTERIOR
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'Crunch',
    description: 'Basis crunch. Matige rectus abdominis activatie — LAGER dan ab wheel en hanging varianten [Escamilla 2006].',
    category: 'STRENGTH',
    bodyRegion: ['LUMBAR'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'CORE',
    tags: ['core', 'crunch', 'beginner'],
    instructions: ['Lig op rug, knieën gebogen', 'Handen bij slapen', 'Rol schouders op (geen sit-up)', 'Laat gecontroleerd zakken'],
    muscleLoads: { Core: 3, 'Hip flexors': 1 },
  },
  {
    name: 'Sit-Up',
    description: 'Klassieke sit-up. Hogere activatie van bovenste/onderste rectus abdominis en externe obliquus dan straight leg raise [Escamilla 2006].',
    category: 'STRENGTH',
    bodyRegion: ['LUMBAR'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'CORE',
    tags: ['core', 'sit-up', 'beginner'],
    instructions: ['Lig op rug, voeten gefixeerd', 'Kom omhoog tot rechtop', 'Laat gecontroleerd zakken', 'Geen ruk in beweging'],
    muscleLoads: { Core: 3, 'Hip flexors': 3 },
  },
  {
    name: 'Dead Bug',
    description: 'Core-stabilisatie met extremiteitsbewegingen. Significante transversus abdominis activatie (#4 hollowing ranking). Minimale erector spinae — veilig bij lage rugpijn [Yoon 2024].',
    category: 'STABILITY',
    bodyRegion: ['LUMBAR'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'CORE',
    tags: ['core', 'stabiliteit', 'revalidatie', 'tva'],
    instructions: ['Lig op je rug, armen omhoog, knieën 90°', 'Strek tegenovergestelde arm en been', 'Houd onderrug plat op de grond', 'Wissel'],
    muscleLoads: { Core: 4, 'Hip flexors': 2 },
  },
  {
    name: 'Hollow Body Hold',
    description: 'Anti-extensie isometrische core. Rectus abdominis ~55-65% MVIC. Veilig voor patiënten met lumbale discuspathologie (geen herhaalde flexie) [McGill 2016].',
    category: 'STRENGTH',
    bodyRegion: ['LUMBAR'],
    difficulty: 'INTERMEDIATE',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'CORE',
    tags: ['core', 'isometrisch', 'anti-extensie'],
    instructions: ['Lig op rug, armen/benen gestrekt', 'Druk onderrug in de grond', 'Hef schouders en benen iets op (boot-vorm)', 'Houd positie vast'],
    muscleLoads: { Core: 4, 'Hip flexors': 3 },
  },
  {
    name: 'Cable Crunch',
    description: 'Cable crunch met progressieve belasting. Verhoogde rectus abdominis, externe obliquus en rectus femoris activatie vs. bodyweight [Moraes 2009].',
    category: 'STRENGTH',
    bodyRegion: ['LUMBAR'],
    difficulty: 'INTERMEDIATE',
    loadType: 'MACHINE',
    isUnilateral: false,
    movementPattern: 'CORE',
    tags: ['core', 'kabel', 'progressieve overload'],
    instructions: ['Kniel voor kabelmachine', 'Grijp touw naast hoofd', 'Rol schouders richting heupen (niet hoek in heupen)', 'Laat gecontroleerd terug'],
    muscleLoads: { Core: 5, 'Hip flexors': 2 },
  },
  {
    name: 'Reverse Crunch',
    description: 'Reverse crunch op incline (30°). Top-oefening voor ONDERSTE rectus abdominis regio [Escamilla 2006].',
    category: 'STRENGTH',
    bodyRegion: ['LUMBAR'],
    difficulty: 'INTERMEDIATE',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'CORE',
    tags: ['core', 'onderste abs', 'reverse'],
    instructions: ['Lig op rug of op incline bank', 'Knieën gebogen', 'Rol heupen/knieën richting borst', 'Laat gecontroleerd zakken'],
    muscleLoads: { Core: 4, 'Hip flexors': 3 },
  },
  {
    name: 'Hanging Knee Raise',
    description: 'Hanging knee-up. Top-3 rectus abdominis en interne obliquus activatie [Escamilla 2006]. Hoge grip-eis — gebruik straps indien nodig.',
    category: 'STRENGTH',
    bodyRegion: ['LUMBAR'],
    difficulty: 'INTERMEDIATE',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'CORE',
    tags: ['core', 'hanging', 'rectus abdominis'],
    instructions: ['Hang aan een pull-up stang', 'Hef knieën richting borst', 'Controleer omlaag', 'Geen schommel in beweging'],
    muscleLoads: { Core: 5, 'Hip flexors': 4, Onderarmen: 3 },
  },
  {
    name: 'Hanging Leg Raise',
    description: 'Hanging leg raise met gestrekte benen. Progressie van hanging knee raise — hogere overall activatie.',
    category: 'STRENGTH',
    bodyRegion: ['LUMBAR'],
    difficulty: 'ADVANCED',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'CORE',
    tags: ['core', 'hanging', 'gevorderd'],
    instructions: ['Hang aan een pull-up stang', 'Hef gestrekte benen tot 90°', 'Laat gecontroleerd zakken', 'Geen schommel'],
    muscleLoads: { Core: 5, 'Hip flexors': 5, Onderarmen: 3 },
  },
  {
    name: 'Ab Wheel Rollout',
    description: 'Anti-extensie ab wheel. Bovenste rectus abdominis 63% MVIC, externe/interne obliquus 46% — significant hoger dan meeste abdominale oefeningen [Escamilla 2006].',
    category: 'STRENGTH',
    bodyRegion: ['LUMBAR'],
    difficulty: 'ADVANCED',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'CORE',
    tags: ['core', 'anti-extensie', 'gevorderd'],
    instructions: ['Kniel met handen op het wiel', 'Rol vooruit met gestrekte armen', 'Houd core aangespannen (geen doorhangen)', 'Rol terug naar startpositie'],
    muscleLoads: { Core: 5, 'Schouders anterieur': 3, Lats: 3 },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // CORE — POSTERIOR / LATERAL / STABILIZATION
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'Bird Dog',
    description: 'McGill "Big Three". Transversus abdominis #1 in hollowing-oefeningen (grootste toename in spierdikte) [Yoon 2024]. Traint stabilisatie tegen rotatie + extensie.',
    category: 'STABILITY',
    bodyRegion: ['LUMBAR', 'BACK'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'CORE',
    tags: ['core', 'rug', 'stabiliteit', 'mcgill', 'tva'],
    instructions: ['Viervoetersstand', 'Strek tegenovergestelde arm en been', 'Houd romp stabiel (geen rotatie)', 'Wissel van kant'],
    muscleLoads: { Core: 5, Onderrug: 3, Glutes: 3, 'Schouders posterieur': 2 },
  },
  {
    name: 'Side Plank',
    description: 'McGill "Big Three" laterale stabilisatie. Externe obliquus hoog, Quadratus lumborum hoog (weinig oefeningen trainen QL effectief), Gluteus medius 3 [McGill 2016].',
    category: 'STABILITY',
    bodyRegion: ['LUMBAR'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: true,
    movementPattern: 'CORE',
    tags: ['core', 'lateraal', 'stabiliteit', 'mcgill', 'quadratus lumborum'],
    instructions: ['Lig op je zij op onderarm', 'Hef heupen omhoog (rechte lijn)', 'Houd positie vast', 'Wissel kant'],
    muscleLoads: { Core: 4, Abductoren: 4, Glutes: 3, 'Schouders lateraal': 2 },
  },
  {
    name: 'Plank',
    description: 'Anterior plank. Matige rectus abdominis, hoge transversus abdominis (vooral met hollowing: 22.7-106% rust vs. bracing 18.7-87.1%) [McGill 2016].',
    category: 'STABILITY',
    bodyRegion: ['LUMBAR'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'CORE',
    tags: ['core', 'plank', 'isometrisch'],
    instructions: ['Onderarmen en tenen op de grond', 'Lichaam in rechte lijn', 'Houd de positie vast', 'Niet laten doorzakken'],
    muscleLoads: { Core: 4, 'Schouders anterieur': 2, Onderrug: 2, Glutes: 2 },
  },
  {
    name: 'Pallof Press',
    description: 'Anti-rotation gouden standaard. Hoge transversus abdominis en obliquus activatie. Minimale compressieve spinale belasting — ideaal bij rugpijn-revalidatie.',
    category: 'STABILITY',
    bodyRegion: ['LUMBAR'],
    difficulty: 'INTERMEDIATE',
    loadType: 'BAND',
    isUnilateral: false,
    movementPattern: 'ROTATION',
    tags: ['core', 'anti-rotatie', 'stabiliteit', 'revalidatie'],
    instructions: ['Sta zijwaarts van het ankerpunt', 'Houd band/kabel tegen borst', 'Druk armen recht vooruit', 'Weersta de rotatie'],
    muscleLoads: { Core: 5, Onderrug: 2 },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // BACK EXTENSION
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'Back Extension (Roman Chair)',
    description: '45° hyper-extension. Erector spinae 76-79% MVIC [De Ridder 2015]. Hogere gluteus maximus (94-140% verschil) dan seated machine.',
    category: 'STRENGTH',
    bodyRegion: ['BACK', 'LUMBAR'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'HINGE',
    tags: ['rug', 'erector spinae', 'hyper'],
    instructions: ['Plaats heupen op pad, voeten gefixeerd', 'Laat bovenlichaam zakken', 'Strek tot neutrale rugpositie', 'Geen overstrekking'],
    muscleLoads: { Onderrug: 4, Glutes: 4, Hamstrings: 3 },
  },
  {
    name: 'Reverse Hyper',
    description: 'Reverse hyper. Biedt spinale decompressie (tractie) in excentrische fase. Gluteus maximus primair + hamstrings [De Ridder 2015].',
    category: 'STRENGTH',
    bodyRegion: ['BACK', 'HIP'],
    difficulty: 'INTERMEDIATE',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'HINGE',
    tags: ['rug', 'glutes', 'decompressie', 'hamstrings'],
    instructions: ['Lig buik op reverse hyper', 'Hef gestrekte benen omhoog', 'Knijp glutes bovenaan', 'Laat gecontroleerd zakken'],
    muscleLoads: { Glutes: 4, Hamstrings: 4, Onderrug: 4 },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // MOBILITY
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'Hip 90/90 Stretch',
    description: 'Heupmobilisatie in 90/90 positie voor interne en externe rotatie.',
    category: 'MOBILITY',
    bodyRegion: ['HIP'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: null,
    tags: ['heup', 'mobiliteit', 'stretch'],
    instructions: ['Zit met benen in 90/90 positie', 'Leun voorover over het voorste been', 'Wissel van kant'],
    muscleLoads: { 'Hip flexors': 3, Adductoren: 3, Glutes: 2 },
  },
  {
    name: 'World\'s Greatest Stretch',
    description: 'Dynamische full-body stretch voor opwarming.',
    category: 'MOBILITY',
    bodyRegion: ['HIP', 'BACK', 'SHOULDER'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: true,
    movementPattern: null,
    tags: ['opwarming', 'dynamisch', 'full-body'],
    instructions: ['Lunge positie', 'Draai romp naar het voorste been', 'Reik omhoog', 'Wissel van kant'],
    muscleLoads: { 'Hip flexors': 3, Adductoren: 2, Core: 2, Bovenrug: 2 },
  },
  {
    name: 'Cat-Cow Stretch',
    description: 'Wervelkolom mobiliteit in viervoetersstand.',
    category: 'MOBILITY',
    bodyRegion: ['BACK', 'LUMBAR', 'THORACIC'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: null,
    tags: ['rug', 'mobiliteit', 'opwarming'],
    instructions: ['Viervoetersstand', 'Hol de rug in (cow)', 'Bol de rug op (cat)', 'Beweeg langzaam door het bereik'],
    muscleLoads: { Core: 2, Onderrug: 2 },
  },
  {
    name: 'Thoracic Spine Rotation',
    description: 'Rotatiemobiliteit van de thoracale wervelkolom.',
    category: 'MOBILITY',
    bodyRegion: ['THORACIC'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: true,
    movementPattern: 'ROTATION',
    tags: ['thoracaal', 'rotatie', 'mobiliteit'],
    instructions: ['Zit of lig op je zij', 'Draai de bovenste arm open', 'Volg de hand met je ogen', 'Wissel van kant'],
    muscleLoads: { Bovenrug: 2, Core: 2 },
  },
  {
    name: 'Shoulder Dislocate (stok)',
    description: 'Schoudermobiliteit met een stok of band.',
    category: 'MOBILITY',
    bodyRegion: ['SHOULDER'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: null,
    tags: ['schouder', 'mobiliteit', 'stok'],
    instructions: ['Houd stok met brede grip', 'Beweeg in een boog over het hoofd naar achteren', 'Houd armen gestrekt'],
    muscleLoads: { 'Schouders anterieur': 2, 'Schouders posterieur': 2, Rotatorcuff: 3 },
  },
  {
    name: 'Ankle Dorsiflexion Mobilisation',
    description: 'Enkelmobiliteit tegen een muur.',
    category: 'MOBILITY',
    bodyRegion: ['ANKLE'],
    difficulty: 'BEGINNER',
    loadType: 'BODYWEIGHT',
    isUnilateral: true,
    movementPattern: null,
    tags: ['enkel', 'mobiliteit', 'dorsalflexie'],
    instructions: ['Voorste voet 10cm van de muur', 'Duw knie naar de muur voorbij de tenen', 'Houd hiel op de grond'],
    muscleLoads: { Calves: 3 },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // PLYOMETRICS
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'Broad Jump',
    description: 'Horizontale sprong voor power.',
    category: 'PLYOMETRICS',
    bodyRegion: ['KNEE', 'HIP'],
    difficulty: 'INTERMEDIATE',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'FULL_BODY',
    tags: ['springen', 'horizontaal', 'power'],
    instructions: ['Sta met voeten op schouderbreedte', 'Zwaai armen naar achteren', 'Spring zo ver mogelijk naar voren', 'Land zacht'],
    muscleLoads: { Quadriceps: 4, Glutes: 4, Hamstrings: 3, Calves: 3 },
  },
  {
    name: 'Countermovement Jump',
    description: 'Verticale sprong met tegenbeweging. Hoge activatie VL, VM, GAS. Na 6 weken plyo: +13.25% VL, +9.60% VM, +13.93% GAS [Ebben 2011].',
    category: 'PLYOMETRICS',
    bodyRegion: ['KNEE', 'HIP', 'ANKLE'],
    difficulty: 'INTERMEDIATE',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'FULL_BODY',
    tags: ['springen', 'verticaal', 'cmj', 'power'],
    instructions: ['Sta met voeten op schouderbreedte', 'Snelle kwart-squat naar beneden', 'Spring zo hoog mogelijk', 'Land zacht'],
    muscleLoads: { Quadriceps: 4, Glutes: 4, Hamstrings: 3, Calves: 4 },
  },
  {
    name: 'Box Jump',
    description: 'Explosieve sprong op een verhoging. Mid-range plyometrische belasting.',
    category: 'PLYOMETRICS',
    bodyRegion: ['KNEE', 'HIP', 'ANKLE'],
    difficulty: 'INTERMEDIATE',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'FULL_BODY',
    tags: ['explosief', 'springen', 'plyometrie'],
    instructions: ['Sta voor de box', 'Gebruik armen voor momentum', 'Spring omhoog en land zacht op de box', 'Stap terug naar beneden (niet springen)'],
    muscleLoads: { Quadriceps: 4, Glutes: 4, Calves: 3, Core: 3, Hamstrings: 3 },
  },
  {
    name: 'Depth Jump',
    description: 'Val van verhoging met direct-opnieuw-springen. Hoge reactieve krachten, korte grondcontacttijd.',
    category: 'PLYOMETRICS',
    bodyRegion: ['KNEE', 'HIP', 'ANKLE'],
    difficulty: 'ADVANCED',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'FULL_BODY',
    tags: ['plyometrie', 'reactief', 'gevorderd'],
    instructions: ['Stap van de box', 'Land en spring DIRECT omhoog', 'Minimale grondcontacttijd', 'Beheers de landing'],
    muscleLoads: { Quadriceps: 5, Calves: 5, Glutes: 4, Hamstrings: 4, Core: 3 },
  },
  {
    name: 'Hurdle Jump',
    description: 'HOOGSTE gluteus maximus activatie van alle sprongoefeningen [Ebben 2011]. Beste plyo voor GMax power-ontwikkeling.',
    category: 'PLYOMETRICS',
    bodyRegion: ['KNEE', 'HIP', 'ANKLE'],
    difficulty: 'ADVANCED',
    loadType: 'BODYWEIGHT',
    isUnilateral: false,
    movementPattern: 'FULL_BODY',
    tags: ['plyometrie', 'hurdle', 'glutes', 'gevorderd'],
    instructions: ['Plaats meerdere hurdles in rij', 'Spring met beide benen over hurdle', 'Minimale grondcontacttijd tussen hurdles', 'Land zacht en reactief'],
    muscleLoads: { Glutes: 5, Quadriceps: 4, Hamstrings: 4, Calves: 4, Core: 3 },
  },
  {
    name: 'Split Jump / Lunge Jump',
    description: 'Explosieve lunge met sprong en wissel.',
    category: 'PLYOMETRICS',
    bodyRegion: ['KNEE', 'HIP'],
    difficulty: 'INTERMEDIATE',
    loadType: 'BODYWEIGHT',
    isUnilateral: true,
    movementPattern: 'LUNGE',
    tags: ['plyometrie', 'lunge', 'explosief'],
    instructions: ['Start in lunge positie', 'Spring omhoog', 'Wissel benen in de lucht', 'Land zacht in lunge'],
    muscleLoads: { Quadriceps: 4, Glutes: 4, Hamstrings: 3, Calves: 3, 'Hip flexors': 3 },
  },
  {
    name: 'Crossover Jump',
    description: 'HOOGSTE gluteus medius activatie van sprongoefeningen [Ebben 2011]. Zijwaartse plyo voor laterale stabilisatie.',
    category: 'PLYOMETRICS',
    bodyRegion: ['KNEE', 'HIP'],
    difficulty: 'ADVANCED',
    loadType: 'BODYWEIGHT',
    isUnilateral: true,
    movementPattern: 'FULL_BODY',
    tags: ['plyometrie', 'lateraal', 'gmed', 'gevorderd'],
    instructions: ['Sta op één been', 'Spring zijwaarts en kruis over', 'Land op tegenovergesteld been', 'Beheers landing en spring terug'],
    muscleLoads: { Glutes: 5, Abductoren: 5, Quadriceps: 3, Calves: 3, Core: 3 },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // CARRIES
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'Farmer\'s Walk',
    description: 'Functioneel dragen van gewicht in beide handen.',
    category: 'STRENGTH',
    bodyRegion: ['FULL_BODY'],
    difficulty: 'BEGINNER',
    loadType: 'WEIGHTED',
    isUnilateral: false,
    movementPattern: 'CARRY',
    tags: ['carry', 'functioneel', 'grip'],
    instructions: ['Pak zwaar gewicht in elke hand', 'Loop met rechte houding', 'Schouders naar achteren', 'Strakke core'],
    muscleLoads: { Core: 4, Onderarmen: 5, 'Schouders lateraal': 3, Bovenrug: 3, Glutes: 2 },
  },
  {
    name: 'Suitcase Carry',
    description: 'Eenzijdig dragen voor anti-laterale flexie. Hoge QL + oblique activatie.',
    category: 'STRENGTH',
    bodyRegion: ['FULL_BODY'],
    difficulty: 'INTERMEDIATE',
    loadType: 'WEIGHTED',
    isUnilateral: true,
    movementPattern: 'CARRY',
    tags: ['carry', 'core', 'anti-lateraal'],
    instructions: ['Gewicht in één hand', 'Houd romp recht zonder zijwaarts leunen', 'Loop gecontroleerd'],
    muscleLoads: { Core: 5, Onderarmen: 4, Abductoren: 3, 'Schouders lateraal': 2 },
  },
]

export default STANDARD_EXERCISES
