export type AssessmentTestSeed = {
  key: string
  archetype: 'LUMBAR_SPINE' | 'SQUAT_HINGE' | 'PISTOL' | 'LUNGE' | 'THORACIC_SPINE' | 'OVERHEAD' | 'FRONT_RACK' | 'PRESS' | 'HANG' | 'BREATHING'
  testType: 'ACTIVE' | 'PASSIVE' | 'MOTOR_CONTROL' | 'BREATHING'
  name: string
  description: string
  criteria: string
  order: number
}

export const ASSESSMENT_TESTS: AssessmentTestSeed[] = [
  // FRONT RACK - ACTIVE
  {
    key: 'pvc-pipe-versus-barbell',
    archetype: 'FRONT_RACK',
    testType: 'ACTIVE',
    name: 'PVC Pipe Versus Barbell',
    description: 'Atleet staat rechtop met PVC-buis op de schouders, handen buiten schouderbreedte, neutrale pols en volledige grip. Test of de atleet front rack kan handhaven met onbelast materiaal of extra gewicht nodig is om door stijfheid te breken.',
    criteria: '• Volledige front rack archetype met PVC-buis mogelijk\n• Elbogen blijven minimaal parallel aan grond\n• Neutrale pols en grip behouden\n• Organisatie van wervelkolom zonder compensatie',
    order: 0,
  },
  {
    key: 'front-squat-motor-control',
    archetype: 'FRONT_RACK',
    testType: 'MOTOR_CONTROL',
    name: 'Front Squat Motor Control',
    description: 'Atleet staat met halter of dumbbells in front rack positie. Coach cueert atleet om stabiliteit in front rack te behouden tijdens front squat. Test controle van positie onder beweging en belasting.',
    criteria: '• Front rack archetype gehandhaafd: handen buiten schouders, neutrale pols\n• Bovenarmem parallel aan grond\n• Organisatie van wervelkolom zonder significante voorwaartse flexie\n• Geen elboogflexie onder parallel',
    order: 1,
  },
  {
    key: 'shoulder-external-rotation-passive',
    archetype: 'FRONT_RACK',
    testType: 'PASSIVE',
    name: 'Shoulder External Rotation Passive',
    description: 'Atleet ligt in ruglig, schouder 90° uit lichaam, elleboog 90° gebogen. Coach handhaaft humeruskop en passief roteert schouder extern door handrugzijde naar grond te brengen tot eerste weerstand (R1) en einde bereik (R2).',
    criteria: '• Minimaal 90° externe rotatie mogelijk tot voorarm raakt grond\n• Minimale weerstand in bewegingsbereik\n• Geen anterior translatie van humeruskop\n• Geen apprehension of instabiliteitsgevoel',
    order: 2,
  },
  {
    key: 'supine-front-rack-passive',
    archetype: 'FRONT_RACK',
    testType: 'PASSIVE',
    name: 'Supine Front Rack Passive',
    description: 'Atleet in ruglig, schouder 90° horizontaal adduksie, elleboog 90° gebogen. Coach passief extern roteert schouder naar front rack positie, assesses rotatie van voorarm weg van middellijn.',
    criteria: '• Rotatie gelijk of groter dan 90° externe rotatie mogelijk\n• Voorarm verticaal of voorbij verticaal positionerbaar\n• Schouder blijft tegen grond zonder anterior translatieén\n• Geen compensatoire zijwaartse buiging romp',
    order: 3,
  },
  // HANG - MOTOR CONTROL
  {
    key: 'cuban-rotation-progression',
    archetype: 'HANG',
    testType: 'MOTOR_CONTROL',
    name: 'Cuban Rotation Progression',
    description: 'Atleet start in ruglig met lichte dumbbells, cueert actieve interne rotatie schouders terwijl contact met tafel behouden blijft. Progressie: staand tegen muur, vrijstaand zonder feedback.',
    criteria: '• Actieve controle interne rotatie van schouders door volledige bereik\n• Centration van schoudergewricht gehandhaafd\n• Inspiratie bij daling naar interne rotatie, expiratie bij terugkeer\n• Geen anterieure translatie schouders',
    order: 0,
  },
  {
    key: 'supine-internal-rotation-active-passive',
    archetype: 'HANG',
    testType: 'ACTIVE',
    name: 'Supine Internal Rotation Active and Passive',
    description: 'Atleet in ruglig, schouder 90° uit lichaam, elleboog 90° gebogen. Atleet activeert interne rotatie van schouder, coach stabiliseert en passief roteert intern, assesses bewegingsbereik en translatie.',
    criteria: '• 70° interne rotatie actief en passief mogelijk\n• Voorarm kan naar trunksniveau rotatie\n• Schouder blijft geapproximeerd op lichaam\n• Geen anterieure translatie in actieve test',
    order: 1,
  },
  // HIP-SQUAT / LUMBAR_SPINE
  {
    key: 'neutral-spine-squat-test',
    archetype: 'SQUAT_HINGE',
    testType: 'ACTIVE',
    name: 'Neutral Spine Squat Test',
    description: 'Atleet staat met voeten schouderbreedte uit elkaar. Coach cueert atleet squat met heupvouw minimaal onder knieniveau. Test behoud van neutrale wervelkolom positie, stabiliteit voet en rotatie stabiliteit onderste extremiteit.',
    criteria: '• Neutrale wervelkolom zonder flexie of extensie gehandhaafd\n• Heupvouw onder knieniveau bereikt\n• 3-punts druk voet behouden, geen pronatie\n• Knie boven teen, geen valgus of varus compensatie',
    order: 0,
  },
  {
    key: 'squat-motor-control-categories',
    archetype: 'SQUAT_HINGE',
    testType: 'MOTOR_CONTROL',
    name: 'Squat Motor Control Categories',
    description: 'Atleet voert squat uit in 3 categorieën: langzaam tempo, snel vallen naar diepte, sprong uit kneeling. Test of mechanica consistent blijft onder verschillende snelheden en complexiteit.',
    criteria: '• Mechanica identiek in alle 3 categorieën\n• Neutrale wervelkolom behouden bij snelle beweging\n• 3-punts druk voet consistent\n• Geen valgus compensatie onder belasting of tempo',
    order: 1,
  },
  {
    key: 'hip-hinge-motor-control',
    archetype: 'SQUAT_HINGE',
    testType: 'MOTOR_CONTROL',
    name: 'Hip Hinge Motor Control',
    description: 'Atleet staat met voeten onder heupen. Coach cueert heupbisschop. Test behoud van organisatie wervelkolom, ademhaling en 3-punts druk voet bij excentrische heupextensie.',
    criteria: '• Werkelkolom organisatie gehandhaafd door beweging\n• Excentrische heupextensie met gluteale en hamstring belasting\n• Ademhaling gecoördineerd voor stabiliteit\n• Knie boven enkel, voetdruk anterior gehandhaafd',
    order: 2,
  },
  {
    key: 'lateral-lunge-active',
    archetype: 'SQUAT_HINGE',
    testType: 'ACTIVE',
    name: 'Lateral Lunge',
    description: 'Atleet staat met voeten schouder-wijd uit elkaar. Coach cueert atleet naar beide zijden minimaal parallel buigen. Test mobiliteit adductoren en stabiliteit werkelkolom.',
    criteria: '• Organisatie werkelkolom zonder flexie of extensie\n• Heupvouw onder knie bereikt bilateraal\n• 3-punts voetdruk gehandhaafd\n• Geen genu valgum compensatie',
    order: 3,
  },
  {
    key: 'supine-straight-leg-raise',
    archetype: 'SQUAT_HINGE',
    testType: 'ACTIVE',
    name: 'Supine Straight Leg Raise',
    description: 'Atleet in ruglig, beide benen gestrekt. Coach cueert atleet voet omhoog te tillen met dorsiflexie en gestrekt knie tot significante stijfheid in achterzijde. Test sciatiuszenuw mobiliteit en wervelkolom stabiliteit.',
    criteria: '• Neutrale werkelkolom zonder verandering door test\n• Knie gestrekt gehandhaafd\n• Heup 90° flexie bereikt\n• Contralaterale been plat op grond',
    order: 4,
  },
  {
    key: '90-90-hamstring-passive',
    archetype: 'SQUAT_HINGE',
    testType: 'PASSIVE',
    name: '90/90 Hamstring Muscle Passive',
    description: 'Atleet in ruglig. Coach passief flexeert heup voorbij 90°, dan passief kniest. Test hamstring spier flexibiliteit.',
    criteria: '• Knie volledig extensie mogelijk met knie haaks op grond\n• Minimale weerstand in bewegingsbereik\n• Been bijna gestrekt bereikbaar\n• Geen compensatoire werkelkolom extensie nodig',
    order: 5,
  },
  {
    key: 'hip-flexion-passive',
    archetype: 'SQUAT_HINGE',
    testType: 'PASSIVE',
    name: 'Hip Flexion Passive',
    description: 'Atleet in ruglig. Coach passief flexeert heup, dij recht omhoog naar borst. Assesses heupflexiebereik en impingement.',
    criteria: '• Dij raakt romp mogelijk\n• Heupflexie minimaal 120° bereikt\n• Geen inpingement gevoel in heupvoorkant\n• Geen rotatie compensatie nodig',
    order: 6,
  },
  {
    key: 'hip-external-rotation-passive',
    archetype: 'SQUAT_HINGE',
    testType: 'PASSIVE',
    name: 'Hip External Rotation Passive',
    description: 'Atleet in ruglig, heup 90° flexie. Coach passief extern roteert heup. Test externe rotatiecapaciteit van heup.',
    criteria: '• Minimaal 45° externe rotatie bereikt\n• Tot 90° externe rotatie mogelijk in goede mobiliteit\n• Gecombineerd rotatievenster gelijk of groter dan 90°\n• Musculaire stretch gevoeld aan einde bereik',
    order: 7,
  },
  {
    key: 'hip-internal-rotation-passive',
    archetype: 'SQUAT_HINGE',
    testType: 'PASSIVE',
    name: 'Hip Internal Rotation Passive',
    description: 'Atleet in ruglig, heup 90° flexie. Coach passief intern roteert heup. Test interne rotatiecapaciteit en gecombineerd rotatievenster.',
    criteria: '• Minimaal 30° interne rotatie bereikt\n• Compleet bereik tot 45° mogelijk\n• Gecombineerd rotatievenster gelijk of groter dan 90°\n• Geen abrupte hard stop zonder musculaire fase',
    order: 8,
  },
  {
    key: 'fms-tandem-ankle-dorsiflexion-hip-squat',
    archetype: 'SQUAT_HINGE',
    testType: 'ACTIVE',
    name: 'FMS Tandem Ankle Dorsiflexion',
    description: 'Atleet in tandemstand, voeten hakvoet-teen uitgelijnd. Coach cueert atleet beide knieën en enkels te buigen terwijl beide voeten plat blijven. Test enkelmobiliteit en voetdruk controle.',
    criteria: '• Achterknie dorsiflexie gelijk aan voorste knie of voorbij mediale malleolus\n• Beenrotatie behouden met knie in rechte lijn\n• Voetbogen en 3-punts druk gehandhaafd\n• Geen achterste hakhemel tillen',
    order: 9,
  },
  // LUNGE - ACTIVE
  {
    key: '3-position-couch-stretch',
    archetype: 'LUNGE',
    testType: 'ACTIVE',
    name: '3 Position Couch Stretch',
    description: 'Atleet knieschijf op pad, scheenbeen verticaal tegen muur. Progressie door 3 posities: voetvoorkant grond, voetvoorkant omhoog, verticale romp. Test achterheupmobiliteit en differentiatie stijfheid bronnen.',
    criteria: '• Heup in rechte lijn van enkel tot schouder in elke positie\n• Volledig gluteale en abdominale engagement\n• 3 volledige diepe adembewegingen tolerabel\n• Geen compensatoire werkelkolom extensie',
    order: 0,
  },
  {
    key: 'knee-down-squat',
    archetype: 'LUNGE',
    testType: 'ACTIVE',
    name: 'Knee Down Squat',
    description: 'Atleet in squat diepte. Coach cueert atleet ene knie naar grond plaatsen, voetbal op grond houdend. Test 1ste MTP extensie en voetdruk.',
    criteria: '• 1ste MTP dorsiflexie tot 90° bereikt\n• Voetbal op grond behouden\n• Groot tehalignment behouden, geen rotatie',
    order: 1,
  },
  {
    key: 'upright-lunge-motor-control',
    archetype: 'LUNGE',
    testType: 'MOTOR_CONTROL',
    name: 'Upright Lunge Motor Control',
    description: 'Atleet start in longe positie met rechtop romp. Coach cueert atleet recht omlaag te zakken zover mogelijk. Test stabiliteit heupextensie, romp organisatie en kniepositionering.',
    criteria: '• Rechtop organisatie werkelkolom gehandhaafd\n• Heup recht omlaag beweging\n• Achterknie op grond mogelijk\n• Voetdruk over voetbal gehandhaafd',
    order: 2,
  },
  {
    key: 'prone-heel-to-butt-passive',
    archetype: 'LUNGE',
    testType: 'PASSIVE',
    name: 'Prone Heel to Butt Passive',
    description: 'Atleet in buiklig. Coach passief kniet flectie en brengt hiel naar billen. Assesses knie flectie bereik zonder compensatie.',
    criteria: '• Hiel tot billen mogelijk, minder dan vuist afstand\n• Geen passieve heupflexie compensatie\n• Geen passieve werkelkolom extensie of rotatie\n• Spier stretch voelbaar aan einde bereik',
    order: 3,
  },
  {
    key: 'prone-1st-toe-extension-passive',
    archetype: 'LUNGE',
    testType: 'PASSIVE',
    name: 'Prone 1st Toe Extension Passive',
    description: 'Atleet in buiklig, knie 90° flexie. Coach passief groot teen extensie. Test groot teen extensie bereik en plantaire fascia mobiliteit.',
    criteria: '• 90° groot teen extensie bereikt\n• Minimale weerstand door bewegingsbereik\n• Geen pijnlijkheid onder voetbal\n• Geen pijn voettopgewricht',
    order: 4,
  },
  // OVERHEAD
  {
    key: 'dumbbell-overhead-hold',
    archetype: 'OVERHEAD',
    testType: 'ACTIVE',
    name: 'Dumbbell Overhead Hold',
    description: 'Atleet staat met dumbbells in overhead press positie. Coach observeert positurale controle. Test schouder mobiliteit en spinale organisatie onder belasting.',
    criteria: '• Organisatie werkelkolom behouden\n• Voorarmmen en bovenarmmen verticaal\n• Volledige schouder overhead mobiliteit\n• Dumbbells in rechte lijn boven schoudergewricht',
    order: 0,
  },
  {
    key: 'dumbbell-see-saw-press',
    archetype: 'OVERHEAD',
    testType: 'MOTOR_CONTROL',
    name: 'Dumbbell See-Saw Press',
    description: 'Atleet staat met dumbbells overhead. Coach cueert atleet één dumbbell naar persbegin loweren, dan terug omhoog. Herhaald afwisselend. Test excentrische controle externe rotatie en dynamische romp organisatie.',
    criteria: '• Overhead hold positie behouden met ene of beide gewichten\n• Elleboog in lijn met pols en schouder bij excentrische fase\n• Knuckles verticaal gehandhaafd\n• Spinale organisatie behouden zonder extensie compensatie',
    order: 1,
  },
  {
    key: 'standing-overpressure-passive',
    archetype: 'OVERHEAD',
    testType: 'PASSIVE',
    name: 'Standing Overpressure Passive',
    description: 'Atleet staat. Coach grijpt onderarm en stabiliseert elleboog. Coach passief beweegt atleet in overhead positie door naar oor te drukken.',
    criteria: '• Minimale weerstand door bewegingsbereik\n• Coach kan volledige overhead positie bereiken zonder pijn\n• Geen significante "unwinding" naar interne rotatie\n• Geduldig einde bereik gevoel',
    order: 2,
  },
  {
    key: 'supine-overpressure-passive',
    archetype: 'OVERHEAD',
    testType: 'PASSIVE',
    name: 'Supine Overpressure Passive',
    description: 'Atleet in ruglig. Coach grijpt boven en onder elleboog, passief flexeert schouder overhead. Coach assesses bereik en spinale compensatie.',
    criteria: '• Arm in contact met grond in overhead positie bereikbaar\n• Werkelkolom neutraal en ontspannen blijvend\n• Minimale "unwinding" naar interne rotatie\n• Geen extensie compensatie van romp',
    order: 3,
  },
  {
    key: 'prone-pvc-pipe-lift-off',
    archetype: 'OVERHEAD',
    testType: 'ACTIVE',
    name: 'Prone PVC Pipe Lift-Off',
    description: 'Atleet in buiklig, armen overhead, PVC-buis in duimen. Coach cueert atleet handen van grond te tillen. Test schouder mobiliteit en bewegingssequentie.',
    criteria: '• Scapulamotie eerst omlaag naar rug\n• Ellebogen gestrekt behouden\n• Duidelijke scheiding van grond bereikt\n• Overhead mechanica goed uitgedrukt',
    order: 4,
  },
  // PISTOL
  {
    key: 'feet-together-squat',
    archetype: 'PISTOL',
    testType: 'ACTIVE',
    name: 'Feet Together Squat',
    description: 'Atleet staat met voeten samen, knieën samen. Coach cueert atleet zover mogelijk te squat. Test enkelmobiliteit en rotatie stabiliteit in beperkte positie.',
    criteria: '• Organisatie werkelkolom gehandhaafd\n• Volledige diepte tot bil-enkel bereikt mogelijk\n• 3-punts voetdruk gehandhaafd\n• Rotatie alignment voet en knie gelijk',
    order: 0,
  },
  {
    key: 'pistol-and-box-step-down',
    archetype: 'PISTOL',
    testType: 'MOTOR_CONTROL',
    name: 'Pistol and Box Step-Down',
    description: 'Atleet stands op één voet (of box), tegengestelde voet opgetild. Coach cueert atleet op één been te squat. Test enkel mobiliteit, heupstabiliteit en rotatie controle.',
    criteria: '• Organisatie werkelkolom gehandhaafd door diepte\n• Volledige diepte bil-enkel bereikbaar\n• 3-punts voetdruk gehandhaafd\n• Knie in lijn van enkel zonder varus compensatie',
    order: 1,
  },
  {
    key: 'prone-ankle-dorsiflexion-passive',
    archetype: 'PISTOL',
    testType: 'PASSIVE',
    name: 'Prone Ankle Dorsiflexion Passive',
    description: 'Atleet in buiklig. Coach buigt knie 90°, passief dorsiflexeert enkel. Assesses dorsaal flectie bereik en voetboogstabiliteit.',
    criteria: '• Minimaal 20° dorsiflexie bereikt, tot 30° mogelijk\n• Voet recht gehandhaafd in scheenbeenvlak\n• Neutrale voetboog positie\n• Geen arch collapse of rotatie compensatie',
    order: 2,
  },
  {
    key: 'fms-tandem-ankle-dorsiflexion-pistol',
    archetype: 'PISTOL',
    testType: 'ACTIVE',
    name: 'FMS Tandem Ankle Dorsiflexion Pistol',
    description: 'Atleet in tandemstand, voeten hakvoet-teen uitgelijnd. Coach cueert atleet beide knieën en enkels te buigen terwijl beide voeten plat blijven. Test enkelmobiliteit en voetdruk controle.',
    criteria: '• Achterknie dorsiflexie gelijk aan voorste knie of voorbij mediale malleolus\n• Beenrotatie behouden met knie in rechte lijn\n• Voetbogen en 3-punts druk gehandhaafd\n• Geen achterste hakhemel tillen',
    order: 3,
  },
  // PRESS
  {
    key: 'fist-release-push-up',
    archetype: 'PRESS',
    testType: 'ACTIVE',
    name: 'Fist Release Push-Up',
    description: 'Atleet in buiklig, borst op grond, knuckels op grond, elleboog direct boven vuisten. Coach cueert atleet vuisten recht omhoog te tillen.',
    criteria: '• Schouders recht omhoog extensie mogelijk\n• Duidelijke scheiding knuckels van grond\n• Geen elleboog flare compensatie\n• Geen schouder shrug of nekextensie',
    order: 0,
  },
  {
    key: 'ring-push-up-motor-control',
    archetype: 'PRESS',
    testType: 'MOTOR_CONTROL',
    name: 'Ring Push-Up Motor Control',
    description: 'Atleet in push-up positie op ringen 1-2 inch boven grond. Coach cueert atleet push-up uit te voeren zover mogelijk met controle. Test spinale organisatie en schouder stabiliteit onder beweging.',
    criteria: '• Spinale organisatie behouden zonder lumbaale extensie of flexie\n• Initiatieert beweging met romp voorwaarts\n• Elleboog verticaal boven ring in laagste positie\n• Ademhaling gecoördineerd: inhalatie omlaag, exhalatie omhoog',
    order: 1,
  },
  {
    key: 'ring-row-press',
    archetype: 'PRESS',
    testType: 'MOTOR_CONTROL',
    name: 'Ring-Row Press',
    description: 'Atleet staat, grijpt ringen taille-hoogte. Atleet loopt lichaam onder ringen tot schouders direct onder. Coach cueert atleet zelf naar ringen te trekken en gecontroleerd terug te laten zakken.',
    criteria: '• Spinale organisatie gehandhaafd door beweging\n• Schouder rotatie met elleboog en pols in vlak\n• Initiatie met schouder naar lichaam, niet elleboog flexie\n• Scapulamobilisatie gehandhaafd tot bottom positie',
    order: 2,
  },
  {
    key: 'standing-pvc-pipe-extension',
    archetype: 'PRESS',
    testType: 'ACTIVE',
    name: 'Standing PVC Pipe Extension',
    description: 'Atleet staat met PVC-buis achter heupen, volledige grip, palmen vooruit. Coach cueert atleet buis zover achter zich mogelijk te heffen met armen recht.',
    criteria: '• Actief schouder extensie tot 90° parallel mogelijk\n• Rechtop spinale organisatie behouden\n• Armen gestrekt, polsen neutraal\n• Geen spinale flexie compensatie',
    order: 3,
  },
  // THORACIC_SPINE
  {
    key: 'hollow-body-hold',
    archetype: 'THORACIC_SPINE',
    testType: 'MOTOR_CONTROL',
    name: 'Hollow Body Hold',
    description: 'Atleet in ruglig. Coach cueert atleet hoofd en bovenrug op te tillen, dan benen, dan sacrum. Test globale spinale flexie controle en respiratoire coördinatie.',
    criteria: '• Globale spinale flexie positie aangenomen\n• Diafragmatische ademhaling gehandhaafd in positie\n• Geen "breath hold" stabilisatiepatroon\n• Spanning behouden zonder pijn',
    order: 0,
  },
  {
    key: 'jefferson-curl',
    archetype: 'THORACIC_SPINE',
    testType: 'MOTOR_CONTROL',
    name: 'Jefferson Curl',
    description: 'Atleet staat. Coach cueert atleet voorover te flexeren beginnend met hoofd-op-nek, segmenteel door werkelkolom van boven naar beneden, dan terug in omgekeerde richting.',
    criteria: '• Elke spinale segment flexeert gelijkmatig\n• Symmetrische curve zonder lokale scharnierpunten\n• Geen pijn bij beweging\n• Vloeiiende beweging zonder "blocks" in mobiliteit',
    order: 1,
  },
  {
    key: 'prone-breathing-active-passive',
    archetype: 'THORACIC_SPINE',
    testType: 'ACTIVE',
    name: 'Prone Breathing Active and Passive',
    description: 'Atleet in buiklig. Coach cueert atleet diepe ademhalingen te nemen, observeert beweging. Coach bevestigt palpatie thoracale spinale beweging.',
    criteria: '• Duidelijke stijging en daling thoracale werbelkolom zichtbaar\n• Diafragmatische ademhaling initiatie\n• Laterale ribkasmobiliteit\n• Geen gecompenseerde accessoire ademhalingspat',
    order: 2,
  },
  {
    key: 'superman-hold',
    archetype: 'THORACIC_SPINE',
    testType: 'MOTOR_CONTROL',
    name: 'Superman Hold',
    description: 'Atleet in buiklig. Coach cueert atleet hoofd en bovenrug op te tillen, dan benen op te tillen in globale spinale extensie. Test globale extensie controle en gluteale activatie.',
    criteria: '• Globale spinale extensie positie aangenomen\n• Gluteale en abdominale spieren gebrukt voor organizatie\n• Diafragmatische ademhaling gehandhaafd\n• Geen "breath hold" stabilisatiepatroon',
    order: 3,
  },
  // BREATHING
  {
    key: '20-breath-plank-hold-test',
    archetype: 'BREATHING',
    testType: 'BREATHING',
    name: '20 Breath Plank Hold Test',
    description: 'Atleet in plank positie op handen. Atlanthaalt door neus 4 seconden, exhaleert 2 seconden. Totaal 20 ademhalingen (2 minuten). Test spinale organisatie en respiratoire controle onder belasting.',
    criteria: '• Plank positie 20 ademhalingen volgehouden\n• Werkelkolom organisatie gehandhaafd\n• Inhalatie neus 4 sec, exhalatie mond 2 sec gehandhaafd\n• Geen lumbaale extensie compensatie',
    order: 0,
  },
  {
    key: 'flinch-test-spinal-bracing',
    archetype: 'BREATHING',
    testType: 'BREATHING',
    name: 'Flinch Test of Spinal Bracing',
    description: 'Atleet in ruglig met benen gestrekt. Op "Go" cue tildt atleet benen 2 inch snel op. Coach observeert stabiliteitssequentie en spinale beweging.',
    criteria: '• Romp organiseert snel voor beenheffen\n• Benen heffen zonder spinale positieveuganding\n• Comfortabele ademhaling tolerabel zonder beenverlies\n• Geen breath-hold of abdominal flinch patroon',
    order: 1,
  },
  {
    key: 'plank-shear-test',
    archetype: 'BREATHING',
    testType: 'BREATHING',
    name: 'Plank Shear Test',
    description: 'Atleet in plank positie. Coach plaatst palmhakken zijwaarts op lage rug, langzaam druk opbouwend. Test spinale stabiliteit onder afschuifbelasting.',
    criteria: '• Neutraal spinale positie behouden\n• Schouders stabiliteit naar grond, gluteale activatie\n• Constante neus-inhalatie ademhaling\n• Geen lumbaale extensie compensatie',
    order: 2,
  },
  {
    key: 'supine-breathing-assessment',
    archetype: 'BREATHING',
    testType: 'BREATHING',
    name: 'Supine Breathing Assessment',
    description: 'Atleet in ruglig, ontspannen. Coach cueert diepademing. Test diafragmatische functie en ribkasmobiliteit. Passieve plaatsing hand op buik en borst bevestigt ademhaling patroon.',
    criteria: '• Inhalatie neus\n• 360° expansie onderste romp en ribkasten\n• Laterale ribkasmobiliteit\n• Gladde sequentie zonder stokkering of compensatie\n• Snelle en volledige exhalatie via mond',
    order: 3,
  },
]
