export const ACHILLES_RUPTURE_PROTOCOL = {
  protocol: {
    key: 'achillespees-ruptuur-postop',
    name: 'Achillespeesreparatie (Post-op) — Criteria-Based Revalidatie',
    description: 'Protocol voor postoperatieve revalidatie na chirurgische reparatie van complete achillespeesruptuur. Collageen rijping duurt 12-16 weken; volledige mechanische integriteit na 6-12 maanden.',
    specialty: 'achilles_rupture',
    sourceReference: 'Movement Based Therapy Amsterdam (2026). Criteria-Based Revalidatieprotocol: Chirurgische Achillespeesreparatie.',
  },
  phases: [
    {
      order: 0,
      shortName: 'Pre-op',
      name: 'Pre-operatieve Fase — Gereed voor Operatie',
      description: 'Baseline meetwaarden vastleggen van contralaterale zijde en patiënteducatie over biologisch genezingsproces.',
      keyGoals: ['Baseline referentiewaarden vastleggen', 'Patiënteducatie genezingsproces', 'Psychologische voorbereiding'],
      typicalStartWeek: -2,
      typicalEndWeek: 0,
      criteria: [
        { name: 'Goniometrie enkel (contralateraal)', testDescription: 'Passieve ROM dorsaalflexie en plantairflexie van niet-aangedane zijde met universele goniometer.', reference: 'Norkin & White (2016), ICC 0.90-0.98', targetValue: 'Vastleggen als referentie', targetUnit: 'graden', inputType: 'NUMERIC', isBonus: false },
        { name: 'Single Leg Calf Raise (contralateraal)', testDescription: 'Maximaal aantal herhalingen op niet-aangedane been op trede, tempo 1 per 2 sec.', reference: 'Hébert-Losier et al. (2009), ICC 0.88', targetValue: '≥25', targetUnit: 'herhalingen', inputType: 'NUMERIC', isBonus: false },
        { name: 'ATRS', testDescription: '10-item vragenlijst specifiek voor achillespeesruptuur, score 0-100.', reference: 'Nilsson-Helander et al. (2007), ICC 0.98, MDC 8.4, MCID 10', targetValue: 'Vastleggen als baseline', targetUnit: 'punten', inputType: 'NUMERIC', isBonus: false },
        { name: 'VISA-A', testDescription: '8-item vragenlijst voor achillespees klachten en functie, score 0-100.', reference: 'Robinson et al. (2001), ICC 0.90', targetValue: 'Vastleggen als baseline', targetUnit: 'punten', inputType: 'NUMERIC', isBonus: false },
        { name: 'Thompson Test', testDescription: 'Patiënt in buikligging; knijpen in kuit evalueren op passieve plantairflexie respons.', reference: 'Thompson & Doherty (1962), sensitiviteit 96%', targetValue: 'Positief', targetUnit: 'bevestiging', inputType: 'PASS_FAIL', isBonus: false },
      ],
    },
    {
      order: 1,
      shortName: 'Fase 1',
      name: 'Fase 1: Bescherming & Vroeg Herstel (Week 0-6)',
      description: 'Weefselbescherming in gipsverband en walker boot met voorzichtige belastingsopbouw. Dorsaalflexie voorbij neutraal is gecontra-indiceerd.',
      keyGoals: ['Weefselbescherming reparatie', 'Gecontroleerde belastingsopbouw', 'Zwellingreductie'],
      typicalStartWeek: 0,
      typicalEndWeek: 6,
      criteria: [
        { name: 'Thompson Test', testDescription: 'Herhaalde beoordeling pees continuïteit door passieve plantairflexie bij kuitknijpen.', reference: 'Thompson & Doherty (1962)', targetValue: 'Negatief', targetUnit: 'continuïteit intact', inputType: 'PASS_FAIL', isBonus: false },
        { name: 'Pijn (NRS)', testDescription: 'Numerieke Rating Schaal pijn in rust en bij belasting in boot.', reference: 'Ferreira-Valente et al. (2011), ICC 0.95', targetValue: '≤3/10 rust, ≤4/10 belasting', targetUnit: 'schaal 0-10', inputType: 'NUMERIC', isBonus: false },
        { name: 'Zwelling (figure-of-8)', testDescription: 'Omtrekmeting enkel in achtvormig patroon met meetlint.', reference: 'Mawdsley et al. (2000), ICC 0.98-0.99', targetValue: '≤1.5 cm verschil', targetUnit: 'cm', inputType: 'NUMERIC', isBonus: false },
        { name: 'Goniometrie plantairflexie', testDescription: 'Passieve ROM plantairflexie; dorsaalflexie NIET geforceerd in deze fase.', reference: 'Norkin & White (2016)', targetValue: '≥30°', targetUnit: 'graden', inputType: 'NUMERIC', isBonus: false },
        { name: 'Gewichtsdracht progressie', testDescription: 'Beoordeling looppatroon in walker boot; progressie non-WB naar partiële belasting.', reference: 'Klinische observatie', targetValue: 'Week 0-2: non-WB; Week 2-6: 50-75% WB', targetUnit: 'beschrijving', inputType: 'TEXT', isBonus: false },
      ],
    },
    {
      order: 2,
      shortName: 'Fase 2',
      name: 'Fase 2: Vroege Mobiliteit & Kracht (Week 6-12)',
      description: 'Afbouw walker boot, introductie dorsaalflexie naar neutraal, actieve plantairflexie oefeningen. Collageen in late proliferatieve fase.',
      keyGoals: ['ROM-herstel dorsaalflexie', 'Vroege kracht activatie gastrocnemius-soleus', 'Gangpatroon normalisatie'],
      typicalStartWeek: 6,
      typicalEndWeek: 12,
      criteria: [
        { name: 'Goniometrie enkel (DF + PF)', testDescription: 'Passieve ROM dorsaalflexie en plantairflexie.', reference: 'Norkin & White (2016)', targetValue: 'DF ≥0°, PF ≥40°', targetUnit: 'graden', inputType: 'NUMERIC', isBonus: false },
        { name: 'Lunge Test', testDescription: 'Weight-bearing dorsaalflexie; afstand knie-muur in cm.', reference: 'Bennell et al. (1998), ICC 0.97', targetValue: '≥5 cm', targetUnit: 'cm', inputType: 'NUMERIC', isBonus: false },
        { name: 'Single Leg Calf Raise (grond)', testDescription: 'Maximaal aantal herhalingen op één been op vlakke grond, beperkte ROM.', reference: 'Hébert-Losier et al. (2009)', targetValue: '≥10', targetUnit: 'herhalingen', inputType: 'NUMERIC', isBonus: false },
        { name: 'ATRS', testDescription: 'Gevalideerde vragenlijst achillespeesruptuur outcomes.', reference: 'Nilsson-Helander et al. (2007)', targetValue: '≥40', targetUnit: 'punten', inputType: 'NUMERIC', isBonus: false },
        { name: 'Ganganalyse', testDescription: 'Klinische observatie looppatroon: hielcontact, afrolpatroon, stap-symmetrie zonder antalgisch patroon.', reference: 'Klinische observatie', targetValue: 'Normaal gangpatroon', targetUnit: 'beschrijving', inputType: 'TEXT', isBonus: false },
      ],
    },
    {
      order: 3,
      shortName: 'Fase 3',
      name: 'Fase 3: Neuromusculaire Controle & Functionele Kracht (Week 12-20)',
      description: 'Opbouw functionele kracht triceps surae via concentrisch en excentrisch training. Collageen bereikt toegenomen mechanische sterkte; voorbereiding hardlopen.',
      keyGoals: ['Functionele kracht volledig calf raise', 'Dynamische stabiliteit en proprioceptie', 'Voorbereiding return-to-running'],
      typicalStartWeek: 12,
      typicalEndWeek: 20,
      criteria: [
        { name: 'Single Leg Calf Raise (trede)', testDescription: 'Maximaal aantal herhalingen op één been op trede in volledige ROM, tempo 1 per 2 sec.', reference: 'Hébert-Losier et al. (2009), ICC 0.88', targetValue: '≥25', targetUnit: 'herhalingen', inputType: 'NUMERIC', isBonus: false },
        { name: 'Lunge Test', testDescription: 'Weight-bearing dorsaalflexie meting in cm; Limb Symmetry Index te berekenen.', reference: 'Bennell et al. (1998), ICC 0.97', targetValue: '≥8 cm of LSI ≥75%', targetUnit: 'cm/procent', inputType: 'NUMERIC', isBonus: false },
        { name: 'ATRS', testDescription: 'Vragenlijst functionele beperkingen en symptomen.', reference: 'Nilsson-Helander et al. (2007)', targetValue: '≥60', targetUnit: 'punten', inputType: 'NUMERIC', isBonus: false },
        { name: 'VISA-A', testDescription: 'Vragenlijst achillespees functie inclusief sport activiteiten.', reference: 'Robinson et al. (2001), ICC 0.90', targetValue: '≥70', targetUnit: 'punten', inputType: 'NUMERIC', isBonus: false },
        { name: 'HHD plantairflexie', testDescription: 'Isometrische plantairflexie kracht met hand-held dynamometer, Limb Symmetry Index.', reference: 'Hébert-Losier et al. (2012), ICC 0.85-0.95', targetValue: 'LSI ≥70%', targetUnit: 'procent', inputType: 'NUMERIC', isBonus: false },
        { name: 'Single Leg Balance (ogen dicht)', testDescription: 'Eénbenstand op stabiele ondergrond, ogen gesloten.', reference: 'Springer et al. (2007), ICC 0.79-0.87', targetValue: '≥15 sec', targetUnit: 'seconden', inputType: 'NUMERIC', isBonus: false },
      ],
    },
    {
      order: 4,
      shortName: 'Fase 4',
      name: 'Fase 4: Hardlopen & Sportspecifieke Opbouw (Week 20-32)',
      description: 'Return-to-running criteria volgens Silbernagel. Hardloopanalyse via Ochy.io om biomechanische asymmetrieën te detecteren. Plyometrische opbouw.',
      keyGoals: ['Veilige return to running', 'Plyometrische capaciteit opbouwen', 'Sportspecifieke belastingspatronen'],
      typicalStartWeek: 20,
      typicalEndWeek: 32,
      criteria: [
        { name: 'Return-to-Running Criteria (Silbernagel)', testDescription: 'Combinatie van pijnvrij wandelen 30 min, calf raise ≥25 reps, geen pijntoename post-belasting, geen ochtendstijfheid >30 min.', reference: 'Silbernagel et al. (2010)', targetValue: 'Alle 4 criteria behaald', targetUnit: 'pass/fail', inputType: 'PASS_FAIL', isBonus: false },
        { name: 'Single Leg Hop for Distance', testDescription: 'Maximale afstand éénbensprong met gecontroleerde landing, LSI berekenen.', reference: 'Noyes et al. (1991), ICC 0.92-0.96', targetValue: 'LSI ≥80%', targetUnit: 'procent', inputType: 'NUMERIC', isBonus: false },
        { name: 'Triple Hop for Distance', testDescription: 'Drie opeenvolgende éénbensprongen, totale afstand en LSI.', reference: 'Hamilton et al. (2008), ICC 0.95-0.97', targetValue: 'LSI ≥80%', targetUnit: 'procent', inputType: 'NUMERIC', isBonus: false },
        { name: 'Crossover Hop for Distance', testDescription: 'Drie éénbensprongen met mediolaterale component over lijn, LSI.', reference: 'Noyes et al. (1991), ICC 0.93', targetValue: 'LSI ≥80%', targetUnit: 'procent', inputType: 'NUMERIC', isBonus: false },
        { name: 'HHD Plantairflexie', testDescription: 'Isometrische kracht plantairflexie, LSI berekenen.', reference: 'Hébert-Losier et al. (2012)', targetValue: 'LSI ≥80%', targetUnit: 'procent', inputType: 'NUMERIC', isBonus: false },
        { name: 'Hardloopanalyse (Ochy.io)', testDescription: 'Biomechanische analyse op loopband: contacttijd, kadans, verticale oscillatie, enkel-kniehoeken.', reference: 'AI computer vision, 200+ studies', targetValue: 'Symmetrische belasting, asymmetrie <5%', targetUnit: 'beschrijving', inputType: 'TEXT', isBonus: false },
        { name: 'ATRS', testDescription: 'Achillespeesruptuur vragenlijst.', reference: 'Nilsson-Helander et al. (2007)', targetValue: '≥75', targetUnit: 'punten', inputType: 'NUMERIC', isBonus: false },
      ],
    },
    {
      order: 5,
      shortName: 'Fase 5',
      name: 'Fase 5: Return to Sport (Week 32-48)',
      description: 'Stringente criteria voor volledige sportparticipatie. LSI ≥90% voor kracht en plyometrie. Psychologische gereedheid integraal.',
      keyGoals: ['Volledige sportparticipatie', 'Krachtsymmetrie ≥90%', 'Psychologische gereedheid'],
      typicalStartWeek: 32,
      typicalEndWeek: 48,
      criteria: [
        { name: 'HHD/Isokinetische Plantairflexie', testDescription: 'Maximale isometrische of isokinetische plantairflexie kracht, LSI.', reference: 'Hébert-Losier et al. (2012)', targetValue: 'LSI ≥90%', targetUnit: 'procent', inputType: 'NUMERIC', isBonus: false },
        { name: 'Single Leg Hop for Distance', testDescription: 'Maximale afstand éénbensprong, LSI.', reference: 'Noyes et al. (1991)', targetValue: 'LSI ≥90%', targetUnit: 'procent', inputType: 'NUMERIC', isBonus: false },
        { name: 'Triple Hop for Distance', testDescription: 'Drie opeenvolgende éénbensprongen, LSI.', reference: 'Hamilton et al. (2008)', targetValue: 'LSI ≥90%', targetUnit: 'procent', inputType: 'NUMERIC', isBonus: false },
        { name: 'Crossover Hop for Distance', testDescription: 'Drie éénbensprongen met mediolaterale component, LSI.', reference: 'Noyes et al. (1991)', targetValue: 'LSI ≥90%', targetUnit: 'procent', inputType: 'NUMERIC', isBonus: false },
        { name: 'Single Leg Calf Raise (trede)', testDescription: 'Maximaal aantal herhalingen volledige ROM.', reference: 'Hébert-Losier et al. (2009)', targetValue: 'LSI ≥90%, absoluut ≥25', targetUnit: 'procent/herhalingen', inputType: 'NUMERIC', isBonus: false },
        { name: 'ATRS', testDescription: 'Achillespeesruptuur vragenlijst.', reference: 'Nilsson-Helander et al. (2007)', targetValue: '≥85', targetUnit: 'punten', inputType: 'NUMERIC', isBonus: false },
        { name: 'VISA-A', testDescription: 'Vragenlijst achillespees functie en symptomen.', reference: 'Robinson et al. (2001)', targetValue: '≥85', targetUnit: 'punten', inputType: 'NUMERIC', isBonus: false },
        { name: 'Psychologische gereedheid (ACL-RSI)', testDescription: 'Aangepaste schaal voor achillespeesletsel; vertrouwen, angst, risico-evaluatie sport.', reference: 'Webster et al. (2008), aangepast', targetValue: '≥70%', targetUnit: 'procent', inputType: 'NUMERIC', isBonus: false },
      ],
    },
    {
      order: 6,
      shortName: 'Fase 6',
      name: 'Fase 6: Preventie van Recidief (Week 48+)',
      description: 'Langdurige monitoring kracht symmetrie en symptomen. Excentrische training onderhoud (Alfredson protocol) 2-3x/week levenslang.',
      keyGoals: ['Langdurig kracht onderhoud', 'Periodieke monitoring', 'Zelfmanagement patiënt'],
      typicalStartWeek: 48,
      typicalEndWeek: null,
      criteria: [
        { name: 'Single Leg Calf Raise (trede)', testDescription: 'Maximaal aantal herhalingen; afname elke 3 maanden eerste jaar.', reference: 'Hébert-Losier et al. (2009)', targetValue: 'LSI ≥90%', targetUnit: 'procent', inputType: 'NUMERIC', isBonus: false },
        { name: 'ATRS', testDescription: 'Vragenlijst; afname elke 3 maanden.', reference: 'Nilsson-Helander et al. (2007)', targetValue: '≥85', targetUnit: 'punten', inputType: 'NUMERIC', isBonus: false },
        { name: 'VISA-A', testDescription: 'Vragenlijst; afname elke 6 maanden.', reference: 'Robinson et al. (2001)', targetValue: '≥85', targetUnit: 'punten', inputType: 'NUMERIC', isBonus: false },
        { name: 'HHD Plantairflexie', testDescription: 'Isometrische kracht, LSI; afname elke 6 maanden.', reference: 'Hébert-Losier et al. (2012)', targetValue: 'LSI ≥85%', targetUnit: 'procent', inputType: 'NUMERIC', isBonus: false },
        { name: 'Symptoommonitoring', testDescription: 'Zelfrapportage: ochtendstijfheid >30 min, pijn opstarten, zwelling na sport, pees verdikking.', reference: 'Klinische observatie', targetValue: '0 alarmsymptomen', targetUnit: 'symptomen', inputType: 'PASS_FAIL', isBonus: false },
      ],
    },
  ],
}

export const LATERAL_ANKLE_RECONSTRUCTION_PROTOCOL = {
  protocol: {
    key: 'laterale-enkelbandreconstructie',
    name: 'Laterale Enkelbandreconstructie (Broström-Gould) — Criteria-Based Revalidatie',
    description: 'Protocol voor postoperatieve revalidatie na Broström-Gould procedure. Recidiefpercentage zonder adequate revalidatie 40-70%; met criteria-based revalidatie 10-15%.',
    specialty: 'lateral_ankle_reconstruction',
    sourceReference: 'Movement Based Therapy Amsterdam (2026). Criteria-Based Revalidatieprotocol: Laterale Enkelbandreconstructie.',
  },
  phases: [
    {
      order: 0,
      shortName: 'Pre-op',
      name: 'Pre-operatieve Fase — Gereed voor Operatie',
      description: 'Optimalisering neuromusculaire controle en ROM. Baseline meetwaarden vastleggen. Patiënteducatie over postoperatieve beperkingen.',
      keyGoals: ['Enkerkracht en ROM optimaliseren', 'Baseline meetwaarden vastleggen', 'Patiënteducatie verwachtingsmanagement'],
      typicalStartWeek: -4,
      typicalEndWeek: 0,
      criteria: [
        { name: 'Goniometrie enkel', testDescription: 'Passieve ROM dorsaalflexie, plantairflexie, inversie en eversie met universele goniometer.', reference: 'Norkin & White (2016), ICC 0.90-0.98', targetValue: 'Vastleggen als baseline; DF ≥10°, PF ≥40°', targetUnit: 'graden', inputType: 'NUMERIC', isBonus: false },
        { name: 'Lunge Test', testDescription: 'Weight-bearing dorsaalflexie; patiënt maakt lunge totdat knie muur raakt.', reference: 'Bennell et al. (1998), ICC 0.97-0.98', targetValue: '≥10 cm of baseline', targetUnit: 'cm', inputType: 'NUMERIC', isBonus: false },
        { name: 'Single Leg Calf Raise', testDescription: 'Maximaal aantal herhalingen op één been op trede, tempo 1 per 2 sec.', reference: 'Hébert-Losier et al. (2009), ICC 0.88', targetValue: 'Vastleggen als baseline; norm ≥25', targetUnit: 'herhalingen', inputType: 'NUMERIC', isBonus: false },
        { name: 'FAAM', testDescription: '21-item ADL subschaal en 8-item Sport subschaal op 5-punts Likertschaal.', reference: 'Martin et al. (2005), MDC 5.7/12.3', targetValue: 'Vastleggen als baseline', targetUnit: 'punten', inputType: 'NUMERIC', isBonus: false },
        { name: 'CAIT', testDescription: '9-item vragenlijst functionele instabiliteit, score 0-30.', reference: 'Hiller et al. (2006), sensitiviteit 82.9%', targetValue: 'Vastleggen als baseline', targetUnit: 'punten', inputType: 'NUMERIC', isBonus: false },
      ],
    },
    {
      order: 1,
      shortName: 'Fase 1',
      name: 'Fase 1: Bescherming & Vroeg Herstel (Week 0-4)',
      description: 'Weefselbescherming gereconstrueerde ligament in inflammatoire/proliferatieve fase. Inversie en eversie vermeden. Gecontroleerde axiale belasting in walker boot.',
      keyGoals: ['Weefselbescherming ligament reparatie', 'Zwellingreductie', 'Vroege gecontroleerde belasting'],
      typicalStartWeek: 0,
      typicalEndWeek: 4,
      criteria: [
        { name: 'Pijn (NRS)', testDescription: 'Numerieke Rating Schaal pijn in rust en bij belasting.', reference: 'Ferreira-Valente et al. (2011), ICC 0.95', targetValue: '≤3/10 rust, ≤5/10 belasting', targetUnit: 'schaal 0-10', inputType: 'NUMERIC', isBonus: false },
        { name: 'Zwelling (figure-of-8)', testDescription: 'Omtrekmeting enkel in achtvormig patroon.', reference: 'Mawdsley et al. (2000), ICC 0.98-0.99', targetValue: '≤1.0 cm verschil contralateraal', targetUnit: 'cm', inputType: 'NUMERIC', isBonus: false },
        { name: 'Goniometrie DF/PF', testDescription: 'Passieve ROM sagittaal vlak; inversie/eversie NIET gemeten (bescherming).', reference: 'Norkin & White (2016)', targetValue: 'DF ≥0°, PF ≥30°', targetUnit: 'graden', inputType: 'NUMERIC', isBonus: false },
        { name: 'Gewichtsdracht', testDescription: 'Beoordeling looppatroon met walker boot en krukken; pijnvrije belastingsprogressie.', reference: 'Klinische observatie', targetValue: 'Pijnvrij 50-75% WB in boot', targetUnit: 'beschrijving', inputType: 'TEXT', isBonus: false },
        { name: 'Quadriceps activatie', testDescription: 'Straight Leg Raise zonder extensie lag; isometrische quadriceps aanspanning.', reference: 'Klinische observatie', targetValue: 'Actieve SLR zonder lag', targetUnit: 'pass/fail', inputType: 'PASS_FAIL', isBonus: false },
      ],
    },
    {
      order: 2,
      shortName: 'Fase 2',
      name: 'Fase 2: Vroege Mobiliteit & Kracht (Week 4-8)',
      description: 'ROM-herstel inclusief voorzichtige inversie/eversie opbouw. Afbouw walker boot. Vroege kracht peroneale spieren en plantairflexoren.',
      keyGoals: ['ROM normalisatie enkel', 'Basissterkte peroneale spieren', 'Gangpatroon normalisatie'],
      typicalStartWeek: 4,
      typicalEndWeek: 8,
      criteria: [
        { name: 'Goniometrie enkel (volledig)', testDescription: 'Passieve ROM alle richtingen: DF, PF, inversie, eversie.', reference: 'Norkin & White (2016)', targetValue: 'DF ≥10°, PF ≥40°, inv/eve ≥75% contralateraal', targetUnit: 'graden/procent', inputType: 'NUMERIC', isBonus: false },
        { name: 'Lunge Test', testDescription: 'Weight-bearing dorsaalflexie; afstand knie-muur in cm.', reference: 'Bennell et al. (1998)', targetValue: '≥8 cm of ≥75% baseline', targetUnit: 'cm/procent', inputType: 'NUMERIC', isBonus: false },
        { name: 'Anterior Drawer Test', testDescription: 'Patiënt in rugligging knie 90° flexie; onderzoeker trekt talus anterieur.', reference: 'Van Dijk et al. (1996), sensitiviteit 73%', targetValue: 'Negatief', targetUnit: 'stevig eindgevoel', inputType: 'PASS_FAIL', isBonus: false },
        { name: 'Single Leg Balance (ogen open)', testDescription: 'Eénbenstand op stabiele ondergrond, ogen open; tijd tot eerste compensatie.', reference: 'Springer et al. (2007), ICC 0.79-0.87', targetValue: '≥30 sec', targetUnit: 'seconden', inputType: 'NUMERIC', isBonus: false },
        { name: 'Single Leg Calf Raise (grond)', testDescription: 'Maximaal aantal herhalingen op één been op vlakke grond.', reference: 'Hébert-Losier et al. (2009)', targetValue: '≥15', targetUnit: 'herhalingen', inputType: 'NUMERIC', isBonus: false },
      ],
    },
    {
      order: 3,
      shortName: 'Fase 3',
      name: 'Fase 3: Neuromusculaire Controle & Functionele Kracht (Week 8-14)',
      description: 'Opbouw dynamische stabiliteit via proprioceptieve training. Star Excursion Balance Test als integraal doel. Voorbereiding hardlopen.',
      keyGoals: ['Dynamische stabiliteit en neuromusculaire controle', 'Functionele kracht triceps surae', 'Voorbereiding hardlopen'],
      typicalStartWeek: 8,
      typicalEndWeek: 14,
      criteria: [
        { name: 'Star Excursion Balance Test (SEBT)', testDescription: 'Eénbenstand bereiken in 3 richtingen (anterior, posteromedial, posterolateral); genormaliseerd naar beenlengte.', reference: 'Gribble et al. (2012), ICC 0.85-0.93', targetValue: 'LSI ≥90% alle richtingen', targetUnit: 'procent', inputType: 'NUMERIC', isBonus: false },
        { name: 'Single Leg Balance (ogen dicht)', testDescription: 'Eénbenstand op stabiele ondergrond, ogen gesloten.', reference: 'Springer et al. (2007)', targetValue: '≥15 sec', targetUnit: 'seconden', inputType: 'NUMERIC', isBonus: false },
        { name: 'Single Leg Calf Raise (trede)', testDescription: 'Maximaal aantal herhalingen op trede in volledige ROM.', reference: 'Hébert-Losier et al. (2009)', targetValue: '≥25', targetUnit: 'herhalingen', inputType: 'NUMERIC', isBonus: false },
        { name: 'FAAM Sport subschaal', testDescription: '8-item sportgerelateerde functie vragenlijst.', reference: 'Martin et al. (2005), MDC 12.3', targetValue: '≥80%', targetUnit: 'procent', inputType: 'NUMERIC', isBonus: false },
        { name: 'CAIT', testDescription: '9-item functionele instabiliteit vragenlijst.', reference: 'Hiller et al. (2006)', targetValue: '≥26', targetUnit: 'punten', inputType: 'NUMERIC', isBonus: false },
      ],
    },
    {
      order: 4,
      shortName: 'Fase 4',
      name: 'Fase 4: Hardlopen & Sportspecifieke Opbouw (Week 14-20)',
      description: 'Return-to-running met grondreactiekrachten 2.5-3x lichaamsgewicht. Laterale stabiliteit onder dynamische belasting. Hardloopanalyse Ochy.io.',
      keyGoals: ['Veilige return to running', 'Laterale stabiliteit onder dynamische belasting', 'Sportspecifieke bewegingspatronen'],
      typicalStartWeek: 14,
      typicalEndWeek: 20,
      criteria: [
        { name: 'Side Hop Test', testDescription: 'Zijwaarts springen over twee lijnen (30 cm apart) op één been 30 sec; aantal succesvolle landingen.', reference: 'Gustavsson et al. (2006), ICC 0.84-0.90', targetValue: 'LSI ≥90%', targetUnit: 'procent', inputType: 'NUMERIC', isBonus: false },
        { name: 'Figure-of-8 Hop Test', testDescription: 'Hoppen op één been langs 8-vormig parcours (5 m per cirkel); tijd en kwaliteit.', reference: 'Docherty et al. (2005), ICC 0.95', targetValue: 'LSI ≥90%', targetUnit: 'procent', inputType: 'NUMERIC', isBonus: false },
        { name: 'Single Leg Hop for Distance', testDescription: 'Maximale afstand éénbensprong met gecontroleerde landing; LSI berekenen.', reference: 'Noyes et al. (1991)', targetValue: 'LSI ≥85%', targetUnit: 'procent', inputType: 'NUMERIC', isBonus: false },
        { name: 'Hardloopanalyse (Ochy.io)', testDescription: 'Biomechanische analyse op loopband; contacttijd, kadans, knie- en enkelhoeken.', reference: 'AI computer vision, 200+ studies', targetValue: 'Symmetrische belasting, geen compensaties', targetUnit: 'beschrijving', inputType: 'TEXT', isBonus: false },
        { name: 'FAAM ADL + Sport', testDescription: 'Volledige FAAM vragenlijst ADL en Sport subscales.', reference: 'Martin et al. (2005)', targetValue: 'ADL ≥90%, Sport ≥85%', targetUnit: 'procent', inputType: 'NUMERIC', isBonus: false },
      ],
    },
    {
      order: 5,
      shortName: 'Fase 5',
      name: 'Fase 5: Return to Sport (Week 20-26)',
      description: 'Stringente multidimensionale criteria voor volledige sporthervatting. Met RTS-criteria 10-15% recidief; zonder tot 70%.',
      keyGoals: ['Volledige sportparticipatie', 'Objectieve gereedheid multidimensionaal', 'Psychologische bereidheid'],
      typicalStartWeek: 20,
      typicalEndWeek: 26,
      criteria: [
        { name: 'Side Hop Test', testDescription: 'Zijwaarts springen op één been 30 sec; aantal succesvolle landingen.', reference: 'Gustavsson et al. (2006)', targetValue: 'LSI ≥95%', targetUnit: 'procent', inputType: 'NUMERIC', isBonus: false },
        { name: 'Figure-of-8 Hop Test', testDescription: 'Hoppen langs 8-vormig parcours op één been; tijd en kwaliteit.', reference: 'Docherty et al. (2005)', targetValue: 'LSI ≥95%', targetUnit: 'procent', inputType: 'NUMERIC', isBonus: false },
        { name: 'Single Leg Hop for Distance', testDescription: 'Maximale afstand éénbensprong; LSI.', reference: 'Noyes et al. (1991)', targetValue: 'LSI ≥90%', targetUnit: 'procent', inputType: 'NUMERIC', isBonus: false },
        { name: 'SEBT', testDescription: 'Star Excursion Balance Test alle richtingen; LSI.', reference: 'Gribble et al. (2012)', targetValue: 'LSI ≥95% alle richtingen', targetUnit: 'procent', inputType: 'NUMERIC', isBonus: false },
        { name: 'FAAM', testDescription: 'Volledige Foot and Ankle Ability Measure ADL en Sport.', reference: 'Martin et al. (2005)', targetValue: 'ADL ≥95%, Sport ≥90%', targetUnit: 'procent', inputType: 'NUMERIC', isBonus: false },
        { name: 'CAIT', testDescription: 'Cumberland Ankle Instability Tool.', reference: 'Hiller et al. (2006)', targetValue: '≥28', targetUnit: 'punten', inputType: 'NUMERIC', isBonus: false },
        { name: 'Anterior Drawer Test', testDescription: 'Patiënt in ruglig knie 90°; onderzoeker trekt talus anterieur.', reference: 'Van Dijk et al. (1996)', targetValue: 'Negatief', targetUnit: 'stevig eindgevoel', inputType: 'PASS_FAIL', isBonus: false },
        { name: 'Psychologische gereedheid (ACL-RSI)', testDescription: 'Aangepast voor enkelbandletsel; vertrouwen, angst, risico-evaluatie sport.', reference: 'Webster et al. (2008), aangepast', targetValue: '≥70%', targetUnit: 'procent', inputType: 'NUMERIC', isBonus: false },
      ],
    },
    {
      order: 6,
      shortName: 'Fase 6',
      name: 'Fase 6: Preventie van Recidief (Week 26+)',
      description: 'Langdurige neuromusculaire training en proprioceptieve oefeningen 2x/week. Bracing/taping bij sport 12+ maanden. Periodieke monitoring.',
      keyGoals: ['Langdurige neuromusculaire training', 'Monitoring functieverlies', 'Zelfmanagement patiënt'],
      typicalStartWeek: 26,
      typicalEndWeek: null,
      criteria: [
        { name: 'CAIT', testDescription: 'Cumberland Ankle Instability Tool; afname elke 3 maanden eerste jaar.', reference: 'Hiller et al. (2006)', targetValue: '≥28', targetUnit: 'punten', inputType: 'NUMERIC', isBonus: false },
        { name: 'FAAM Sport', testDescription: 'Foot and Ankle Ability Measure Sport subschaal; afname elke 3 maanden.', reference: 'Martin et al. (2005)', targetValue: '≥90%', targetUnit: 'procent', inputType: 'NUMERIC', isBonus: false },
        { name: 'SEBT', testDescription: 'Star Excursion Balance Test; afname elke 6 maanden.', reference: 'Gribble et al. (2012)', targetValue: 'LSI ≥90%', targetUnit: 'procent', inputType: 'NUMERIC', isBonus: false },
        { name: 'Single Leg Balance (ogen dicht)', testDescription: 'Eénbenstand ogen dicht; afname elke 3 maanden.', reference: 'Springer et al. (2007)', targetValue: '≥20 sec', targetUnit: 'seconden', inputType: 'NUMERIC', isBonus: false },
        { name: 'Recidiefregistratie', testDescription: 'Zelfrapportage: giving way episodes, zwelling na sport, pijn bij belasting.', reference: 'Klinische observatie', targetValue: '0 episodes', targetUnit: 'symptomen', inputType: 'PASS_FAIL', isBonus: false },
      ],
    },
  ],
}

export const HIP_FAI_PROTOCOL = {
  protocol: {
    key: 'heuparthroscopie-fai',
    name: 'Heuparthroscopie (FAI / Labrum Reparatie) — Criteria-Based Revalidatie',
    description: 'Protocol voor postoperatieve revalidatie na heuparthroscopie wegens femoroacetabulair impingement (FAI) en/of labrum reparatie. Labrum reparatie vereist bescherming eerste 6 weken.',
    specialty: 'hip_fai',
    sourceReference: 'Movement Based Therapy Amsterdam (2026). Criteria-Based Revalidatieprotocol: Heuparthroscopie (FAI / Labrum Reparatie).',
  },
  phases: [
    {
      order: 0,
      shortName: 'Pre-op',
      name: 'Pre-operatieve Fase — Gereed voor Operatie',
      description: 'Optimalisering heupmusculatuur kracht en neuromusculaire controle. Baseline meetwaarden voor postoperatieve vergelijking.',
      keyGoals: ['Heupabductor- en extensorkracht optimaliseren', 'Baseline meetwaarden vastleggen', 'Patiënteducatie postoperatief traject'],
      typicalStartWeek: -4,
      typicalEndWeek: 0,
      criteria: [
        { name: 'Heupabductorkracht', testDescription: 'Hand Held Dynamometry in zijlig, gestandaardiseerd protocol.', reference: 'Thorborg et al. (2010)', targetValue: 'Baseline vastleggen', targetUnit: 'Newton', inputType: 'NUMERIC', isBonus: false },
        { name: 'Heupflexorkracht', testDescription: 'HHD in ruglig, knie 90° gebogen.', reference: 'Thorborg et al. (2010)', targetValue: 'Baseline vastleggen', targetUnit: 'Newton', inputType: 'NUMERIC', isBonus: false },
        { name: 'iHOT-33', testDescription: 'International Hip Outcome Tool 33 items.', reference: 'Mohtadi et al. (2012)', targetValue: 'Baseline vastleggen', targetUnit: 'punten 0-100', inputType: 'NUMERIC', isBonus: false },
        { name: 'HOS-ADL & Sport', testDescription: 'Hip Outcome Score ADL en Sport subscales.', reference: 'Martin & Philippon (2007)', targetValue: 'Baseline vastleggen', targetUnit: 'procent', inputType: 'NUMERIC', isBonus: false },
        { name: 'Single leg balance', testDescription: 'Eénbenstand ogen open, 30 sec bilateraal.', reference: 'Springer et al. (2007)', targetValue: '≥30 sec bilateraal', targetUnit: 'seconden', inputType: 'NUMERIC', isBonus: false },
        { name: '6-minuten looptest', testDescription: 'Gestandaardiseerd protocol; maximale afstand lopend in 6 minuten.', reference: 'ATS (2002)', targetValue: 'Baseline vastleggen', targetUnit: 'meter', inputType: 'NUMERIC', isBonus: false },
      ],
    },
    {
      order: 1,
      shortName: 'Fase 1',
      name: 'Fase 1: Bescherming & Vroeg Herstel (Week 0-4)',
      description: 'Bescherming labrum reparatie in inflammatoire/proliferatieve fase. Heupflexie ≤90°. Gedeeltelijke belasting met krukken.',
      keyGoals: ['Weefselbescherming labrum en heupkapsel', 'Pijn en zwelling controle', 'Gluteale activatie behoud'],
      typicalStartWeek: 0,
      typicalEndWeek: 4,
      criteria: [
        { name: 'Pijn in rust (VAS)', testDescription: 'Visueel Analoge Schaal pijn 0-10 in rust.', reference: 'Bijur et al. (2001)', targetValue: '≤3/10', targetUnit: 'schaal 0-10', inputType: 'NUMERIC', isBonus: false },
        { name: 'Passieve heupflexie ROM', testDescription: 'Goniometrie in ruglig; heupflexie beperkt ≤90°.', reference: 'Clapis et al. (2008)', targetValue: '0-90° (niet voorbij)', targetUnit: 'graden', inputType: 'NUMERIC', isBonus: false },
        { name: 'Passieve heupabductie ROM', testDescription: 'Goniometrie in ruglig.', reference: 'Clapis et al. (2008)', targetValue: '≥20°', targetUnit: 'graden', inputType: 'NUMERIC', isBonus: false },
        { name: 'Straight Leg Raise', testDescription: 'Actieve heupflexie in ruglig, knie gestrekt; zelfstandig uitvoerbaar.', reference: 'Klinische observatie', targetValue: 'Zelfstandig zonder pijn', targetUnit: 'pass/fail', inputType: 'PASS_FAIL', isBonus: false },
        { name: 'Looppatroon', testDescription: 'Observationele ganganalyse met krukken.', reference: 'Perry & Burnfield (2010)', targetValue: 'Symmetrisch patroon, gedeeltelijke WB', targetUnit: 'beschrijving', inputType: 'TEXT', isBonus: false },
        { name: 'FABER test', testDescription: 'Flexie-Abductie-Exorotatie provocatietest.', reference: 'Martin & Sekiya (2008)', targetValue: 'Symptoomvrij', targetUnit: 'pass/fail', inputType: 'PASS_FAIL', isBonus: false },
      ],
    },
    {
      order: 2,
      shortName: 'Fase 2',
      name: 'Fase 2: Vroege Kracht & Mobiliteit (Week 4-8)',
      description: 'ROM-herstel voorbij 90° flexie progressief. Afbouw krukken. Gesloten-ketentraining. Isometrisch naar isotoon kracht.',
      keyGoals: ['Volledig pijnvrij ROM herstel', 'Afbouw krukken', 'Isometrisch naar isotone kracht opbouw'],
      typicalStartWeek: 4,
      typicalEndWeek: 8,
      criteria: [
        { name: 'Actieve heupflexie ROM', testDescription: 'Goniometrie actief in ruglig.', reference: 'Clapis et al. (2008)', targetValue: '≥110° pijnvrij', targetUnit: 'graden', inputType: 'NUMERIC', isBonus: false },
        { name: 'Actieve heupabductie ROM', testDescription: 'Goniometrie actief in zijlig.', reference: 'Clapis et al. (2008)', targetValue: '≥30° pijnvrij', targetUnit: 'graden', inputType: 'NUMERIC', isBonus: false },
        { name: 'Heupexo-/endorotatie ROM', testDescription: 'Goniometrie in buiklig, heup neutraal.', reference: 'Clapis et al. (2008)', targetValue: 'Symmetrisch, binnen 5° contralateraal', targetUnit: 'graden', inputType: 'NUMERIC', isBonus: false },
        { name: 'Heupabductorkracht', testDescription: 'HHD in zijlig; Limb Symmetry Index berekenen.', reference: 'Thorborg et al. (2010), ICC 0.91', targetValue: 'LSI ≥60%', targetUnit: 'procent', inputType: 'NUMERIC', isBonus: false },
        { name: 'Gangpatroon zonder hulpmiddelen', testDescription: 'Observationele ganganalyse; Trendelenburg-teken evalueren.', reference: 'Perry & Burnfield (2010)', targetValue: 'Trendelenburg-negatief', targetUnit: 'beschrijving', inputType: 'TEXT', isBonus: false },
        { name: 'FADIR test', testDescription: 'Flexie-Adductie-Endorotatie provocatietest.', reference: 'Maslowski et al. (2010)', targetValue: 'Pijnvrij of significant verbeterd', targetUnit: 'pass/fail', inputType: 'PASS_FAIL', isBonus: false },
      ],
    },
    {
      order: 3,
      shortName: 'Fase 3',
      name: 'Fase 3: Functionele Kracht & Neuromusculaire Controle (Week 8-14)',
      description: 'Opbouw functionele kracht voor ADL en sportvoorbereiding. Single-leg taken introduceren.',
      keyGoals: ['Heupabductor- en extensorkracht LSI ≥80%', 'Adequate single-leg stabiliteit', 'Pijnvrije ADL inclusief traplopen'],
      typicalStartWeek: 8,
      typicalEndWeek: 14,
      criteria: [
        { name: 'Heupabductorkracht', testDescription: 'HHD in zijlig; LSI berekenen.', reference: 'Thorborg et al. (2010)', targetValue: 'LSI ≥80%', targetUnit: 'procent', inputType: 'NUMERIC', isBonus: false },
        { name: 'Heupflexorkracht', testDescription: 'HHD in ruglig; LSI berekenen.', reference: 'Thorborg et al. (2010)', targetValue: 'LSI ≥80%', targetUnit: 'procent', inputType: 'NUMERIC', isBonus: false },
        { name: 'Single leg balance', testDescription: 'Staand op één been, ogen open, 30 sec; minimale posturale sway.', reference: 'Springer et al. (2007), ICC 0.92', targetValue: '≥30 sec, minimale sway', targetUnit: 'seconden', inputType: 'NUMERIC', isBonus: false },
        { name: 'Single leg squat', testDescription: 'Kwalitatieve beoordeling: knie-valgus, Trendelenburg, trunk flexie.', reference: 'Crossley et al. (2011)', targetValue: 'Goed: geen compensaties', targetUnit: 'kwalitatief', inputType: 'TEXT', isBonus: false },
        { name: 'Star Excursion Balance Test (SEBT)', testDescription: 'Anterior, posteromedial, posterolateral reach; genormaliseerd naar beenlengte.', reference: 'Gribble et al. (2012), ICC 0.85-0.93', targetValue: 'LSI ≥90% alle richtingen', targetUnit: 'procent', inputType: 'NUMERIC', isBonus: false },
        { name: 'Step-down test (Duke)', testDescription: 'Laterale step-down van 20 cm verhoging; kwalitatieve beoordeling.', reference: 'Piva et al. (2006)', targetValue: 'Goed: gecontroleerde tracking', targetUnit: 'kwalitatief', inputType: 'TEXT', isBonus: false },
      ],
    },
    {
      order: 4,
      shortName: 'Fase 4',
      name: 'Fase 4: Functionele Opbouw (Week 14-20)',
      description: 'Hogere functionele belasting: langere loopafstanden, traplopen, sport-gerelateerde taken. Plyometrische introductie.',
      keyGoals: ['Heupkracht LSI ≥90% alle spiergoepen', 'Tolerantie impact- en plyometrische belasting', 'Volledige ADL onafhankelijkheid'],
      typicalStartWeek: 14,
      typicalEndWeek: 20,
      criteria: [
        { name: 'Heupabductorkracht', testDescription: 'HHD in zijlig; LSI berekenen.', reference: 'Thorborg et al. (2010)', targetValue: 'LSI ≥90%', targetUnit: 'procent', inputType: 'NUMERIC', isBonus: false },
        { name: 'Heupextensorkracht', testDescription: 'HHD in buiklig, knie 90°; LSI berekenen.', reference: 'Thorborg et al. (2010)', targetValue: 'LSI ≥90%', targetUnit: 'procent', inputType: 'NUMERIC', isBonus: false },
        { name: '6-minuten looptest', testDescription: 'Gestandaardiseerd protocol; afstand in 6 minuten.', reference: 'ATS (2002), ICC 0.95', targetValue: '≥80% leeftijdsnorm', targetUnit: 'procent', inputType: 'NUMERIC', isBonus: false },
        { name: 'Timed Stair Climb Test', testDescription: 'Op en neer 12 treden, gechronometreerd.', reference: 'Bennell et al. (2011), ICC 0.90', targetValue: '≤ gemiddelde leeftijdsgroep', targetUnit: 'seconden', inputType: 'NUMERIC', isBonus: false },
        { name: 'HOS-Sport subscale', testDescription: 'Hip Outcome Score Sport; 8 items sportgerelateerde functie.', reference: 'Martin & Philippon (2007), MCID 6', targetValue: '≥70%', targetUnit: 'procent', inputType: 'NUMERIC', isBonus: false },
        { name: 'Single leg hop test', testDescription: 'Afstandshop op één been; LSI berekenen.', reference: 'Kivlan & Martin (2012)', targetValue: 'LSI ≥80%', targetUnit: 'procent', inputType: 'NUMERIC', isBonus: false },
      ],
    },
    {
      order: 5,
      shortName: 'Fase 5',
      name: 'Fase 5: Return to Sport / Activiteit (Week 20-32)',
      description: 'Voorbereiding volledige sporthervatting. Sport-specifieke training, multidirectionele agility, hoge-intensiteit plyometrie. RTS 4-8 mnd postoperatief.',
      keyGoals: ['Volledige sport-specifieke kracht LSI ≥95%', 'Succesvolle sport-specifieke trainingsopbouw', 'Psychologische bereidheid sport'],
      typicalStartWeek: 20,
      typicalEndWeek: 32,
      criteria: [
        { name: 'Heupabductorkracht', testDescription: 'HHD in zijlig; LSI berekenen.', reference: 'Thorborg et al. (2010)', targetValue: 'LSI ≥95%', targetUnit: 'procent', inputType: 'NUMERIC', isBonus: false },
        { name: 'Triple hop test', testDescription: 'Drie opeenvolgende éénbensprongen; totale afstand en LSI.', reference: 'Kivlan & Martin (2012)', targetValue: 'LSI ≥90%', targetUnit: 'procent', inputType: 'NUMERIC', isBonus: false },
        { name: 'T-test agility', testDescription: 'Multidirectionele agility: vooruit-links-rechts-achteruit patroon.', reference: 'Pauole et al. (2000), ICC 0.98', targetValue: 'LSI ≥90% of ≤ sportnorm', targetUnit: 'procent/seconden', inputType: 'NUMERIC', isBonus: false },
        { name: 'iHOT-33', testDescription: 'Internationale heup uitkomstmaat 33 items.', reference: 'Mohtadi et al. (2012), MCID 6.1', targetValue: '≥80/100', targetUnit: 'punten', inputType: 'NUMERIC', isBonus: false },
        { name: 'HOS-Sport', testDescription: 'Hip Outcome Score Sport subscale.', reference: 'Martin & Philippon (2007)', targetValue: '≥90%', targetUnit: 'procent', inputType: 'NUMERIC', isBonus: false },
        { name: 'ACL-RSI (aangepast voor heup)', testDescription: 'Psychologische bereidheid voor sporthervatting.', reference: 'Webster et al. (2008), aangepast', targetValue: '≥60/100', targetUnit: 'punten', inputType: 'NUMERIC', isBonus: false },
      ],
    },
    {
      order: 6,
      shortName: 'Fase 6',
      name: 'Fase 6: Preventie van Recidief (Maand 8+)',
      description: 'Behoud heupkracht en neuromusculaire controle. Zelfmanagement trainingsbelasting. Periodieke monitoring 3-maandelijks.',
      keyGoals: ['Behoud heupkracht en neuromusculaire controle', 'Zelfmanagement trainingsbelasting', 'Vroege detectie symptoomrecidief'],
      typicalStartWeek: 32,
      typicalEndWeek: null,
      criteria: [
        { name: 'Heupabductorkracht', testDescription: 'HHD in zijlig; LSI onderhoud.', reference: 'Thorborg et al. (2010)', targetValue: 'LSI ≥90%', targetUnit: 'procent', inputType: 'NUMERIC', isBonus: false },
        { name: 'iHOT-33', testDescription: 'Internationale heup uitkomstmaat; afname elke 3 maanden.', reference: 'Mohtadi et al. (2012), MCID 6.1', targetValue: '≥80/100 (geen daling >MCID)', targetUnit: 'punten', inputType: 'NUMERIC', isBonus: false },
        { name: 'HOS-ADL', testDescription: 'Hip Outcome Score ADL subscale.', reference: 'Martin & Philippon (2007)', targetValue: '≥95%', targetUnit: 'procent', inputType: 'NUMERIC', isBonus: false },
        { name: 'FABER/FADIR monitoring', testDescription: 'Provocatietesten; monitoring impingement recidief.', reference: 'Martin & Sekiya (2008)', targetValue: 'Negatief', targetUnit: 'pass/fail', inputType: 'PASS_FAIL', isBonus: false },
        { name: 'Trainingsbelasting (ACWR)', testDescription: 'Acute:Chronic Workload Ratio zelfregistratie.', reference: 'Gabbett (2016)', targetValue: 'ACWR 0.8-1.3', targetUnit: 'ratio', inputType: 'NUMERIC', isBonus: false },
        { name: 'Patient Acceptable Symptom State (PASS)', testDescription: 'Eén vraag: Is uw huidige toestand bevredigend?', reference: 'Tubach et al. (2005)', targetValue: 'Ja', targetUnit: 'pass/fail', inputType: 'PASS_FAIL', isBonus: false },
      ],
    },
  ],
}
