export const HIP_ARTHROPLASTY_PROTOCOL = {
  protocol: {
    key: 'totale-heupprothese',
    name: 'Totale Heupprothese — Criteria-Based Revalidatie',
    description: 'Protocol voor actieve patiënten na totale heupprothese, gericht op functioneel herstel en terugkeer naar recreatieve sport, met criteria-based progressie en approach-specifieke voorzorgsmaatregelen.',
    specialty: 'hip_arthroplasty',
    sourceReference: 'Movement Based Therapy Amsterdam (2026). Criteria-Based Revalidatieprotocol: Totale Heupprothese (THP) — Actieve Populatie, Versie 1.0',
  },
  phases: [
    {
      order: 0,
      shortName: 'Pre-op',
      name: 'Pre-operatieve Fase: Gereed voor Operatie',
      description: 'Prehabilitatie voor optimalisering van kracht en aerobe conditie, met documentatie van basale functiemetingen en patiënteducatie over prothese-specifieke voorzorgsmaatregelen.',
      keyGoals: [
        'Optimaliseren van kracht en aerobe conditie pre-operatief',
        'Patiënteducatie: prothese-specifieke voorzorgsmaatregelen en sportverwachtingen',
        'Baseline metingen vastleggen voor postoperatieve monitoring',
      ],
      typicalStartWeek: -4,
      typicalEndWeek: 0,
      criteria: [
        {
          name: 'Timed Up and Go',
          testDescription: 'Opstaan, 3m lopen, omdraaien, terugzitten.',
          reference: 'Podsiadlo & Richardson (1991)',
          targetValue: 'Baseline vastleggen',
          targetUnit: 'sec',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: '5x Sit-to-Stand',
          testDescription: '5 keer opstaan uit stoel zonder armen.',
          reference: 'Bohannon (2006)',
          targetValue: 'Baseline vastleggen',
          targetUnit: 'sec',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: '6-minuten looptest',
          testDescription: 'Gestandaardiseerd ATS protocol.',
          reference: 'ATS (2002)',
          targetValue: 'Baseline vastleggen',
          targetUnit: 'm',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'HOOS',
          testDescription: 'Hip Disability and Osteoarthritis Outcome Score.',
          reference: 'Nilsdotter et al. (2003)',
          targetValue: 'Baseline vastleggen',
          targetUnit: '',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'Oxford Hip Score',
          testDescription: '12-item PROM specifiek voor THP.',
          reference: 'Dawson et al. (1996)',
          targetValue: 'Baseline vastleggen',
          targetUnit: '/48',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'Heupabductorkracht',
          testDescription: 'HHD in zijlig.',
          reference: 'Thorborg et al. (2010)',
          targetValue: 'Baseline vastleggen',
          targetUnit: 'N',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: '10-meter looptest',
          testDescription: 'Comfortabel en maximaal tempo.',
          reference: 'Watson (2002)',
          targetValue: 'Baseline vastleggen',
          targetUnit: 'm/s',
          inputType: 'NUMERIC',
          isBonus: false,
        },
      ],
    },
    {
      order: 1,
      shortName: 'Fase 1',
      name: 'Fase 1: Bescherming & Vroeg Herstel (Week 0-4)',
      description: 'Wondgenezing, controle van oedeem en bescherming van de prothese met strikte naleving van approach-specifieke voorzorgsmaatregelen en vroege mobilisatie.',
      keyGoals: [
        'Bescherming van de prothese (approach-specifieke restricties)',
        'Pijncontrole en oedeemmanagement',
        'Zelfstandige transfers en mobiliteit met hulpmiddelen',
      ],
      typicalStartWeek: 0,
      typicalEndWeek: 4,
      criteria: [
        {
          name: 'Pijn in rust',
          testDescription: 'Visueel Analoge Schaal 0-10.',
          reference: 'Bijur et al. (2001)',
          targetValue: '≤3/10',
          targetUnit: '/10',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'Wondgenezing',
          testDescription: 'Inspectie: geen tekenen van infectie, dehiscentie.',
          reference: '',
          targetValue: 'Ongecompliceerd',
          targetUnit: '',
          inputType: 'PASS_FAIL',
          isBonus: false,
        },
        {
          name: 'TUG met loophulpmiddel',
          testDescription: 'Gechronometreerd met rollator/krukken.',
          reference: 'Podsiadlo & Richardson (1991)',
          targetValue: 'Uitvoerbaar, veilig',
          targetUnit: 'sec',
          inputType: 'TEXT',
          isBonus: false,
        },
        {
          name: 'Actieve heupflexie ROM',
          testDescription: 'Goniometrie, ruglig.',
          reference: 'Clapis et al. (2008)',
          targetValue: '≥70°',
          targetUnit: '°',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'Straight Leg Raise',
          testDescription: 'Actief in ruglig.',
          reference: '',
          targetValue: 'Zelfstandig uitvoerbaar',
          targetUnit: '',
          inputType: 'PASS_FAIL',
          isBonus: false,
        },
        {
          name: 'Transfers',
          testDescription: 'Bed-stoel, stoel-staand, toilet.',
          reference: '',
          targetValue: 'Zelfstandig met hulpmiddel',
          targetUnit: '',
          inputType: 'PASS_FAIL',
          isBonus: false,
        },
      ],
    },
    {
      order: 2,
      shortName: 'Fase 2',
      name: 'Fase 2: Vroege Kracht & Mobiliteit (Week 4-8)',
      description: 'Progressieve belastingopbouw, afbouw van hulpmiddelen, herstel van gangpatroon en opbouw van heupmusculatuur met geleidelijke opheffing van approach-specifieke restricties.',
      keyGoals: [
        'Afbouw van loophulpmiddelen naar zelfstandig lopen',
        'Herstel van veilig gangpatroon zonder compensaties',
        'Opbouw van heupkracht (isometrisch → concentrisch)',
      ],
      typicalStartWeek: 4,
      typicalEndWeek: 8,
      criteria: [
        {
          name: 'TUG zonder hulpmiddel',
          testDescription: 'Gechronometreerd.',
          reference: 'Podsiadlo & Richardson (1991)',
          targetValue: '<20 sec',
          targetUnit: 'sec',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: '10-meter looptest',
          testDescription: 'Comfortabel tempo.',
          reference: 'Watson (2002)',
          targetValue: '≥0.8 m/s',
          targetUnit: 'm/s',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'Actieve heupflexie ROM',
          testDescription: 'Goniometrie.',
          reference: 'Clapis et al. (2008)',
          targetValue: '≥100°',
          targetUnit: '°',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'Actieve heupabductie ROM',
          testDescription: 'Goniometrie in zijlig.',
          reference: 'Clapis et al. (2008)',
          targetValue: '≥25°',
          targetUnit: '°',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'Heupabductorkracht',
          testDescription: 'HHD.',
          reference: 'Thorborg et al. (2010)',
          targetValue: '≥50% LSI',
          targetUnit: '%',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'Gangpatroon',
          testDescription: 'Observationeel: Trendelenburg, staplengte, afwikkeling.',
          reference: 'Perry & Burnfield (2010)',
          targetValue: 'Trendelenburg-negatief, symmetrische staplengte',
          targetUnit: '',
          inputType: 'PASS_FAIL',
          isBonus: false,
        },
      ],
    },
    {
      order: 3,
      shortName: 'Fase 3',
      name: 'Fase 3: Functionele Kracht & Neuromusculaire Controle (Week 8-14)',
      description: 'Ontwikkeling van functionele kracht en dynamische stabiliteit met progressieve weerstandstraining, balanstraining en start van laag-impact recreatieve activiteiten.',
      keyGoals: [
        'Heupkracht LSI ≥70% (abductoren, extensoren)',
        'Adequate dynamische balans en proprioceptie',
        'Start van laag-impact recreatieve activiteiten (fietsen, zwemmen)',
      ],
      typicalStartWeek: 8,
      typicalEndWeek: 14,
      criteria: [
        {
          name: 'Heupabductorkracht',
          testDescription: 'HHD.',
          reference: 'Thorborg et al. (2010)',
          targetValue: 'LSI ≥70%',
          targetUnit: '%',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'Heupextensorkracht',
          testDescription: 'HHD.',
          reference: 'Thorborg et al. (2010)',
          targetValue: 'LSI ≥70%',
          targetUnit: '%',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'TUG',
          testDescription: 'Gechronometreerd.',
          reference: 'Podsiadlo & Richardson (1991)',
          targetValue: '<12 sec',
          targetUnit: 'sec',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: '5x Sit-to-Stand',
          testDescription: '5 keer opstaan zonder armen.',
          reference: 'Bohannon (2006)',
          targetValue: '≤ leeftijdsgemiddelde (60-69: 11.4s; 70-79: 12.6s)',
          targetUnit: 'sec',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'Single leg balance',
          testDescription: 'Ogen open, 30 sec.',
          reference: 'Springer et al. (2007)',
          targetValue: '≥15 sec operatiezijde',
          targetUnit: 'sec',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: '6-minuten looptest',
          testDescription: 'ATS protocol.',
          reference: 'ATS (2002)',
          targetValue: '≥400m',
          targetUnit: 'm',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'HOOS-Sport',
          testDescription: 'Sport/recreatie subscale.',
          reference: 'Nilsdotter et al. (2003)',
          targetValue: '≥50%',
          targetUnit: '%',
          inputType: 'NUMERIC',
          isBonus: false,
        },
      ],
    },
    {
      order: 4,
      shortName: 'Fase 4',
      name: 'Fase 4: Functionele Opbouw (Week 14-24)',
      description: 'Hogere functionele belasting met traplopen, langere loopafstanden en verhoogde weerstandstraining; start van sport-specifieke voorbereiding en voorzichtige impactbelasting.',
      keyGoals: [
        'Heupkracht LSI ≥85% (abductoren, extensoren, flexoren)',
        'Volledige ADL-onafhankelijkheid inclusief traplopen en autorijden',
        'Start sport-specifieke voorbereiding (tennis, wandelen, skiën)',
      ],
      typicalStartWeek: 14,
      typicalEndWeek: 24,
      criteria: [
        {
          name: 'Heupabductorkracht',
          testDescription: 'HHD.',
          reference: 'Thorborg et al. (2010)',
          targetValue: 'LSI ≥85%',
          targetUnit: '%',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'Heupextensorkracht',
          testDescription: 'HHD.',
          reference: 'Thorborg et al. (2010)',
          targetValue: 'LSI ≥85%',
          targetUnit: '%',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'Stair Climb Test',
          testDescription: '12 treden op en neer, gechronometreerd.',
          reference: 'Bennell et al. (2011)',
          targetValue: '≤ leeftijdsgemiddelde',
          targetUnit: 'sec',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: '6-minuten looptest',
          testDescription: 'ATS protocol.',
          reference: 'ATS (2002)',
          targetValue: '≥500m',
          targetUnit: 'm',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: '10-meter looptest maximaal',
          testDescription: 'Maximaal tempo.',
          reference: 'Watson (2002)',
          targetValue: '≥1.2 m/s',
          targetUnit: 'm/s',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'Oxford Hip Score',
          testDescription: '12-item PROM.',
          reference: 'Dawson et al. (1996)',
          targetValue: '≥38/48',
          targetUnit: '/48',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'Single leg balance',
          testDescription: 'Ogen open.',
          reference: 'Springer et al. (2007)',
          targetValue: '≥25 sec operatiezijde',
          targetUnit: 'sec',
          inputType: 'NUMERIC',
          isBonus: false,
        },
      ],
    },
    {
      order: 5,
      shortName: 'Fase 5',
      name: 'Fase 5: Return to Sport / Activiteit (Week 24-40)',
      description: 'Voorbereiding voor terugkeer naar recreatieve sport met evaluatie van sport-specifieke fitness, impacttoleratie en patiënt-gerapporteerde activiteitsniveau.',
      keyGoals: [
        'Heupkracht LSI ≥90% voor sport-specifieke taken',
        'Succesvolle graduele sporthervatting zonder symptomen',
        'Patiënt kan trainingsbelasting zelfstandig reguleren',
      ],
      typicalStartWeek: 24,
      typicalEndWeek: 40,
      criteria: [
        {
          name: 'Heupabductorkracht',
          testDescription: 'HHD.',
          reference: 'Thorborg et al. (2010)',
          targetValue: 'LSI ≥90%',
          targetUnit: '%',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'Heupextensorkracht',
          testDescription: 'HHD.',
          reference: 'Thorborg et al. (2010)',
          targetValue: 'LSI ≥90%',
          targetUnit: '%',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'TUG',
          testDescription: 'Gechronometreerd.',
          reference: 'Podsiadlo & Richardson (1991)',
          targetValue: '<9 sec',
          targetUnit: 'sec',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: '6-minuten looptest',
          testDescription: 'ATS protocol.',
          reference: 'ATS (2002)',
          targetValue: '≥80% leeftijdsnorm',
          targetUnit: '%',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'Single leg hop',
          testDescription: 'Afstandshop, LSI.',
          reference: 'Kivlan & Martin (2012)',
          targetValue: 'LSI ≥80%',
          targetUnit: '%',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'HOOS-Sport',
          testDescription: 'Sport/recreatie subscale.',
          reference: 'Nilsdotter et al. (2003)',
          targetValue: '≥75%',
          targetUnit: '%',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'UCLA Activity Score',
          testDescription: 'Activiteitsniveau schaal 1-10.',
          reference: 'Zahiri et al. (1998)',
          targetValue: '≥6',
          targetUnit: '/10',
          inputType: 'NUMERIC',
          isBonus: false,
        },
      ],
    },
    {
      order: 6,
      shortName: 'Fase 6',
      name: 'Fase 6: Preventie van Recidief & Langetermijnonderhoud (Maand 10+)',
      description: 'Langdurig behoud van functionele winst en prothesestand met periodieke monitoring van kracht, functie en patiënt-gerapporteerde uitkomsten.',
      keyGoals: [
        'Behoud van heupkracht en functionele fitness op lange termijn',
        'Zelfmanagement: patiënt reguleert activiteitniveau in relatie tot prothese',
        'Vroege detectie van protheseproblematiek (loslating, slijtage)',
      ],
      typicalStartWeek: 40,
      typicalEndWeek: null,
      criteria: [
        {
          name: 'Heupabductorkracht',
          testDescription: 'HHD.',
          reference: 'Thorborg et al. (2010)',
          targetValue: 'LSI ≥85%',
          targetUnit: '%',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'TUG',
          testDescription: 'Gechronometreerd.',
          reference: 'Podsiadlo & Richardson (1991)',
          targetValue: '<12 sec',
          targetUnit: 'sec',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: '6-minuten looptest',
          testDescription: 'ATS protocol.',
          reference: 'ATS (2002)',
          targetValue: 'Stabiel (geen daling >50m)',
          targetUnit: 'm',
          inputType: 'TEXT',
          isBonus: false,
        },
        {
          name: 'Oxford Hip Score',
          testDescription: '12-item PROM.',
          reference: 'Dawson et al. (1996)',
          targetValue: '≥38/48',
          targetUnit: '/48',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'HOOS',
          testDescription: 'Volledige score.',
          reference: 'Nilsdotter et al. (2003)',
          targetValue: 'Stabiel (geen daling >10 punten)',
          targetUnit: 'punten',
          inputType: 'TEXT',
          isBonus: false,
        },
        {
          name: 'UCLA Activity Score',
          testDescription: 'Activiteitsniveau.',
          reference: 'Zahiri et al. (1998)',
          targetValue: '≥5',
          targetUnit: '/10',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'PASS',
          testDescription: 'Is uw huidige toestand bevredigend?',
          reference: 'Tubach et al. (2005)',
          targetValue: 'Ja',
          targetUnit: '',
          inputType: 'PASS_FAIL',
          isBonus: false,
        },
      ],
    },
  ],
}

export const BANKART_PROTOCOL = {
  protocol: {
    key: 'bankart-reparatie',
    name: 'Bankart Reparatie — Criteria-Based Post-Operatief Revalidatie',
    description: 'Protocol voor anterieure schouderinstabiliteit na arthroscopische Bankart reparatie, met nadruk op proprioceptie, dynamische stabiliteit en geleidelijke ROM-opbouw met strenge ER-restricties in vroege fasen.',
    specialty: 'shoulder_bankart',
    sourceReference: 'Movement Based Therapy Amsterdam (2026). Criteria-Based Post-Operatief Revalidatieprotocol: Bankart Reparatie, Versie 1.0',
  },
  phases: [
    {
      order: 0,
      shortName: 'Pre-op',
      name: 'Pre-operatieve Fase: Gereed voor Operatie',
      description: 'Optimalisatie van dynamische stabilisatoren en documentatie van baseline ROM, kracht en proprioceptie met educatie over ROM-restricties en lange revalidatietraject.',
      keyGoals: [
        'Optimaliseren dynamische schouderstabilisatoren (RC-kracht, scapulaire controle)',
        'Baseline documentatie: ROM, kracht, instabiliteitsscores, proprioceptie',
        'Patiënteducatie: verwachtingen, ROM-restricties, tijdlijn contactsport',
      ],
      typicalStartWeek: -2,
      typicalEndWeek: 0,
      criteria: [
        {
          name: 'Passieve ROM',
          testDescription: 'Goniometrie flexie, abductie, ER, IR.',
          reference: 'Norkin & White (2016)',
          targetValue: 'Baseline documentatie',
          targetUnit: '°',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'Isometrische ER/IR kracht',
          testDescription: 'HHD zittend, elleboog 90°.',
          reference: 'Kolber et al. (2007)',
          targetValue: 'Baseline + ER/IR ratio',
          targetUnit: 'N',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'WOSI',
          testDescription: '21 items, 0-2100 schaal specifiek voor instabiliteit.',
          reference: 'Kirkley et al. (1998)',
          targetValue: 'Baseline documentatie',
          targetUnit: 'punten',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'Apprehension test',
          testDescription: 'Ruglig, 90° abductie, progressieve ER.',
          reference: 'Lo et al. (2004)',
          targetValue: 'Documentatie (verwacht positief pre-op)',
          targetUnit: '',
          inputType: 'PASS_FAIL',
          isBonus: false,
        },
        {
          name: 'Proprioceptie JPRT',
          testDescription: 'Joint Position Reproduction Test naar 45° ER, ogen dicht.',
          reference: 'Zuckerman et al. (2003)',
          targetValue: 'Baseline absolute error',
          targetUnit: '°',
          inputType: 'NUMERIC',
          isBonus: false,
        },
      ],
    },
    {
      order: 1,
      shortName: 'Fase 1',
      name: 'Fase 1: Bescherming & Vroeg Herstel (Week 0-4)',
      description: 'Gerepareerde anterieure labrum beschermen met strikte 0° ER-restrictie en sling naleving; vroege pendel- en scapulaire oefeningen zonder labrale belasting.',
      keyGoals: [
        'Bescherming anterieur labrum: geen ER voorbij 0°, sling compliance',
        'Pijncreductie en oedeemmanagement',
        'Behoud passieve flexie en veilige scapulaire activatie',
      ],
      typicalStartWeek: 0,
      typicalEndWeek: 4,
      criteria: [
        {
          name: 'Passieve flexie',
          testDescription: 'Goniometrie ruglig, therapeut-geleid.',
          reference: 'Norkin & White (2016)',
          targetValue: '≥120°',
          targetUnit: '°',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'Passieve ER',
          testDescription: 'Goniometrie ruglig, arm langs lichaam, elleboog 90°.',
          reference: '',
          targetValue: 'Maximaal 0° (geen ER voorbij neutraal)',
          targetUnit: '°',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'VAS pijn',
          testDescription: 'Visual Analogue Scale 0-10.',
          reference: 'Hawker et al. (2011)',
          targetValue: '≤3/10 in rust',
          targetUnit: '/10',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'Scapulaire retractie',
          testDescription: 'Isometrische squeeze, 10 sec hold, pijnvrij.',
          reference: '',
          targetValue: 'Symmetrisch, 10 sec hold',
          targetUnit: 'sec',
          inputType: 'TEXT',
          isBonus: false,
        },
        {
          name: 'Sling compliance',
          testDescription: 'Draagt sling conform afspraak.',
          reference: '',
          targetValue: '>90% compliance',
          targetUnit: '%',
          inputType: 'NUMERIC',
          isBonus: false,
        },
      ],
    },
    {
      order: 2,
      shortName: 'Fase 2',
      name: 'Fase 2: Actieve Mobiliteit & Vroege Kracht (Week 4-10)',
      description: 'Voorzichtige uitbreiding van exorotatie met +10° per week tot 30-40°; transitie naar actieve ROM met nadruk op scapulohumeraal ritme en proprioceptieve retraining.',
      keyGoals: [
        'Geleidelijke uitbreiding exorotatie (0° → 30-40°) met monitoring',
        'Herstel actieve ROM in flexie en abductie',
        'Opstarten isometrische RC-kracht en proprioceptie',
      ],
      typicalStartWeek: 4,
      typicalEndWeek: 10,
      criteria: [
        {
          name: 'Actieve flexie',
          testDescription: 'Goniometrie staand, actief.',
          reference: 'Norkin & White (2016)',
          targetValue: '≥150° of >85% LSI',
          targetUnit: '°',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'Passieve ER progressief',
          testDescription: 'Goniometrie ruglig, elleboog 90°, arm langs lichaam.',
          reference: '',
          targetValue: '30-40° (einde fase)',
          targetUnit: '°',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'Scapula laterale verschuivingstest',
          testDescription: 'LSST Kibler: 3 posities.',
          reference: 'Kibler (1998)',
          targetValue: 'Asymmetrie <1.5 cm',
          targetUnit: 'cm',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'Isometrische ER kracht',
          testDescription: 'HHD zittend, elleboog 90°, arm in neutraal (0° ER), isometrisch.',
          reference: 'Kolber et al. (2007)',
          targetValue: '≥40% LSI, pijnvrij',
          targetUnit: '%',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'Proprioceptie JPRT',
          testDescription: 'Joint Position Reproduction Test naar 30° ER, actief, ogen dicht.',
          reference: 'Zuckerman et al. (2003)',
          targetValue: 'Absolute error <8°',
          targetUnit: '°',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'Apprehension test',
          testDescription: '90° abductie, voorzichtige ER.',
          reference: 'Lo et al. (2004)',
          targetValue: 'Negatief bij 30° ER',
          targetUnit: '',
          inputType: 'PASS_FAIL',
          isBonus: false,
        },
      ],
    },
    {
      order: 3,
      shortName: 'Fase 3',
      name: 'Fase 3: Kracht & Neuromusculaire Controle (Week 10-20)',
      description: 'Progressieve krachtoefeningen door volledig ROM met focus op dynamische stabiliteit en proprioceptieve training in toenemend uitdagende posities.',
      keyGoals: [
        'Progressieve kracht RC en scapulaire stabilisatoren door volledig ROM',
        'Dynamische stabiliteit in open en gesloten keten',
        'Proprioceptie in end-range posities (apprehension-vrij)',
      ],
      typicalStartWeek: 10,
      typicalEndWeek: 20,
      criteria: [
        {
          name: 'ER/IR krachtratio',
          testDescription: 'HHD zittend, elleboog 90°, maximaal isometrisch.',
          reference: 'Cools et al. (2016)',
          targetValue: 'Ratio ≥0.66',
          targetUnit: 'ratio',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'ER kracht LSI',
          testDescription: 'HHD maximale isometrische ER.',
          reference: 'Kolber et al. (2007)',
          targetValue: '≥65% LSI',
          targetUnit: '%',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'Passieve ER in 90° abductie',
          testDescription: 'Goniometrie ruglig, 90° abductie.',
          reference: 'Norkin & White (2016)',
          targetValue: '≥60° of >80% LSI',
          targetUnit: '°',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'CKCUEST',
          testDescription: 'Closed Kinetic Chain UE Stability Test: push-up positie, 91.4 cm, alternerend hand aanraken, 15 sec.',
          reference: 'Goldbeck & Davies (2000)',
          targetValue: '≥65% LSI',
          targetUnit: '%',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'Apprehension test',
          testDescription: '90° abductie, ER tot 60°.',
          reference: 'Lo et al. (2004)',
          targetValue: 'Negatief bij 60° ER in 90° abductie',
          targetUnit: '',
          inputType: 'PASS_FAIL',
          isBonus: false,
        },
        {
          name: 'WOSI',
          testDescription: '0-2100 schaal.',
          reference: 'Kirkley et al. (1998)',
          targetValue: 'Verbetering ≥400 punten t.o.v. pre-op',
          targetUnit: 'punten',
          inputType: 'NUMERIC',
          isBonus: false,
        },
      ],
    },
    {
      order: 4,
      shortName: 'Fase 4',
      name: 'Fase 4: Functionele Opbouw & Sport-Specifieke Training (Week 20-36)',
      description: 'Sport-specifieke training met toenemende complexiteit; perturbatietraining en reactieve stabiliteit; plyometrische training voor reactieve stiffness.',
      keyGoals: [
        'Sport-specifieke kracht, power en reactieve stabiliteit',
        'Perturbatietraining in instabiliteit-provocerende posities',
        'Bereiken van volledige ER in 90° abductie zonder apprehension',
      ],
      typicalStartWeek: 20,
      typicalEndWeek: 36,
      criteria: [
        {
          name: 'ER kracht LSI',
          testDescription: 'HHD maximale isometrische ER.',
          reference: 'Kolber et al. (2007)',
          targetValue: '≥80% LSI',
          targetUnit: '%',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'ER in 90° abductie',
          testDescription: 'Goniometrie: volledige passieve ER in 90° abductie.',
          reference: 'Norkin & White (2016)',
          targetValue: '≥80° of >90% LSI',
          targetUnit: '°',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'Seated Shot Put Test',
          testDescription: 'Zittend, medicinbal (2-3 kg) vanuit borsthoogte.',
          reference: 'Negrete et al. (2010)',
          targetValue: '≥80% LSI',
          targetUnit: '%',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'Y-Balance Test UE',
          testDescription: 'Push-up positie, reikafstanden 3 richtingen.',
          reference: 'Gorman et al. (2012)',
          targetValue: 'Composite ≥80% LSI',
          targetUnit: '%',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'CKCUEST',
          testDescription: '15 sec test.',
          reference: 'Goldbeck & Davies (2000)',
          targetValue: '≥80% LSI',
          targetUnit: '%',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'Apprehension test',
          testDescription: '90° abductie, maximale ER (end-range).',
          reference: 'Lo et al. (2004)',
          targetValue: 'Negatief in end-range',
          targetUnit: '',
          inputType: 'PASS_FAIL',
          isBonus: false,
        },
        {
          name: 'WOSI',
          testDescription: '0-2100 schaal.',
          reference: 'Kirkley et al. (1998)',
          targetValue: '≤600/2100',
          targetUnit: 'punten',
          inputType: 'NUMERIC',
          isBonus: false,
        },
      ],
    },
    {
      order: 5,
      shortName: 'Fase 5',
      name: 'Fase 5: Return to Sport (Week 36+, minimaal 9 maanden voor contactsport)',
      description: 'Minimaal 9 maanden post-operatief voor contactsport; evaluatie van volledige dynamische stabiliteit, psychologische readiness en sport-specifieke provocatietests.',
      keyGoals: [
        'Bevestigen volledige dynamische stabiliteit onder maximale sportbelasting',
        'Psychologische readiness: geen angst in provocatieve posities',
        'Gecontroleerde sporthervatting met recidiefmonitoring',
      ],
      typicalStartWeek: 36,
      typicalEndWeek: null,
      criteria: [
        {
          name: 'ER kracht LSI',
          testDescription: 'HHD maximale isometrische ER.',
          reference: 'Kolber et al. (2007)',
          targetValue: '≥90% LSI',
          targetUnit: '%',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'IR kracht LSI',
          testDescription: 'HHD maximale isometrische IR.',
          reference: 'Kolber et al. (2007)',
          targetValue: '≥90% LSI',
          targetUnit: '%',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'Abductie kracht LSI',
          testDescription: 'HHD maximale isometrische abductie scapulair vlak.',
          reference: '',
          targetValue: '≥90% LSI',
          targetUnit: '%',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'CKCUEST',
          testDescription: '15 sec test.',
          reference: 'Goldbeck & Davies (2000)',
          targetValue: '≥90% LSI',
          targetUnit: '%',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'Seated Shot Put Test',
          testDescription: '2-3 kg medicinbal.',
          reference: 'Negrete et al. (2010)',
          targetValue: '≥90% LSI',
          targetUnit: '%',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'YBT-UE',
          testDescription: 'Composite score.',
          reference: 'Gorman et al. (2012)',
          targetValue: '≥90% LSI',
          targetUnit: '%',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'Apprehension test',
          testDescription: 'End-range, 90° abductie + maximale ER.',
          reference: 'Lo et al. (2004)',
          targetValue: 'Negatief, geen angst',
          targetUnit: '',
          inputType: 'PASS_FAIL',
          isBonus: false,
        },
        {
          name: 'WOSI',
          testDescription: '0-2100 schaal.',
          reference: 'Kirkley et al. (1998)',
          targetValue: '≤400/2100',
          targetUnit: 'punten',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'SI-RSI',
          testDescription: 'Shoulder Instability-Return to Sport after Injury: 12 items, 0-100%.',
          reference: 'Geerts et al. (2019)',
          targetValue: '≥70%',
          targetUnit: '%',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'Sport-specifieke provocatietest',
          testDescription: 'Simulatie sport-specifieke scenario\'s: tackle, armtrekking, val op uitgestrekte arm.',
          reference: '',
          targetValue: 'Geen apprehension, vol vertrouwen',
          targetUnit: '',
          inputType: 'PASS_FAIL',
          isBonus: false,
        },
      ],
    },
    {
      order: 6,
      shortName: 'Fase 6',
      name: 'Fase 6: Preventie van Recidief (Levenslang)',
      description: 'Langdurig onderhoud van dynamische stabiliteit en proprioceptie met periodieke 6-maandelijkse screening en self-monitoring op subluxatie-symptomen.',
      keyGoals: [
        'Behoud van dynamische schouderstabiliteit en RC-kracht',
        'Continue proprioceptieve training en perturbatieoefeningen',
        'Vroege signaalherkenning: subluxatiegevoel, apprehension, giving way',
      ],
      typicalStartWeek: null,
      typicalEndWeek: null,
      criteria: [
        {
          name: 'ER/IR krachtratio',
          testDescription: 'HHD 6-maandelijks.',
          reference: 'Cools et al. (2016)',
          targetValue: 'Ratio ≥0.66, stabiel',
          targetUnit: 'ratio',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'ER kracht LSI',
          testDescription: 'HHD 6-maandelijks.',
          reference: 'Kolber et al. (2007)',
          targetValue: '≥90% LSI behouden',
          targetUnit: '%',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'Apprehension test',
          testDescription: 'End-range test, 6-maandelijks.',
          reference: 'Lo et al. (2004)',
          targetValue: 'Negatief (permanent)',
          targetUnit: '',
          inputType: 'PASS_FAIL',
          isBonus: false,
        },
        {
          name: 'WOSI',
          testDescription: '6-maandelijks.',
          reference: 'Kirkley et al. (1998)',
          targetValue: '≤400/2100 behouden',
          targetUnit: 'punten',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'Proprioceptie JPRT',
          testDescription: 'Joint Position Reproduction 60° ER in 90° abductie.',
          reference: 'Zuckerman et al. (2003)',
          targetValue: 'Absolute error <5°',
          targetUnit: '°',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'Patiënt Self-Monitoring',
          testDescription: 'Wekelijks: subluxatiegevoel (ja/nee), vertrouwen (0-10), pijn (0-10).',
          reference: '',
          targetValue: 'Geen subluxatie, vertrouwen ≥8',
          targetUnit: '/10',
          inputType: 'TEXT',
          isBonus: false,
        },
      ],
    },
  ],
}

export const ROTATOR_CUFF_PROTOCOL = {
  protocol: {
    key: 'rotatorcuff-reparatie',
    name: 'Rotator Cuff Reparatie — Criteria-Based Post-Operatief Revalidatie',
    description: 'Protocol voor arthroscopische rotator cuff reparatie (supraspinatus), criteria-based progressie met aandacht voor biologische genezingstijden van peesweefsel en voorkoming van stijfheid.',
    specialty: 'shoulder_rotator_cuff',
    sourceReference: 'Movement Based Therapy Amsterdam (2026). Criteria-Based Post-Operatief Revalidatieprotocol: Rotator Cuff Reparatie, Versie 1.0',
  },
  phases: [
    {
      order: 0,
      shortName: 'Pre-op',
      name: 'Pre-operatieve Fase: Gereed voor Operatie',
      description: 'Optimalisatie van scapulaire stabiliteit en ROM met baseline documentatie en patiënteducatie over revalidatietraject en criteria-based progressie.',
      keyGoals: [
        'Optimaliseren van scapulaire stabiliteit en beschikbare ROM',
        'Patiënteducatie over verwachtingen, tijdlijn en criteria-based progressie',
        'Baseline metingen vastleggen voor postoperatieve vergelijking (LSI)',
      ],
      typicalStartWeek: -2,
      typicalEndWeek: 0,
      criteria: [
        {
          name: 'Passieve ROM schouder',
          testDescription: 'Goniometrie: flexie, abductie, exo- en endorotatie in ruglig.',
          reference: 'Norkin & White (2016)',
          targetValue: 'Documentatie baseline waarden',
          targetUnit: '°',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'DASH-score',
          testDescription: 'Disabilities of the Arm, Shoulder and Hand. 30 items, 0-100 schaal.',
          reference: 'Beaton et al. (2001)',
          targetValue: 'Baseline documentatie',
          targetUnit: 'punten',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'Isometrische kracht ER/IR',
          testDescription: 'HHD, zittend, elleboog 90° flexie, arm langs lichaam.',
          reference: 'Kolber et al. (2007)',
          targetValue: 'Baseline ER/IR ratio documentatie',
          targetUnit: 'N',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'Scapula laterale verschuivingstest',
          testDescription: 'Kibler LSST: afstand mediale rand scapula in 3 posities.',
          reference: 'Kibler (1998)',
          targetValue: 'Asymmetrie <1.5 cm of documentatie',
          targetUnit: 'cm',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'Patiëntkennis',
          testDescription: 'Mondeling: kan patiënt de fasen benoemen en criteria-based progressie uitleggen.',
          reference: '',
          targetValue: 'Adequate begrip bevestigd',
          targetUnit: '',
          inputType: 'PASS_FAIL',
          isBonus: false,
        },
      ],
    },
    {
      order: 1,
      shortName: 'Fase 1',
      name: 'Fase 1: Bescherming & Vroeg Herstel (Week 0-6)',
      description: 'Bescherming van genezend peesweefsel met passieve ROM in veilige bereiken; collageen type III formatie vereist beperking van actieve elevatie.',
      keyGoals: [
        'Bescherming van het genezende peesweefsel (sling compliance)',
        'Pijncreductie en oedeemmanagement',
        'Behoud/herstel van passieve ROM zonder actieve elevatie',
      ],
      typicalStartWeek: 0,
      typicalEndWeek: 6,
      criteria: [
        {
          name: 'Passieve flexie',
          testDescription: 'Goniometrie ruglig, therapeut-geleid.',
          reference: 'Norkin & White (2016)',
          targetValue: '≥140°',
          targetUnit: '°',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'Passieve exorotatie',
          testDescription: 'Goniometrie ruglig, arm langs lichaam, elleboog 90°.',
          reference: 'Norkin & White (2016)',
          targetValue: '≥30° (week 0-3), ≥45° (week 4-6)',
          targetUnit: '°',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'Passieve abductie',
          testDescription: 'Goniometrie ruglig, scapulair vlak.',
          reference: 'Norkin & White (2016)',
          targetValue: '≥120°',
          targetUnit: '°',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'VAS pijn',
          testDescription: 'Visual Analogue Scale 0-10.',
          reference: 'Hawker et al. (2011)',
          targetValue: '≤3/10 in rust',
          targetUnit: '/10',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'Scapulaire retractie',
          testDescription: 'Isometrische scapula squeeze test: 10 sec hold, geen pijn.',
          reference: '',
          targetValue: '10 sec hold bilateraal symmetrisch, pijnvrij',
          targetUnit: 'sec',
          inputType: 'TEXT',
          isBonus: false,
        },
      ],
    },
    {
      order: 2,
      shortName: 'Fase 2',
      name: 'Fase 2: Actieve Mobiliteit & Vroege Kracht (Week 6-12)',
      description: 'Transitie van passief naar actief met voorzichtige monitoring; actieve ROM zonder weerstand belast pees minimaal terwijl neuromusculaire controle herstelt.',
      keyGoals: [
        'Herstel van volledige actieve ROM (AROM) in alle richtingen',
        'Opstarten isometrische en lichte isotone krachtoefeningen',
        'Normalisatie scapulohumeraal ritme',
      ],
      typicalStartWeek: 6,
      typicalEndWeek: 12,
      criteria: [
        {
          name: 'Actieve flexie',
          testDescription: 'Goniometrie staand/zittend, actief uitgevoerd.',
          reference: 'Norkin & White (2016)',
          targetValue: '≥160° of >90% LSI',
          targetUnit: '°',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'Actieve exorotatie',
          testDescription: 'Goniometrie zittend, elleboog 90°, actief.',
          reference: 'Norkin & White (2016)',
          targetValue: '≥45° of >85% LSI',
          targetUnit: '°',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'Scapula laterale verschuivingstest',
          testDescription: 'LSST Kibler: meting in 3 posities (0°, 45°, 90° abductie).',
          reference: 'Kibler (1998)',
          targetValue: 'Asymmetrie <1.5 cm in alle posities',
          targetUnit: 'cm',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'Isometrische ER kracht',
          testDescription: 'HHD zittend, elleboog 90°, arm langs lichaam, isometrisch.',
          reference: 'Kolber et al. (2007)',
          targetValue: '≥50% LSI, pijnvrij',
          targetUnit: '%',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'DASH-score',
          testDescription: '30 items, 0-100 schaal.',
          reference: 'Beaton et al. (2001)',
          targetValue: 'Verbetering ≥10 punten t.o.v. pre-op',
          targetUnit: 'punten',
          inputType: 'NUMERIC',
          isBonus: false,
        },
      ],
    },
    {
      order: 3,
      shortName: 'Fase 3',
      name: 'Fase 3: Kracht & Neuromusculaire Controle (Week 12-20)',
      description: 'Progressieve weerstandstraining met focus op ER/IR krachtbalans en proprioceptieve training in voorbereiding op functionele taken.',
      keyGoals: [
        'Progressieve kracht opbouw rotatorcuff en scapulaire stabilisatoren',
        'Herstel ER/IR krachtbalans (ratio ≥0.66)',
        'Neuromusculaire controle in gesloten en open keten',
      ],
      typicalStartWeek: 12,
      typicalEndWeek: 20,
      criteria: [
        {
          name: 'ER/IR krachtratio',
          testDescription: 'HHD zittend, elleboog 90°, maximale isometrische ER en IR. Ratio = ER/IR.',
          reference: 'Cools et al. (2016)',
          targetValue: 'Ratio ≥0.66',
          targetUnit: 'ratio',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'ER kracht LSI',
          testDescription: 'HHD maximale isometrische ER.',
          reference: 'Kolber et al. (2007)',
          targetValue: '≥70% LSI',
          targetUnit: '%',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'CKCUEST',
          testDescription: 'Closed Kinetic Chain UE Stability Test: push-up positie, handen 91.4 cm uit elkaar, afwisselend aanraken, 15 sec.',
          reference: 'Goldbeck & Davies (2000)',
          targetValue: '≥70% LSI',
          targetUnit: '%',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'Prone Row Endurance',
          testDescription: 'Buiklig op bank, armen hangend, 2 kg gewicht. Herhaalde horizontale abductie tot falen.',
          reference: 'Tate et al. (2017)',
          targetValue: '≥70% LSI of ≥25 herhalingen',
          targetUnit: 'herhalingen',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'Penn Shoulder Score',
          testDescription: '100-punts schaal: pijn (30), functie (60), tevredenheid (10).',
          reference: 'Leggin et al. (2006)',
          targetValue: '≥60/100',
          targetUnit: '/100',
          inputType: 'NUMERIC',
          isBonus: false,
        },
      ],
    },
    {
      order: 4,
      shortName: 'Fase 4',
      name: 'Fase 4: Functionele Opbouw & Sport-Specifieke Training (Week 20-32)',
      description: 'Sport-specifieke bewegingspatronen en plyometrie; voorzichtige introductie van overhead activiteiten met progressieve belasting.',
      keyGoals: [
        'Sport-specifieke kracht en power ontwikkeling',
        'Introductie overhead activiteiten en plyometrie',
        'Optimaliseren van kracht en uithoudingsvermogen voor return to sport',
      ],
      typicalStartWeek: 20,
      typicalEndWeek: 32,
      criteria: [
        {
          name: 'ER kracht LSI',
          testDescription: 'HHD maximale isometrische ER.',
          reference: 'Kolber et al. (2007)',
          targetValue: '≥85% LSI',
          targetUnit: '%',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'Abductie kracht LSI',
          testDescription: 'HHD maximale isometrische abductie in scapulair vlak.',
          reference: 'Kolber et al. (2007)',
          targetValue: '≥85% LSI',
          targetUnit: '%',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'Seated Shot Put Test',
          testDescription: 'Zittend op stoel, medicinbal (2 kg vrouwen / 3 kg mannen) vanuit borsthoogte.',
          reference: 'Negrete et al. (2010)',
          targetValue: '≥85% LSI',
          targetUnit: '%',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'Y-Balance Test UE',
          testDescription: 'Bovenste extremiteit Y-Balance: steunarm in push-up positie, reikafstanden.',
          reference: 'Gorman et al. (2012)',
          targetValue: 'Composite score ≥85% LSI',
          targetUnit: '%',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'Shoulder Endurance Test',
          testDescription: 'Repetitieve abductie met 2 kg: arm naar 90° scapulair vlak, tempo 1 rep/2 sec tot falen.',
          reference: 'Matsen et al. (1994)',
          targetValue: '≥85% LSI of ≥50 herhalingen',
          targetUnit: 'herhalingen',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'DASH-score',
          testDescription: '30 items, 0-100 schaal.',
          reference: 'Beaton et al. (2001)',
          targetValue: '≤15/100',
          targetUnit: 'punten',
          inputType: 'NUMERIC',
          isBonus: false,
        },
      ],
    },
    {
      order: 5,
      shortName: 'Fase 5',
      name: 'Fase 5: Return to Sport (Week 32+)',
      description: 'Return to sport met stringente criteria; minimaal 6 maanden post-operatief; combinatie van objectieve krachttests en psychologische readiness.',
      keyGoals: [
        'Bevestigen van volledige fysiologische en functionele gereedheid',
        'Evaluatie psychologische readiness (angst-vermijding, vertrouwen)',
        'Gecontroleerde sporthervatting met monitoring',
      ],
      typicalStartWeek: 32,
      typicalEndWeek: null,
      criteria: [
        {
          name: 'ER kracht LSI',
          testDescription: 'HHD maximale isometrische ER.',
          reference: 'Kolber et al. (2007)',
          targetValue: '≥90% LSI',
          targetUnit: '%',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'Abductie kracht LSI',
          testDescription: 'HHD maximale isometrische abductie scapulair vlak.',
          reference: '',
          targetValue: '≥90% LSI',
          targetUnit: '%',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'CKCUEST',
          testDescription: 'Push-up positie, 15 sec.',
          reference: 'Goldbeck & Davies (2000)',
          targetValue: '≥90% LSI',
          targetUnit: '%',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'Seated Shot Put Test',
          testDescription: '2-3 kg medicinbal.',
          reference: 'Negrete et al. (2010)',
          targetValue: '≥90% LSI',
          targetUnit: '%',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'YBT-UE',
          testDescription: 'Composite score.',
          reference: 'Gorman et al. (2012)',
          targetValue: '≥90% LSI',
          targetUnit: '%',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'DASH-score',
          testDescription: '30 items, 0-100 schaal.',
          reference: 'Beaton et al. (2001)',
          targetValue: '≤10/100',
          targetUnit: 'punten',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'Penn Shoulder Score',
          testDescription: '100-punts schaal.',
          reference: 'Leggin et al. (2006)',
          targetValue: '≥80/100',
          targetUnit: '/100',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'SPADI',
          testDescription: 'Shoulder Pain and Disability Index: 13 items, 0-100.',
          reference: 'Roach et al. (1991)',
          targetValue: '≤15/100',
          targetUnit: 'punten',
          inputType: 'NUMERIC',
          isBonus: false,
        },
      ],
    },
    {
      order: 6,
      shortName: 'Fase 6',
      name: 'Fase 6: Preventie van Recidief (Levenslang)',
      description: 'Langdurig onderhoud met structureel programma voor rotatorcuff kracht en scapulaire stabiliteit; periodieke 6-maandelijkse screening en load management.',
      keyGoals: [
        'Behoud van rotatorcuff kracht en ER/IR balans',
        'Continue scapulaire stabilisatie en posturaal bewustzijn',
        'Load management en vroege signaalherkenning',
      ],
      typicalStartWeek: null,
      typicalEndWeek: null,
      criteria: [
        {
          name: 'ER/IR krachtratio',
          testDescription: 'HHD 6-maandelijkse screening.',
          reference: 'Cools et al. (2016)',
          targetValue: 'Ratio ≥0.66, stabiel of verbeterd',
          targetUnit: 'ratio',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'ER kracht LSI',
          testDescription: 'HHD 6-maandelijks.',
          reference: 'Kolber et al. (2007)',
          targetValue: '≥90% LSI behouden',
          targetUnit: '%',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'DASH-score',
          testDescription: '6-maandelijks.',
          reference: 'Beaton et al. (2001)',
          targetValue: '≤10/100 behouden',
          targetUnit: 'punten',
          inputType: 'NUMERIC',
          isBonus: false,
        },
        {
          name: 'Shoulder Endurance Test',
          testDescription: 'Repetitieve abductie, 6-maandelijks.',
          reference: '',
          targetValue: 'Stabiel of verbeterd t.o.v. RTS',
          targetUnit: 'herhalingen',
          inputType: 'TEXT',
          isBonus: false,
        },
        {
          name: 'Patiënt Self-Monitoring',
          testDescription: 'Wekelijkse zelfbeoordeling: pijn (0-10), functie (0-10), vertrouwen (0-10).',
          reference: '',
          targetValue: 'Pijn ≤2, functie ≥8, vertrouwen ≥8',
          targetUnit: '/10',
          inputType: 'TEXT',
          isBonus: false,
        },
      ],
    },
  ],
}
