-- Rehab-trajecten, fase C2: rehab_criterion_status verliest "patientId".
--
-- Dit is de enige echte contract-stap. Eén statement, bewust apart van C1.
--
-- MAG UITSLUITEND NA DEPLOY 2 DRAAIEN: de deploy waarin "patientId" uit het
-- Prisma-model RehabCriterionStatus is gehaald én uit de create in de upsert
-- van src/server/routers/rehab.ts. Draai je dit eerder, dan valt de complete
-- rehab-leeslaag om. Prisma zet bij een findMany zonder select alle
-- modelkolommen in de SELECT-lijst, dus src/lib/rehab-data.ts vraagt dan een
-- kolom op die niet meer bestaat. Dat raakt rehab.getPatientTracker,
-- rehab.getMyTracker, rehab.getTraject, de patiënt- en atleet-dashboards,
-- beide PDF-ingangen en iOS build 78. Schrijven valt ook om, want de create
-- vult "patientId" tot die deploy expliciet.
--
-- Controle vóór je dit draait, moet leeg zijn:
--   grep -rn "patientId" prisma/schema.prisma | sed -n '/RehabCriterionStatus/,$p'
--   grep -n "patientId: input.patientId" src/server/routers/rehab.ts
--
-- C1 heeft de vier policies en de twee indexes die van deze kolom afhingen al
-- weggehaald, dus deze DROP heeft geen pg_depend-afhankelijkheden meer en
-- hoeft geen CASCADE.
--
-- Eenrichtingsdeur. Zodra dit bestand draait en er daarna ook maar één nieuw
-- rehab-traject is aangemaakt, kan de oude unique index
-- (patientId, criterionId) niet meer worden teruggezet zonder dataverlies
-- (zie rollbacksectie in
-- docs/superpowers/specs/2026-07-31-rehab-episodes-migratie-sql.md). Er is
-- geen staging-database: dit bestand draait rechtstreeks tegen productie.
--
-- Geen eigen BEGIN/COMMIT: prisma db execute stuurt dit bestand al als één
-- impliciete transactie.

ALTER TABLE public.rehab_criterion_status DROP COLUMN "patientId";
